### PR TITLE
[REVIEW] fix issue #4156, there should be no prefix of a path for python

### PR DESCRIPTION
**Pull request by kimim**
when python fetch the command line parameters, it will take care of `os.pathsep`. 
If there is some characters before `C:/XXX`, such as `--format=TYPES#C:/XXX`, it will convert this to:
`--format#C;C:/Users/Home/XXX`
That means python will consider `C:/XXX` as two paths. This cause the error as #4156 log:

```
OSError: [Errno 22] Invalid argument: 'C;C:\\dev\\msys64\\Users\\TESTPC Developer\\Documents\\test\\open62541_latest\\open62541\\deps\\ua-nodeset\\Schema\\Opc.Ua.Types.bsd'
```

The solution is moving `TYPES#` as postfix:

`--format=C:/XXX#TYPES`

### CODE REVIEW

**Comment by kimim** [comment]
too long to wait for the CI results.. 
I need to go sleep now..

**Comment by andreasebner** [comment]
@NoelGraf Could you please review the changes?

**Comment by jpfr** [comment]
I'm hesitant to accept this.
Because it will break generator scripts people have in their own build pipeline.

It appears to me we can fix this by working around the call to `os.pathsep`.
Can't you just wrap the input argument string in a quotes `"` to get around this?

**Comment by jpfr** [comment]
@kimim Could you have a look if there is backwards-compatible workaround?

**Comment by kimim** [comment]
I’ve tried quoting the parameter, but cannot avoid the issue. So I have to move the prefix to postfix. 
It seems the path conversion is happened before python get it.
I can have a try once more.

**Comment by kimim** [comment]
@jpfr I use a simpler solution to solve issue #4156 
Could you help review? Thanks.

**Comment by kimim** [comment]
I have a problem that the CI script is running in powershell, which cannot accept an environment variable in posix way..

**Comment by jpfr** [comment]
I think you need to put `"MSYS2_ARG_CONV_EXCL=--import"` into quotes...

**Comment by kimim** [comment]
Try again. On my local bash mintty terminal, I have many options:
- export MSYS2_ARG_CONV_EXCL=--import && python ...
- env MSYS2_ARG_CONV_EXCL=--import   python ...
- MSYS2_ARG_CONV_EXCL=--import   python ...

But all failed in CI's powershell script

**Comment by jpfr** [comment]
Found a way to set the environment that appears to work.
Can you verify in your environment?

**Comment by kimim** [comment]
this is not working inside mingw64 bash environment.
I've tried this way in CMakeList.txt.
cmake manual says ENV only work for the function level.
Here python is invoked inside `add_custom_command` function.

There is a paradox: 
- we do not need to set `MSYS2_ARG_CONV_EXCL` for powershell, because it will not convert path automatically.
- we need `MSYS2_ARG_CONV_EXCL` for mingw64 shell, because it convert path automatically.

How about add more judgement: if MINGW and MINGW64_Shell.
Then the code will not affect powershell script.

Or another solution, we just write it down in MSYS2 manual:
- please `export MSYS2_ARG_CONV_EXCL=--import` before compilation.

**Comment by jpfr** [comment]
> How about add more judgement: if MINGW and MINGW64_Shell.
Then the code will not affect powershell script.

Sounds good!

**Comment by kimim** [comment]
This commit should work for both powershell + mingw and bash + mingw.

**Comment by kimim** [comment]
@opcua-tsn-team-kalycito could you have a test with this PR?
It works on my machine's MingW64 bash shell.

**Comment by jpfr** [comment]
Seems to work.
If there are issues, let's update separately.
Merging!

**Pull request merged**
