### PR TITLE
WIP: initial support for freertos

### PR DESCRIPTION
**Pull request by vatmi**
Draft version supporting freertos with open 62541 using LwiP socket interface.  
Since most of the deafult  socket interfaces were not supported with the used LwiP version 1.4.1 most of them are commented out. The other changes are related to the memory settings in freertos and timing aspects.

This PR is not ready to be merged into master since it changes the default behavior of `tcp_network_tcp.c` in a way that it doesn't work on linux/windows anymore. We need to find a good way to integrate this as a plugin or patch.

### CODE REVIEW

**Comment by vatmi** [comment]
At the moment the server set up without any issues.  I have tested the tutorial_test_server with a tutorial_test_client. This one is able to read the string feedback. But the problem with my current set up is that as soon as a client establishes a connection LwiP goes down. This can be my specific LwiP settings issues related to memory on the memory constraint STM 32 board.

**Comment by Gfast2** [comment]
Hi @vatmi ,
It's very cool that you are trying to port _**open62541**_ project to FreeRTOS+LWIP! 😎  🤝 
Right now I'm working on a project based on [**_ESP32_**](http://esp32.net/), which is another plattform based on FreeRTOS+LWIP sets. It features a tone of goodies -> _Wifi, Ethernet, Bluetooth, 32bit Dual Core@240MHz, 512KB Ram, 2/4/8/16 MB Flash, UARTx2, I2C, I2S, SD_MMC Driver, ULP, DAC, CAN..._ And with a incredible preis tag: about 6€ like [_**this one**_](http://www.ebay.de/itm/162482915954?_trksid=p2380057.m570.l5999&_trkparms=gh1g%3DI162482915954.N36.S2.R2.TR5). So I believe it should be the ultimate platform for IoT and event IIoT applications. (I've emailed the Chip Vender. They guarantee 12 years manufacture commitments) (But it's not ARM based, but [_**Tensilica's Xtensa**_](https://en.wikipedia.org/wiki/Tensilica))

---

I've tried around this pull request for a couple of hours. Unlucky I can't build _**open62541**_ according to the instructions from the [_**official Tutorial**_](https://open62541.org/doc/current/building.html#building-the-examples). I can `cmake ..` it, but when I tried to `make` it, I got stuck with this error:
```
gfast2@gfast2-VB:~/workspace/open62541_vatmi/build$ make
[  1%] Built target open62541-generator-types
[  3%] Building C object CMakeFiles/open62541-plugins.dir/plugins/ua_network_tcp.c.o
cc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
cc: error: nano.specs: No such file or directory
CMakeFiles/open62541-plugins.dir/build.make:78: recipe for target 'CMakeFiles/open62541-plugins.dir/plugins/ua_network_tcp.c.o' failed
make[2]: *** [CMakeFiles/open62541-plugins.dir/plugins/ua_network_tcp.c.o] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/open62541-plugins.dir/all' failed
make[1]: *** [CMakeFiles/open62541-plugins.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
I would surely check out what is `nano.specs`. I figured out its from [_**GNU ARM Embedded Toolcain**_](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa). I didn't need this tool, because my platform is not ARM based, But I'd like to try this out though. As I mentioned above. I installed `gcc-arm-embedded` and checked out this toolchain is installed properly with two command:
```
gfast2@gfast2-VB:~$ which arm-none-eabi-g++
/usr/bin/arm-none-eabi-g++
gfast2@gfast2-VB:~$ which arm-none-eabi-gcc
/usr/bin/arm-none-eabi-gcc
```

And I did found some `nano.specs` in my machine, too:
```
gfast2@gfast2-VB:~$ sudo find / -iname nano.specs
/usr/lib/arm-none-eabi/newlib/thumb/nano.specs
/usr/lib/arm-none-eabi/newlib/thumb/armv7-ar/fpu/vfpv3-d16/be/nano.specs
/usr/lib/arm-none-eabi/newlib/fpu/nano.specs
/usr/lib/arm-none-eabi/newlib/nano.specs
/usr/lib/arm-none-eabi/newlib/armv6-m/nano.specs
/usr/lib/arm-none-eabi/newlib/armv7-m/nano.specs
/usr/lib/arm-none-eabi/newlib/armv7-ar/thumb/fpu/nano.specs
/usr/lib/arm-none-eabi/newlib/armv7-ar/thumb/nano.specs
/usr/lib/arm-none-eabi/newlib/armv7-ar/thumb/softfp/nano.specs
/usr/lib/arm-none-eabi/newlib/armv7e-m/fpu/nano.specs
/usr/lib/arm-none-eabi/newlib/armv7e-m/nano.specs
/usr/lib/arm-none-eabi/newlib/armv7e-m/softfp/nano.specs
/usr/arm-none-eabi/lib/thumb/v7e-m/fpv5/hard/nano.specs
/usr/arm-none-eabi/lib/thumb/v7e-m/fpv5/softfp/nano.specs
/usr/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/nano.specs
/usr/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/softfp/nano.specs
/usr/arm-none-eabi/lib/thumb/v7e-m/nano.specs
/usr/arm-none-eabi/lib/thumb/v7e-m/fpv5-sp/hard/nano.specs
/usr/arm-none-eabi/lib/thumb/v7e-m/fpv5-sp/softfp/nano.specs
/usr/arm-none-eabi/lib/thumb/v7-m/nano.specs
/usr/arm-none-eabi/lib/thumb/v6-m/nano.specs
/usr/arm-none-eabi/lib/thumb/v8-m.base/nano.specs
/usr/arm-none-eabi/lib/thumb/v7-ar/fpv3/hard/nano.specs
/usr/arm-none-eabi/lib/thumb/v7-ar/fpv3/softfp/nano.specs
/usr/arm-none-eabi/lib/thumb/v7-ar/nano.specs
/usr/arm-none-eabi/lib/thumb/nano.specs
/usr/arm-none-eabi/lib/thumb/v8-m.main/fpv5/hard/nano.specs
/usr/arm-none-eabi/lib/thumb/v8-m.main/fpv5/softfp/nano.specs
/usr/arm-none-eabi/lib/thumb/v8-m.main/nano.specs
/usr/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/hard/nano.specs
/usr/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/softfp/nano.specs
/usr/arm-none-eabi/lib/nano.specs
/usr/arm-none-eabi/lib/hard/nano.specs

```
But I still didn't have any chance to get the library compiled. (with the same error). 🦀 

---

I'm using a 64-bit [_**Ubuntu Mate 16.04 LTS**_](https://ubuntu-mate.org/download/) machine in Virtualbox:
```
gfast2@gfast2-VB:~$ uname -a
Linux gfast2-VB 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

---

- What should be the problem? ❔ 📌 💢 
- Is that possible without build _**open62541**_ to implement this library?

**Comment by vatmi** [comment]
@Gfast2, as per my understanding -nano.specs is completely toolchain depended. I am using atollic truestudio and corresponding toolchain for ARM. -nano.specs is used to link the code optimized pre-built C libraries from ARM gcc, which may not be applicable to your platform. If your toolchain is providing some options for code optimization, you may add those. 

So to make the code working for your platform, you may delete this complete line from CMakeLists.txt 
"add_definitions(-mcpu=cortex-m3 -mthumb -g -Wall -O0 -specs=nano.specs -ffunction-sections -fdata-sections  -fno-exceptions -fstack-usage )"

Also please make sure you have all your freertos + lwip related includes placed somewhere. I am using a dump hard coded include options for this as given in the CMakeLists.txt lines 10,11
+include_directories("../freeRTOS_Includes/include")
+include_directories("../freeRTOS_Includes/include/ipv4") 
This directories contain all the includes for lwip, eg:- lwip, arch, ipv4, netif for LwIp and all other includes for freertos and the hardware specific includes.

And as you might have noticed, my hostname is also hard coded now as given in ua_network_tcp.c. You will need to put your IP here, char *hostname = "Your IP"

Hope this helps. Please update your results.

Milan

**Comment by Gfast2** [comment]
Hi @vatmi , Thanks for your explanation! 🥇 
I do understand you've add
`add_definitions(-mcpu=cortex-m3 -mthumb -g -Wall -O0 -specs=nano.specs -ffunction-sections -fdata-sections -fno-exceptions -fstack-usage )`
in **`CMakeLists.txt`** in order to specify the needed compiling parameters. and some hard coded dependencies in the same file firstly.

---

All right. I'll check out your tipps today later.
It's a definitly a enlighting _PR_ for me. I will tell the result.

**Comment by Gfast2** [comment]
Hi @vatmi ,

After such a long time and much effort, I realize what I'm doing is not only change the dependencie to FreeRTOS+LWIP but also _How to use cmake do cross compiling in Terminal._

It's a little bit beyoud my skill range. Through [_**this post**_](http://www.aosabook.org/en/cmake.html) I got the point that **CMake** is heavily based on *gcc* compiler, which in my case the _**xtensa-esp32-elf-gcc**_ . 

It looks like I've to dig deeper.

If I do get something, I'll write here the result. 🌔

**Comment by vatmi** [comment]
Hi @Gfast2, you are right in your case, you might have to specify  xtensa-esp32-elf-gcc as your c compiler and  xtensa-esp32-elf-g++ as c++ compiler in cmake . And one more thing as per the current implementation, open62541 is compiled as a library, which is then linked with the FreeRTOS+LwiP project. 
So in my cmake settings apart from the default settings, I have only UA_ENABLE_AMALGAMATION ticked. Even if you enable UA_BUILD_EXAMPLES this will not be usable. Make of the project creates a freertos( your platform) compatible library libopen62541, which is later used with freertos project for creating application (freertos task). The sample server/client application is created as a freertos task referring to this library.

Hope this helps.

**Comment by jpfr** [comment]
It woul be great if #1160 could be merged.
For that, I propose that your networklayer becomes /plugins/ua_networking_lwip.c.
The changes are big enough to warrant a separate "port" of the networklayer.

**Comment by marcrupprath** [comment]
Question is:
".... with the used LwiP version 1.4.1 most of them are commented out. ...."

As you can see here: https://savannah.nongnu.org/news/?group=lwip
Version 1.4.1 is quite old: latest stable release is: 2.0.3.

I ask the experienced TCP users if the usage of the new release will fix some issues, becaus eit has possibly less limitations ?

If you think that the Lwip Stack is still to limited, have  a look here:
https://www.oryx-embedded.com/cyclone_tcp.html, a free Version is also available

**Comment by Gfast2** [comment]
Hi @marcrupprath ,

I've hear the similar discussion in esp32.com (forum). I believe the [_ESP-IDF_](http://esp-idf.readthedocs.io/en/latest/) is still using the old lwIP. The core developer said, the older one has got all the features that they need. So, what is the point of the new release.

Because I'm still not long in the embedded playground. So I'd like to know your opinion. What have you seen, which feature / features are the _"MUST TO HAVE" from the new release of lwIP. 🤦‍♂️ 

_P.s:
If I can understand your advices, I'll make suggestion there. And try to persuade the guys there working on the new lwIP
_

Cheers

Gfast2

**Comment by marcrupprath** [comment]
Hello Gfast2:
i started the Stack discussionabout the top comment:"
Since most of the deafult socket interfaces were not supported with the used LwiP version 1.4.1 most of them are commented out. "

My questions is: If  you think that the current Version of Lwip is suited enough for the Tasks then all fine
If you are not shure, because of the unsupported interface you have probably think about what is "the right" TCP Stack to use.

My Qhestion is: Are you missing something in the Lwip Stack ?
What are exactly the unsuppoted Network interfaces.

What i will do:
I have become more familiar with TCP Stacks ;-)
I will then make my tests on my one
I will then share my experiences with you at a later stage.

**Comment by marcrupprath** [comment]
Hello,
if you are looking for a good Embedded OPC UA Reference in Hardware and Software i would like to point you to the following:

https://www.infineon.com/cms/de/product/evaluation-boards/kit_xmc48_relax_ecat_v1/
with
OPC UA Example impelemntation;
https://www.infineon.com/cms/en/product/promopages/aim-mc/dave_downloads.html
---> OPCUASERVER_LWIP_XMC47

idea is to replace given Demo lib with open 62541

Hope that helps ;-)

**Comment by Gfast2** [comment]
@marcrupprath 👍 
Wow, you are really a professional! May I ask what kinda of industry you are working on, and how many years you have investigated there?

**Comment by marcrupprath** [comment]
Gesendet: Montag, 15. Januar 2018 um 20:29 Uhr
Von: Su <notifications@github.com>
An: open62541/open62541 <open62541@noreply.github.com>
Cc: marcrupprath <marc.rupprath@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [open62541/open62541] WIP: initial support for freertos (#1160)


@marcrupprath 👍
Wow, you are really a professional! May I ask what kinda of industry you are working on, and how many years you have investigated there?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


 

 

Hello,

i have an diploma in electrical engineering an an have round about of 18 years of  expierence in the automation industrie.

 

I worked for about of 15 yeras in the field of classic "heavy" industry, like steel plants ....

Here i worked minly on SCADA Systems and ws responsible for many kinds of connetion issues.

As ou know classic OPC is very common in zhis field since many years.

 

I now working in the automotive industrie in the field of Testfield / Testsoftware.

I am currently working on some concepts on using OPC UA in this workspace, here it is not as usal as in the "normal" industrie to use OPC.

 

Regards

 

Marc

**Comment by vatmi** [comment]
@marcrupprath, We have finally the full working version of open62541, with our specific hardware set up, (latest master branch merged). One of my colleague @cabralfortiss is making some experiment with newest version of lwip to make the final commit and network layer for lwip.

**Comment by Gfast2** [comment]
@vatmi, Super cool! Congratulations! It looks like that I can somehow do small contribution later freely!

Cheers

Gfast2

**Comment by jpfr** [comment]
We merged FreeRTOS support via #1546.
Please reopen if there are additional features we can take from here.

**Pull request closed without merging**
