### PR TITLE
[Draft] feature(sks): SKS and pubsub integration

### PR DESCRIPTION
**Pull request by hzw53**
Added an implementation of the security key service for the end-to-end
encryption of pubsub communication.

Added SKS implementation under src/pubsub/ua_pubsub_sks.c.
Functions common to sks and publisher / subscribers are implemented in src/pubsub/ua_pubsub_security.c.
Added examples to examples/sks for SKS server, publisher and subscriber
Added unit tests to tests/sks.
Added AES128 and AES256 CTR security policies.

What is supported at the moment:
* All SKS methods
* Publisher and subscriber will connect to the SKS, call GetSecurityKeys
  when necessary and use the returned keys for encryption/decryption
* Publisher and subscriber provide a SetSecurityKeys method. The user
  has to call this method by himself, the SKS won't do this at the moment
* Encryption and decryption are not supported for json

### CODE REVIEW

**Comment by jpfr** [comment]
Very good to see this finally happen! Very nice.

I would have one if our security experts have a quick look.
Then let's have a quick call to discuss merge strategies.
A 6k line PR is of course challenging to pull in at once.

Do you want to add your (organization) names to the code headers?

**Comment by hzw53** [comment]
This sound like a good plan.

**Comment by Dc-H** [comment]
@jpfr @hzw53  Thank you all for doing this. I want to confirm that SKS has not been merged into Branch:master now? because I didn't see the src/pubsub/ua_pubsub_sks.c. or src/pubsub/ua_pubsub_security.c in the GitHub. This is an upcoming feature, right?
By the way, can certificate and private key ( server_encryption.c) be used as one method to limit the subscribers for UDP-based Pub/Sub?
Thanks.

**Comment by Waner98** [comment]
Hi, do you know if an equivalent to this topic was added to the master branch ? More exactly, can we now use certificates and keys to protect PubSub UDP multicast and with which elements ? 

Thanks!

**Comment by jpfr** [comment]
A first batch from this PR was merged via #4256.

**Comment by Muddasir-Shakil** [comment]
Hi,
I tested the functionalities of this PR, it looks promising. It is somewhat behind to the master, so it needs to be updated. I wanted to ask that if someone is already working on integrating this PR into master. Since it is quite a big PR to be merged it makes sense to break it down into smaller chunks like I have seen with #4256, which adds Encryption and Decryption functionalities. I think next step can be SKS methods, Publisher/Subscribe API and config parameters to connect with SKS, Support for Key Push and Pull, adding documentation on API and tutorial, and so on. I can start working on it, but first I wanted to know what are the current plans regarding SKS integration.

**Comment by jpfr** [comment]
@Muddasir-Shakil please check with @hzw53, the author of this PR.
@ChHaa, any near-term plans to work on this?

**Comment by Muddasir-Shakil** [comment]
@hzw53 Thank you on started the work on SKS. I wanted to ask you what are your plans regarding this Pull request. What are the next step so that it can be integrated. I will be happy to help to bring SKS into upstream branch.

**Comment by jpfr** [comment]
The feature was integrated via #5243.

**Pull request closed without merging**
