### PR TITLE
Fix interpreter locations

### PR DESCRIPTION
**Pull request by ctron**
This changes fixes the interpreter locations for a set of Python files.

### CODE REVIEW

**Comment by Pro** [comment]
Thanks for the PR!
Note that most of the files in ` tools/pyUANamespace` will be overwritten/replaced by the refactoring PR #739. Thus we also need to integrate/change this in that PR branch.

I would change it to a more general shebang line, like:
`#!/usr/bin/env python` (note the difference, there's no slash after `env`). Does this also work for you @ctron?

IMHO your proposed shebang line will only work if python is in `/usr/bin/python`?

See also the discussion here:
https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take
and 
https://stackoverflow.com/a/2429517/869402

**Comment by jpfr** [comment]
So `#!/usr/bin/env python`?

**Comment by jpfr** [comment]
Imho this can be merged ahead of #739.

**Comment by Pro** [comment]
Yes, I think `#!/usr/bin/env python` is the more general way.

Merging it before #739 is also ok. But still we need to port the correct shebangs to #739

**Comment by ctron** [comment]
I will give it a test with `#!/usr/bin/env python`

**Comment by ctron** [comment]
Yes, that works. I did update the PR.

**Comment by jpfr** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
