### PR TITLE
Core: More intuitive node id ordering

### LINKED ISSUE #2898: UA_NodeId_order incorrectly compare UA_NodeId
## Description
UA_NodeId_order incorrectly compare UA_NodeIds when UA_NodeId.identifierType equal UA_NODEIDTYPE_GUID.
## Background Information / Reproduction Steps
**current code: ua_types.c line 311**
case UA_NODEIDTYPE_GUID:
&nbsp;&nbsp;&nbsp;&nbsp;if(n1->identifier.guid.data1 < n2->identifier.guid.data1 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data2 < n2->identifier.guid.data2 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data3 < n2->identifier.guid.data3 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;strncmp((const char*)n1->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n2->identifier.guid.data4, 8) < 0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;if(n1->identifier.guid.data1 > n2->identifier.guid.data1 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data2 > n2->identifier.guid.data2 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data3 > n2->identifier.guid.data3 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;strncmp((const char*)n1->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n2->identifier.guid.data4, 8) > 0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;break;

**fixed code:**
case UA_NODEIDTYPE_GUID: {
&nbsp;&nbsp;&nbsp;&nbsp;if(n1->identifier.guid.data1 < n2->identifier.guid.data1) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data1 > n2->identifier.guid.data1) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data2 < n2->identifier.guid.data2) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data2 > n2->identifier.guid.data2) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data3 < n2->identifier.guid.data3) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data3 > n2->identifier.guid.data3) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const int cmp = strncmp(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n1->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n2->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(cmp < 0) return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(cmp > 0) return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;break;
}

### PR DESCRIPTION
**Pull request by melkorb**
Fix function UA_NodeId_order when compare UA_NodeId with identifierType equal UA_NODEIDTYPE_GUID

Fixes #2898

### CODE REVIEW

**Comment by Pro** [comment]
Thank you for the pull request!

Do you have any example GUIDs where the comparison failed?

I would like to add a unit test before we merge this to avoid future regression.

**Comment by melkorb** [comment]
For tests you must use 4 pairs of GUIDs. At begining compare elements of pair, then swap it and compare again. First result must be UA_ORDER_LESS, second UA_ORDER_MORE.

1. 00000000-FFFF-FFFF-FFFF-FFFFFFFFFFFF,  00000001-0000-0000-0000-000000000000
2. 00000000-0000-FFFF-FFFF-FFFFFFFFFFFF, 00000000-0001-0000-0000-000000000000
3. 00000000-0000-0000-FFFF-FFFFFFFFFFFF, 00000000-0000-0001-0000-000000000000
4. 00000000-0000-0000-0000-000000000000, 00000000-0000-0000-0000-000000000001

**Comment by jpfr** [comment]
Thanks for uncovering this!!
I don't fully agree with the changes for ByteString.

Let me come back to you after some testing.

Very good to see unit tests. 👍

**Comment by jpfr** [comment]
The ordering-code was already "correct" before this patch.
It established an absolute ordering of the NodeIds.
But the order was not always very intuitive for guids.

This patch improves the "inuitiveness" of the ordering. So good to go. 👍 

Can you adjust all of the commit messages to something useful?
Or squash the commits into one...

**Comment by Pro** [comment]
> Can you adjust all of the commit messages to something useful?
> Or squash the commits into one...

Done. Can be merged when green

**Pull request merged**
