### PR TITLE
Add -Wshadow -Wconversion compiler flags

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by Stasik0** [comment]
Does it kill backward-compatibility?

**Comment by Stasik0** [comment]
@jpfr so how is the status? )

**Comment by jpfr** [comment]
The code is good.
But travis bugs me. A lot.

**Comment by jpfr** [comment]
This PR was squashed and merged in 2ae7fef1e4ae33e94a95c6f7b653655c6ff0d328.

**Pull request closed without merging**
