### PR TITLE
fix(nc) missing executeable flag on tools/generate_nodeid_header.py

### PR DESCRIPTION
**Pull request by gusentom**
without executeable flag generate_nodeid_header fails with permission denied on Linux

### CODE REVIEW

**Comment by andreasebner** [comment]
Thank's for your contribution. In order to merge your change, it's neccessary that you sign the CLA.

**Comment by gusentom** [comment]
> Thank's for your contribution. In order to merge your change, it's neccessary that you sign the CLA.
CLA is signed yet

**Comment by andreasebner** [comment]
Currently the CLA seems still not signed. Please check the following: 

"Thomas Gusenleitner seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)."
--> Maybe your GitHub mail =! the email used in your Git-Config

**Comment by gusentom** [comment]
> Currently the CLA seems still not signed. Please check the following:
> 
> "Thomas Gusenleitner seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)." --> Maybe your GitHub mail =! the email used in your Git-Config


email is public now

**Comment by andreasebner** [comment]
> > Currently the CLA seems still not signed. Please check the following:
> > "Thomas Gusenleitner seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)." --> Maybe your GitHub mail =! the email used in your Git-Config
> 
> email is public now

Something still seems to be wrong. I start a re-check and your Email (configured localy in your github) is not used for Github / or linked in GitHub.

**Comment by mojca** [comment]
@andreasebner or anyone else: can you please backport this commit to the 1.3 branch?

**Pull request merged**
