### PR TITLE
feat(core): More logging when setting up the SecureChannel fails

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by shirenfeng** [comment]
I add trace as bellow:
retval = securityPolicy->channelModule.newContext(securityPolicy, remoteCertificate, &channel->channelContext);
    if(retval != UA_STATUSCODE_GOOD){
			UA_LOG_ERROR(securityPolicy->logger, UA_LOGCATEGORY_SECURITYPOLICY,"SRF newContext FAIL");
            return retval;
        }


got log:
 pk_parse_key_pkcs8_unencrypted_der 11 ret=0

 mbedtls_pk_parse_key 11 ret=0
[2019-10-25 10:38:56.550 (UTC+0800)] info/userland      UA_ClientConfig 3
[2019-10-25 10:38:56.550 (UTC+0800)] info/client        Connecting to endpoint opc.tcp://localhost:4840
[2019-10-25 10:38:56.550 (UTC+0800)] error/securitypolicy       SRF newContext FAIL
[2019-10-25 10:38:56.551 (UTC+0800)] error/client       Failed to set the security policy
[2019-10-25 10:38:56.551 (UTC+0800)] error/client       Couldn't connect the client to a TCP secure channel

**Comment by shirenfeng** [comment]
code:
static UA_StatusCode
parseRemoteCertificate_sp_basic256sha256(Basic256Sha256_ChannelContext *cc,
                                         const UA_ByteString *remoteCertificate) {
    if(remoteCertificate == NULL || cc == NULL)
        return UA_STATUSCODE_BADINTERNALERROR;

    /* Parse the certificate */
    int mbedErr = mbedtls_x509_crt_parse(&cc->remoteCertificate, remoteCertificate->data,
                                         remoteCertificate->length);
    if(mbedErr){
		UA_LOG_ERROR(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, "call mbedtls_x509_crt_parse fail return UA_STATUSCODE_BADSECURITYCHECKSFAILED in parseRemoteCertificate_sp_basic256sha256 retval=0x%x",mbedErr);
        
        return UA_STATUSCODE_BADSECURITYCHECKSFAILED;
    }

    /* Check the key length */
    mbedtls_rsa_context *rsaContext = mbedtls_pk_rsa(cc->remoteCertificate.pk);
    if(rsaContext->len < UA_SECURITYPOLICY_BASIC256SHA256_MINASYMKEYLENGTH ||
       rsaContext->len > UA_SECURITYPOLICY_BASIC256SHA256_MAXASYMKEYLENGTH)
        return UA_STATUSCODE_BADCERTIFICATEUSENOTALLOWED;

    return UA_STATUSCODE_GOOD;
}

log:

pk_parse_key_pkcs8_unencrypted_der 11 ret=0

 mbedtls_pk_parse_key 11 ret=0
[2019-10-25 10:51:10.116 (UTC+0800)] info/userland      UA_ClientConfig 3
[2019-10-25 10:51:10.116 (UTC+0800)] info/client        Connecting to endpoint opc.tcp://localhost:4840
[2019-10-25 10:51:10.117 (UTC+0800)] error/userland     call mbedtls_x509_crt_parse fail return UA_STATUSCODE_BADSECURITYCHECKSFAILED in parseRemoteCertificate_sp_basic256sha256 retval=0xffffd800
[2019-10-25 10:51:10.117 (UTC+0800)] error/userland     call parseRemoteCertificate_sp_basic256sha256 fail in channelContext_newContext_sp_basic256sha256 retval=0x80130000
[2019-10-25 10:51:10.117 (UTC+0800)] error/securitypolicy       SRF newContext FAIL
[2019-10-25 10:51:10.117 (UTC+0800)] error/client       Failed to set the security policy
[2019-10-25 10:51:10.117 (UTC+0800)] error/client       Couldn't connect the client to a TCP secure channel

**Comment by shirenfeng** [comment]
server certs:
[http://118.89.56.251/certs/server/private/jmApp.pem](server's private pem key)
[http://118.89.56.251/certs/server/serverCertFile.der](server's public key)

**Comment by shirenfeng** [comment]
client certs:
[http://118.89.56.251/certs/client/private/jmApp.pem](client's private pem key)
[http://118.89.56.251/certs/client/clientCertFile.der](client's public key)

**Comment by shirenfeng** [comment]
error come from function: mbedtls_x509_crt_parse(), maybe my certificates  have some problems , please try to  run your open62541-project with my certificates , thanks!

**Comment by jpfr** [comment]
pfx does not look like the correct format for the private key.
You can use the tool in /tools/certs/create_certificate.py to generate a self-signed certificate for testing.

**Comment by shirenfeng** [comment]
Thank you very much ! 

I used create_certificate.py to generate a self-signed certificate and to test:

but the client got the same errors.

### SERVER LOG:
# ./ua_server ../certs/my/server_cert.der ../certs/my/server_key.der

[2019-10-28 09:44:34.524 (UTC+0800)] warn/userland      No CA trust-list provided. Any remote certificate will be accepted.

 mbedtls_pk_parse_key 1

 mbedtls_pk_parse_key 2

 mbedtls_pk_parse_key 3

 mbedtls_pk_parse_key 5

 mbedtls_pk_parse_key 6

 mbedtls_pk_parse_key 9 ret=-4224

 mbedtls_pk_parse_key 10 ret=-4224

 mbedtls_pk_parse_key 12 ret=-4224

 mbedtls_pk_parse_key 13 ret=-4224

 mbedtls_pk_parse_key 15 ret=-4224

 mbedtls_pk_parse_key 16 ret=-15360

 pk_parse_key_pkcs8_unencrypted_der 4 ret=-15074

 mbedtls_pk_parse_key 1

 mbedtls_pk_parse_key 2

 mbedtls_pk_parse_key 3

 mbedtls_pk_parse_key 5

 mbedtls_pk_parse_key 6

 mbedtls_pk_parse_key 9 ret=-4224

 mbedtls_pk_parse_key 10 ret=-4224

 mbedtls_pk_parse_key 12 ret=-4224

 mbedtls_pk_parse_key 13 ret=-4224

 mbedtls_pk_parse_key 15 ret=-4224

 mbedtls_pk_parse_key 16 ret=-15360

 pk_parse_key_pkcs8_unencrypted_der 4 ret=-15074

 mbedtls_pk_parse_key 1

 mbedtls_pk_parse_key 2

 mbedtls_pk_parse_key 3

 mbedtls_pk_parse_key 5

 mbedtls_pk_parse_key 6

 mbedtls_pk_parse_key 9 ret=-4224

 mbedtls_pk_parse_key 10 ret=-4224

 mbedtls_pk_parse_key 12 ret=-4224

 mbedtls_pk_parse_key 13 ret=-4224

 mbedtls_pk_parse_key 15 ret=-4224

 mbedtls_pk_parse_key 16 ret=-15360

 pk_parse_key_pkcs8_unencrypted_der 4 ret=-15074
[2019-10-28 09:44:34.536 (UTC+0800)] info/server        server->config.applicationDescription.applicationUri urn:open62541.server.application
[2019-10-28 09:44:34.536 (UTC+0800)] info/server        server->config.applicationDescription.applicationUri urn:open62541.server.application
[2019-10-28 09:44:34.536 (UTC+0800)] info/server        server->config.applicationDescription.applicationUri urn:open62541.server.application
[2019-10-28 09:44:34.537 (UTC+0800)] info/network       TCP network layer listening on opc.tcp://ubuntu:4840/








### CLIENT LOG:
# ./ua_client opc.tcp://localhost:4840 ../certs/my/server_cert.der ../certs/my/server_key.der  3 http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
[2019-10-28 09:49:30.677 (UTC+0800)] info/client        SecurityPolicy not specified -> use default #None
[2019-10-28 09:49:30.678 (UTC+0800)] warn/securitypolicy        Security policy None is used to create SecureChannel. Accepting all certificates
[2019-10-28 09:49:30.680 (UTC+0800)] info/client        TCP connection established
[2019-10-28 09:49:30.682 (UTC+0800)] info/client        Opened SecureChannel with SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None
[2019-10-28 09:49:30.684 (UTC+0800)] info/userland      UA_Client_getEndpoints : i=0,endpointUrl:opc.tcp://localhost:48401,mode:1,policyUri:http://opcfoundation.org/UA/SecurityPolicy#None
[2019-10-28 09:49:30.685 (UTC+0800)] info/userland      UA_Client_getEndpoints : i=1,endpointUrl:opc.tcp://localhost:48401,mode:2,policyUri:http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15▒
[2019-10-28 09:49:30.686 (UTC+0800)] info/userland      UA_Client_getEndpoints : i=2,endpointUrl:opc.tcp://localhost:48401,mode:3,policyUri:http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15▒
[2019-10-28 09:49:30.687 (UTC+0800)] info/userland      UA_Client_getEndpoints : i=3,endpointUrl:opc.tcp://localhost:48401,mode:2,policyUri:http://opcfoundation.org/UA/SecurityPolicy#Basic256
[2019-10-28 09:49:30.687 (UTC+0800)] info/userland      UA_Client_getEndpoints : i=4,endpointUrl:opc.tcp://localhost:48401,mode:3,policyUri:http://opcfoundation.org/UA/SecurityPolicy#Basic256
[2019-10-28 09:49:30.687 (UTC+0800)] info/userland      UA_Client_getEndpoints : i=5,endpointUrl:opc.tcp://localhost:48401,mode:2,policyUri:http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
[2019-10-28 09:49:30.687 (UTC+0800)] info/userland      UA_Client_getEndpoints : i=6,endpointUrl:opc.tcp://localhost:48401,mode:3,policyUri:http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
[2019-10-28 09:49:30.687 (UTC+0800)] info/userland      UA_ClientConfig 1
[2019-10-28 09:49:30.687 (UTC+0800)] info/userland      UA_ClientConfig 2

 mbedtls_pk_parse_key 1

 mbedtls_pk_parse_key 2

 mbedtls_pk_parse_key 3

 mbedtls_pk_parse_key 5

 mbedtls_pk_parse_key 6

 mbedtls_pk_parse_key 9 ret=-4224

 mbedtls_pk_parse_key 10 ret=-4224

 mbedtls_pk_parse_key 12 ret=-4224

 mbedtls_pk_parse_key 13 ret=-4224

 mbedtls_pk_parse_key 15 ret=-4224

 mbedtls_pk_parse_key 16 ret=-15360

 pk_parse_key_pkcs8_unencrypted_der 4 ret=-15074

 mbedtls_pk_parse_key 1

 mbedtls_pk_parse_key 2

 mbedtls_pk_parse_key 3

 mbedtls_pk_parse_key 5

 mbedtls_pk_parse_key 6

 mbedtls_pk_parse_key 9 ret=-4224

 mbedtls_pk_parse_key 10 ret=-4224

 mbedtls_pk_parse_key 12 ret=-4224

 mbedtls_pk_parse_key 13 ret=-4224

 mbedtls_pk_parse_key 15 ret=-4224

 mbedtls_pk_parse_key 16 ret=-15360

 pk_parse_key_pkcs8_unencrypted_der 4 ret=-15074

 mbedtls_pk_parse_key 1

 mbedtls_pk_parse_key 2

 mbedtls_pk_parse_key 3

 mbedtls_pk_parse_key 5

 mbedtls_pk_parse_key 6

 mbedtls_pk_parse_key 9 ret=-4224

 mbedtls_pk_parse_key 10 ret=-4224

 mbedtls_pk_parse_key 12 ret=-4224

 mbedtls_pk_parse_key 13 ret=-4224

 mbedtls_pk_parse_key 15 ret=-4224

 mbedtls_pk_parse_key 16 ret=-15360

 pk_parse_key_pkcs8_unencrypted_der 4 ret=-15074
[2019-10-28 09:49:30.711 (UTC+0800)] info/userland      UA_ClientConfig 3
[2019-10-28 09:49:30.711 (UTC+0800)] info/client        Connecting to endpoint opc.tcp://localhost:4840
[2019-10-28 09:49:30.712 (UTC+0800)] warn/client        The configured ApplicationURI does not match the URI specified in the certificate for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
[2019-10-28 09:49:30.712 (UTC+0800)] warn/client        The configured ApplicationURI does not match the URI specified in the certificate for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Basic256
[2019-10-28 09:49:30.712 (UTC+0800)] warn/client        The configured ApplicationURI does not match the URI specified in the certificate for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
[2019-10-28 09:49:30.713 (UTC+0800)] error/userland     call mbedtls_x509_crt_parse fail return UA_STATUSCODE_BADSECURITYCHECKSFAILED in parseRemoteCertificate_sp_basic256sha256 retval=0xffffd800
[2019-10-28 09:49:30.713 (UTC+0800)] error/userland     call parseRemoteCertificate_sp_basic256sha256 fail in channelContext_newContext_sp_basic256sha256 retval=0x80130000
[2019-10-28 09:49:30.713 (UTC+0800)] error/securitypolicy       SRF newContext FAIL
[2019-10-28 09:49:30.713 (UTC+0800)] error/client       Failed to set the security policy
[2019-10-28 09:49:30.713 (UTC+0800)] error/client       Couldn't connect the client to a TCP secure channel
root@ubuntu:/home/huiwei/pc/client#

**Comment by shirenfeng** [comment]
my certs:
[server_cert.der](http://118.89.56.251/certs/my/server_cert.der)
[server_key.der](http://118.89.56.251/certs/my/server_key.der)

**Comment by shirenfeng** [comment]
@jpfr

**Comment by shirenfeng** [comment]
which version of mbedtls that you used?

**Comment by jpfr** [comment]
I use the mbedtls that comes with Debian 10.

> [2019-10-28 09:49:30.713 (UTC+0800)] error/userland call mbedtls_x509_crt_parse fail return UA_STATUSCODE_BADSECURITYCHECKSFAILED in parseRemoteCertificate_sp_basic256sha256 retval=0xffffd800

Hmm. It looks as if the certificate was corrupted and cannot be read.
Are you on a Linux?

**Comment by shirenfeng** [comment]
yes,my OS is ubuntu16.04

**Comment by shirenfeng** [comment]
could you give me a certificate  that can be read and correct?

**Pull request merged**
