### PR TITLE
Fix duplicate value 0 in union switch field enums

### PR DESCRIPTION
**Pull request by basyskom-jvoe**

### CODE REVIEW

**Comment by jpfr** [comment]
Looks good!
Can you rebase for the 1.2 branch and add the fix(nc) prefix?

**Comment by basyskom-jvoe** [comment]
> Looks good!
> Can you rebase for the 1.2 branch and add the fix(nc) prefix?

Done

**Comment by jpfr** [comment]
Thanks!

**Comment by basyskom-jvoe** [comment]
> Thanks!

Thanks for the merge!

**Pull request merged**
