### PR TITLE
[REVIEW] feat(ci): automatic gitsubmodule updates

### PR DESCRIPTION
**Pull request by GoetzGoerisch**
Following my and other recent updates to the OPC UA NodeSets. #4213 #4144 #3967 

I propose an semi-automatic update of the corresponding gitsubmodules.

### CODE REVIEW

**Comment by jpfr** [comment]
Some of these recent updates were problematic.
We had to adjust some of our generation scripts.

More such problematic changes have to anticipated. For example, the .bsd format for datatypes is now deprecated.

Let's not automatic this. The effort to do a PR is small.
And we see the build result before pressing the merge button.

**Comment by GoetzGoerisch** [comment]
@jpfr I understand this explanation.

The PR is generated automatically, but not merged.

Therefore, one sees the build results and if a problematic change happens it results in a failing PR run. 😄

**Comment by jpfr** [comment]
> The PR is generated automatically, but not merged.

In that case, yes please!

**Comment by GoetzGoerisch** [comment]
I assume, the docker cloud failing build is unrelated to this change, but I have no access to asses this, as the "Details" gives me a 404.

**Comment by GoetzGoerisch** [comment]
For our project we are working with this method.
See https://github.com/umati/Sample-Server/pull/108 as an example.

**Comment by jpfr** [comment]
Nice 👍 
Merged.

**Pull request merged**
