### PR TITLE
Correct boolean check on input parameters

### PR DESCRIPTION
**Pull request by tjuerges**
Currently the input parameter checks in addPubSubConnection are concatenated with boolean AND.  From the code that follows after the checks I take it that the checks should rather be concatenated with boolean OR so that any failed check will force a return.

### CODE REVIEW

**Comment by jpfr** [comment]
Good find!
Can you sign the CLA in the PR checks? Then we can merge.

**Comment by tjuerges** [comment]
It says that I have signed it:  
> You have signed the CLA for open62541/open62541
Not sure what's now wrong.

**Comment by jpfr** [comment]
Is the email given in the author name of the commit linked to your Github profile?

**Comment by tjuerges** [comment]
:man_facepalming:  Obviously I did this during work time and my work address was not registered.  - Just did that.

I guess I'll need to file a new merge request then?

**Comment by Pro** [comment]
>  Obviously I did this during work time and my work address was not registered. - Just did that.
> Then I revoked CLA access and resigned the CLA again. Let's see how this goes now.

You can also amend the author of the commit and then force push to you branch.
That will automatically update this PR

**Comment by tjuerges** [comment]
> You can also amend the author of the commit and then force push to you branch.
> That will automatically update this PR

> commit 1398d6267a144bcaa75b4076354836228f674a3c (HEAD -> fix_input_parameter_check, origin/fix_input_parameter_check)
Author: Thomas Jürges <jurges@astron.nl>
Date:   2019-07-29 15:10:33 +0200

    Correct boolean check on input parameters

The commit already contains the correct e-mail address.  It is the CLA system that apparently does not get it although I signed the LA again after I have added my work address to github.

**Comment by tjuerges** [comment]
Obviously there is something broken in the CLA system.  The license stuff is already taking much more time than it took me to find the bug in the source code.  If you want to merge the bug fix, fine.  If you don't, also fine with me.  But I won't waste more time on this bunch of license baloney.

**Comment by Pro** [comment]
I just did a rebase and force push. That re-triggers the CLA. It's green now. 
After the other CI run through, we can merge.

Thanks @tjuerges

**Pull request merged**
