### PR TITLE
stop setting UA_SUBSCRIPTIONSTATE_LATE at the end of monitoredItem list

### PR DESCRIPTION
**Pull request by StalderT**

### CODE REVIEW

**Comment by StalderT** [comment]
If I use [client.txt](https://github.com/open62541/open62541/files/1460835/client.txt) and [server.txt](https://github.com/open62541/open62541/files/1460836/server.txt)

I have this issue (client log) : 

```
test has changed 10000 130000!
test has changed 9000 131001!
test has changed 8000 132001!
test has changed 7000 133001!
test has changed 6000 134001!
test has changed 5000 135001!
test has changed 4000 136001!
test has changed 3000 137001!
test has changed 2000 138001!
test has changed 1 140000!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131547826199912710 after 131547826243910270 diff 43997560
test has changed 10000 130001!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131547826243912170 after 131547826280131700 diff 36219530
test has changed 10000 150000!
test has changed 9000 151001!
test has changed 8000 152001!
test has changed 7000 153001!
test has changed 6000 154001!
test has changed 5000 155001!
test has changed 4000 156001!
test has changed 3000 157001!
test has changed 2000 158001!
test has changed 1 160000!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131547826280137930 after 131547826324074900 diff 43936970
test has changed 10000 150001!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131547826324076710 after 131547826360012530 diff 35935820
test has changed 10000 170000!
test has changed 9000 171001!
test has changed 8000 172001!
test has changed 7000 173001!
test has changed 6000 174001!
test has changed 5000 175001!
test has changed 4000 176001!
test has changed 3000 177001!
test has changed 2000 178001!
test has changed 1 180000!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131547826360012730 after 131547826403990840 diff 43978110
```

One time ```UA_Client_Subscriptions_manuallySendPublishRequest``` works, the second time, only some Items are sent (only one PublishResponse). After one works, one failed .....

bug1

wireshark capture [bug1.zip](https://github.com/open62541/open62541/files/1460846/bug1.zip)

Seem to work on UaExpert, all the monitedItems are refreshed every 4 seconds. But I think there is still a problem sometime we have two consecutive PublishResponse
uaexpert

wireshark : [uaexpert.zip](https://github.com/open62541/open62541/files/1460892/uaexpert.zip)

I search, but can't found solution. Can you help me?

Thanks in advance

**Comment by StalderT** [comment]
I finally found !

It's because ```UA_Client_Subscriptions_addMonitoredItem``` set ```samplingInterval``` with ```sub->publishingInterval``` value.

here https://github.com/open62541/open62541/blob/5c73d380c419dfc60ce69006459fb85a596dd0d1/src/client/ua_client_highlevel_subscriptions.c#L225 and here https://github.com/open62541/open62541/blob/5c73d380c419dfc60ce69006459fb85a596dd0d1/src/client/ua_client_highlevel_subscriptions.c#L251

And indeed we do not have all the values at this moment. The behavior is normal. That's why it worked with UaExpert.

With this test commit https://github.com/StalderT/open62541/commit/02302d84ddea49a21e95f8818b33f05d3529e953 no more issue : 

```
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131548098688562830 after 131548098726008830 diff 37446000
test has changed 10000 2970002!
test has changed 9000 2989000!
test has changed 8000 2988000!
test has changed 7000 2987000!
test has changed 6000 2986000!
test has changed 5000 2985000!
test has changed 4000 2984000!
test has changed 3000 2983000!
test has changed 2000 2982000!
test has changed 1 2980001!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131548098726011410 after 131548098762552290 diff 36540880
test has changed 10000 2990002!
test has changed 9000 3009000!
test has changed 8000 3008000!
test has changed 7000 3007000!
test has changed 6000 3006000!
test has changed 5000 3005000!
test has changed 4000 3004000!
test has changed 3000 3003000!
test has changed 2000 3002000!
test has changed 1 3000001!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131548098762554940 after 131548098802512410 diff 39957470
test has changed 10000 3010002!
test has changed 9000 3029000!
test has changed 8000 3028000!
test has changed 7000 3027000!
test has changed 6000 3026000!
test has changed 5000 3025000!
test has changed 4000 3024000!
test has changed 3000 3023000!
test has changed 2000 3022000!
test has changed 1 3020001!
UA_Client_Subscriptions_manuallySendPublishRequest retval 0 0 before 131548098802525360 after 131548098842779570 diff 40254210
test has changed 10000 3030002!
test has changed 9000 3031002!
test has changed 8000 3048000!
test has changed 7000 3047000!
test has changed 6000 3046000!
test has changed 5000 3045000!
test has changed 4000 3044000!
test has changed 3000 3043000!
test has changed 2000 3042000!
test has changed 1 3040001!
```

I don't know if putting ```sub->publishingInterval``` in ```samplingInterval ``` is a good idea. Can we add a parameter to UA_Client_Subscriptions_addMonitoredItem to specify samplingInterval?

**Comment by StalderT** [comment]
@jpfr
 
------

do we really need the 'l' variable here ? :
https://github.com/StalderT/open62541/blob/9bb23a9d3839289104b5c5173c7d014c9c98f27b/src/server/ua_subscription.c#L213-L214

------

Have you a good suggestion for naming this function ?  

https://github.com/StalderT/open62541/blob/9bb23a9d3839289104b5c5173c7d014c9c98f27b/src/server/ua_subscription.c#L79

------

Can we put :
https://github.com/StalderT/open62541/blob/1d47ccece4f505fb508ea2fd43c34ce379576616/src/server/ua_subscription.c#L245-L267

before

https://github.com/StalderT/open62541/blob/1d47ccece4f505fb508ea2fd43c34ce379576616/src/server/ua_subscription.c#L225 ?

In order to no browse the list here https://github.com/StalderT/open62541/blob/1d47ccece4f505fb508ea2fd43c34ce379576616/src/server/ua_subscription.c#L228 if we have none PublishResponseEntry

**Comment by StalderT** [comment]
@jpfr can we remove Keepalive test?

**Comment by jpfr** [comment]
@StalderT Why should we remove the KeepAlive test?

**Comment by StalderT** [comment]
Because we need an UA_PublishResponseEntry to test the KeepAlive. If I good understand, actual test don't make a PublishRequest.

**Comment by jpfr** [comment]
> do we really need the 'l' variable here ? :
https://github.com/StalderT/open62541/blob/9bb23a9d3839289104b5c5173c7d014c9c98f27b/src/server/ua_subscription.c#L213-L214

In the current master branch we need the `l` variable!
The variable `notifications` contains the number of notifications we can send right now.
The variable `l` contains the number of notifications we have already moved to the message.
We need `l` to know whether to restart at the beginning (if we started at a monitoreditem in the middle). And to know where we are in the response array.
https://github.com/open62541/open62541/blob/7a4996743a6d2f01ef5a61a853118a5e84b7b9bf/src/server/ua_subscription.c#L217

How does you code accomplish the "restart"?

**Comment by jpfr** [comment]
> Because we need an UA_PublishResponseEntry to test the KeepAlive. If I good understand, actual test don't make a PublishRequest.

Feel free to propose a better test foe the KeepAlive. Can we do that in a separate PR?

**Comment by StalderT** [comment]
I arrive at the limit of my current knowledge. I will try to learn :-) I think KeepAlive must be tested in the client part? What do you think?

Yes, separate PR

**Comment by StalderT** [comment]
```How does your code accomplish the "restart"?``` If we are a the end of the list we have finish. If we restart we can resend, in the same PublishIntreval, a already sent monitoredItem.

The restart is made in the next call of UA_Subscription_publishCallback, made by a repeated callback who integrates PublishInterval. When this call is made, UA_Subscription_publishCallback send all monitoredItem present as this moment (with UA_SUBSCRIPTIONSTATE_LATE mechanism).

**Comment by StalderT** [comment]
ok for merging ?

**Comment by jpfr** [comment]
I'm on it.

**Comment by StalderT** [comment]
@Pro Do you know why we have this error : https://travis-ci.org/open62541/open62541/jobs/310564290#L2170 ?

**Comment by StalderT** [comment]
some news?

**Comment by StalderT** [comment]
Can we merge? Do you want changes or explanations?

**Comment by StalderT** [comment]
@jpfr Really sorry to insist, but this problem is blocking for me (causes poor performances) can we try to solve it? Thank you in advance.

Steps to reproduce the problem: use https://github.com/open62541/open62541/files/1460836/server.txt

Monitor 10'000 items with UaExpert

with these parameters

image
and
image

Datas permanently changes (not every 4 seconds).

**Comment by jpfr** [comment]
Hello @StalderT ,

sorry my reaction time is not good atm. Deadlines ahead.
I have this on my TODO as soon as I get the head above the waterline again.

You closed the issue?

**Comment by StalderT** [comment]
> You closed the issue?

No, just the PR in favor of #1555

**Pull request closed without merging**
