### PR TITLE
feat(server): bind fallback to unspecified address

### PR DESCRIPTION
**Pull request by bluhm**
In a Docker container the local address is usually not the gobal
address in DNS.  So binding to the published address will fail.  As
a fallback bind to any address but with the given port.

### CODE REVIEW

**Comment by ccvca** [comment]
I've just check it and this PR fixes my Docker/NAT setup.

**Comment by jpfr** [comment]
Nice!
Can we add some warning-level logging?
The bound address is important from a security perspective.

**Comment by bluhm** [comment]
> Can we add some warning-level logging?
I used an info log, warning is logged if socket cannot be used at all.  Also make sure that either an info or a warning is logged.

**Comment by jpfr** [comment]
Cool!

**Pull request merged**
