### PR TITLE
Evaluate whereClaus of event subscriptions for operator OfType

### LINKED ISSUE #3102: Unexpected EventType in ModelChangeEvent
I have a fairly recent version of open62541 (two weeks or so) built with 
cmake -DUA_ENABLE_SUBSCRIPTIONS_EVENTS=ON . on Linux (Debian)

After that, I took tutorial_server_events.c from the examples directory and built it.

It runs without any problem, but UaExpert complains at every event: "Unexpected EventType in ModelChangeEvent", and no events are shown in the event window.

### PR DESCRIPTION
**Pull request by ccvca**
This is a minimalistic implementation of the WhereClause for EventSubscriptions.

Fixes #3102

Limitations: Only UA_FILTEROPERATOR_OFTYPE is evaluted.

### CODE REVIEW

**Comment by ccvca** [comment]
How to rerun the CI? Travis failed to fetch some archives...

**Comment by jpfr** [comment]
Looks good!
Is it possible to have a unit test for the feature?

**Comment by ccvca** [comment]
Are there any tricks to call static functions from the tests? Or do I need to add the tested functions to the internal headers?

**Comment by jpfr** [comment]
> Or do I need to add the tested functions to the internal headers?

Yes. You need to do that.

**Comment by ccvca** [comment]
Unit test is added, tesing the function directly.
As I'm not able to run the test local at the moment (Mutex Error), I'll need to wait for travis.

**Comment by jpfr** [comment]
Nice! Merged.

**Pull request merged**
