### PR TITLE
Subscription callback: using MonitoredItemId instead of ClientHandle

### PR DESCRIPTION
**Pull request by Aleskey78**
E.g. MonitoredItemId can be used for node name lookup in a callback function.
UA_Client_Subscriptions_addMonitoredItem returns indeed a "UA_UInt32 *newMonitoredItemId", not a ClientHandle.

### CODE REVIEW

**Comment by ichrispa** [comment]
I used the clientSide handle in these function because... well... it's the client side and it has a handle. If it proves more advantageous to completely hide the handle and only work with the serverside monitoredItemId, I have nothing against that.

**Comment by Aleskey78** [comment]
The reason for the change was, that ClientHandle and MonitoredItemId are not „synchronized“ ones "UA_Client_Subscriptions_addMonitoredItem" was called for a non-existing node.

**Comment by Stasik0** [comment]
@ichrispa so you are okay with the merge?

**Comment by Stasik0** [comment]
@StalderT @ichrispa bump?

**Comment by Stasik0** [comment]
@ichrispa bump?

**Pull request merged**
