### PR TITLE
fix something missing for #1311

### PR DESCRIPTION
**Pull request by StalderT**
https://github.com/open62541/open62541/pull/1311

### CODE REVIEW

**Comment by StalderT** [comment]
yes ```sub->lastSendMonitoredItemId = mon->itemId;``` must be after the loop else we fail one monitoredItem. Sorry !!!

**Comment by jpfr** [comment]
Did you see the problem in practice?

I think the code is fine as-is.
We store the id of the monitoreditem where we had to stop.
Then we resume at this id (not after this id).

**Comment by StalderT** [comment]
do you speak about the second commit of this PR or the two commits?

**Comment by StalderT** [comment]
Because currently we have an infinite loop here:

https://github.com/open62541/open62541/blob/b9c9fc05108d071b9e848c57c6d9fc799d8f7d7c/src/server/ua_subscription.c#L142-L145

**Pull request closed without merging**
