### PR TITLE
Backport fixes to 0.3

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by jonasgreen88** [comment]
Can we backport this PR #2084 as well?

**Comment by jonasgreen88** [comment]
@jpfr Do you think we can merge this PR soon? Or do you wait for some other changes as well?

**Comment by jpfr** [comment]
Just merged #2084.
Let's just wait for CI to become green again.

**Comment by jonasgreen88** [comment]
Thank you! :+1:

**Pull request merged**
