### PR TITLE
fix appveyor and deprecated mbedtls functions

### PR DESCRIPTION
**Pull request by StalderT**
fix https://github.com/open62541/open62541/issues/1616

see https://ci.appveyor.com/project/open62541/open62541/build/5773/job/s5j54usp83m0kt48

### CODE REVIEW

**Comment by StalderT** [comment]
I don't understand why appveyor failed here :

https://ci.appveyor.com/project/StalderT/open62541/build/527/job/3dn86yvs0kps1jid#L600

and here

https://ci.appveyor.com/project/StalderT/open62541/build/527/job/3menmxi662m34vbm#L1174

If someone have an idea?

**Comment by Infinity95** [comment]
Isn't there an mebedtls_sha1_ret function?
We could remove our own version then.

**Comment by StalderT** [comment]
deprecated is fixed. But remain problems with vs2008 and vc2013.

**Comment by StalderT** [comment]
https://github.com/Microsoft/vcpkg/commit/0334365f516c5f229ff4fcf038c7d0190979a38a#diff-464a170117fa96bf98b2f8d224bf503c cause the issue. I'm on it

**Comment by StalderT** [comment]
All green !
Appveyor is happy again. For me, can be merged.

**Comment by jpfr** [comment]
Perfect!

**Pull request merged**
