### PR TITLE
fix(arch): Fix architecture definitions for Embarcadero C++Builder clang/win32

### PR DESCRIPTION
**Pull request by ogsadmin**
Embarcadero C++Builder 10.4 (clang 5.0 / win32) has a few incompatibilities in its standard library, which prevents building Open62541 on this compiler.

I would like to suggest two small additions to the architecture definition files to fix build on this compiler. The changes do not break existing behavior and are guarded by `#ifdef __CODEGEARC__` to only become active for this compiler.

I would also like to add a fix for a bug in the gmtime_s() call in the arch/win32/ua_clock.c file - the call uses the wrong parameter order.

### CODE REVIEW

**Comment by jpfr** [comment]
Looks good! Can be merged like this.
Please click the CLA (in the CI list) so that we can merge.

**Comment by ogsadmin** [comment]
Unfortunately there is nothing to click in the CI list (or I can't find it, sorry). I've signed the CLA when I opened the first PR, but did not get a chance to do it again for this PR...

**Comment by andreasebner** [comment]
Add a "empty commit" which can be removed by an rebase later to restart the CI.

**Comment by jpfr** [comment]
Great. Rebased and now the CLA went green.
👍 For the contribution!

**Pull request merged**
