### PR TITLE
build(deps): bump deps/nodesetLoader from `fd60349` to `a6ef450`

### PR DESCRIPTION
**Pull request by GoetzGoerisch**
Bumps [deps/nodesetLoader](https://github.com/open62541/nodesetLoader) from `fd60349` to `a6ef450`.
- [Release notes](https://github.com/open62541/nodesetLoader/releases)
- [Commits](https://github.com/open62541/nodesetLoader/compare/fd603490d7dbf6727a9cfa8ac819657ed6ae4c47...a6ef45054ff74e0d798fccc257e4646355dadb6a)

---
updated-dependencies:
- dependency-name: deps/nodesetLoader dependency-type: direct:production ...

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
@jpfr I guess CIFuzz is failing due to the missing CI updates from 1581b063137cc23e256eed4634831a8169b28132 in `1.4`

**Comment by GoetzGoerisch** [comment]
Works with an update ci. https://github.com/open62541/open62541/actions/runs/8753891265
Dropped the commit again

**Comment by GoetzGoerisch** [comment]
relates #6432

**Comment by jpfr** [comment]
👍

**Pull request merged**
