### PR TITLE
fix basic256sha256 and add example server

### PR DESCRIPTION
**Pull request by StalderT**
fix : 

```
==59935== Invalid read of size 1
==59935==    at 0x4C326D6: memmove (vg_replace_strmem.c:1252)
==59935==    by 0x151154: asym_encrypt_sp_basic256sha256 (ua_securitypolicy_basic256sha256.c:228)
==59935==    by 0x159332: UA_SecureChannel_sendAsymmetricOPNMessage (ua_securechannel.c:431)
==59935==    by 0x168DF1: processOPN (ua_server_binary.c:370)
==59935==    by 0x169C80: processSecureChannelMessage (ua_server_binary.c:604)
==59935==    by 0x15A12E: UA_SecureChannel_finalizeChunk (ua_securechannel.c:791)
==59935==    by 0x15A91B: UA_SecureChannel_processChunk (ua_securechannel.c:1057)
==59935==    by 0x16A021: processCompleteChunkWithoutChannel (ua_server_binary.c:702)
==59935==    by 0x16A0A9: processCompleteChunk (ua_server_binary.c:728)
==59935==    by 0x157A92: processChunk (ua_connection.c:144)
==59935==    by 0x157B36: UA_Connection_processChunks (ua_connection.c:169)
==59935==    by 0x16A12E: processBinaryMessage (ua_server_binary.c:743)
==59935==  Address 0x625f0b0 is 0 bytes after a block of size 512 alloc'd
==59935==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==59935==    by 0x114220: UA_ByteString_allocBuffer (ua_types.c:228)
==59935==    by 0x150FD1: asym_encrypt_sp_basic256sha256 (ua_securitypolicy_basic256sha256.c:199)
==59935==    by 0x159332: UA_SecureChannel_sendAsymmetricOPNMessage (ua_securechannel.c:431)
==59935==    by 0x168DF1: processOPN (ua_server_binary.c:370)
==59935==    by 0x169C80: processSecureChannelMessage (ua_server_binary.c:604)
==59935==    by 0x15A12E: UA_SecureChannel_finalizeChunk (ua_securechannel.c:791)
==59935==    by 0x15A91B: UA_SecureChannel_processChunk (ua_securechannel.c:1057)
==59935==    by 0x16A021: processCompleteChunkWithoutChannel (ua_server_binary.c:702)
==59935==    by 0x16A0A9: processCompleteChunk (ua_server_binary.c:728)
==59935==    by 0x157A92: processChunk (ua_connection.c:144)
==59935==    by 0x157B36: UA_Connection_processChunks (ua_connection.c:169)
```

@bobbthebuilder or @Infinity95 can you confirm that the fix in ```asym_encrypt_sp_basic256sha256``` is correct ?

### CODE REVIEW

**Comment by Pro** [comment]
Thanks @StalderT 

Since we now duplicated the `loadFile` method quite often, could you think of a way to generalize it, at least within the examples. E.g. use a common header file for methods which are used by all the encryption examples (and unit tests)

**Comment by StalderT** [comment]
Maybe we can add ```loadFile``` in a plugin ?

**Comment by Stasik0** [comment]
Why plugin? Should it be cc0?

**Comment by StalderT** [comment]
> Why plugin? Should it be cc0?

Because ```loadFile``` use non portable function like ```fread```

**Comment by Pro** [comment]
As a first step I would vote for a simple common header in the examples folder, since the loadFile is only used for examples and unit tests, and not for the stack itself. Adding a Plugin for that is probably not the best option, since many embedded architectures do not support file systems and thus you always need to manually remove the plugin from the CMake when you compile the stack for that architecture. Maybe later when we add the Global Discovery server, we need more file functions, then we can think again how to add file handling in a portable way.

**Comment by Infinity95** [comment]
@StalderT looks good to me.

**Comment by StalderT** [comment]
I close this PR in favour of https://github.com/open62541/open62541/pull/1691

I removed ```loadFile``` in unit tests. I will open an issue for ```loadFile``` in examples.

**Pull request closed without merging**
