### PR TITLE
Update ua_mqtt_pal.c

### PR DESCRIPTION
**Pull request by jackybek**
return 0 if SSL_read() cannot process properly ;

### CODE REVIEW

**Comment by jpfr** [comment]
This is covered by the else-clause just below.

**Comment by jackybek** [comment]
i get a -1 from SSL_read().
These are the 2 locations that contains SSL_read():
        // ~/libwebsockets/lib/tls/mbedtls/wrapper/include/internal/ssl_code.h
        // /usr/local/src/openssl-1.1.1k/include/openssl/ssl.h

But I can't find the source code.  Without the source code of SSL_read(), i wont be able to identify what went wrong.  The reasons Can you advise ?

**Comment by jpfr** [comment]
The function you touched already checks for -1.
Just look inside the else-clause below your edit.

It uses `SSL_get_error` to get the actual error.
You might add some logging there to print an error message.

**Comment by jackybek** [comment]
Yes.. i have already done that:
                switch (error) {
                case SSL_ERROR_SSL:printf("error received is 1 : error = SSL_ERROR_SSL \n"); return MQTT_ERROR_SOCKET_ERROR;
                case SSL_ERROR_WANT_READ: printf("error received is 2 : error = SSL_ERROR_WANT_READ \n"); return read;
                case SSL_ERROR_WANT_WRITE:printf("error = SSL_ERROR_WANT_WRITE \n"); return read;
                case SSL_ERROR_WANT_ACCEPT:printf("error = SSL_ERROR_WANT_ACCEPT \n"); return read;
                case SSL_ERROR_WANT_CONNECT:printf("error = SSL_ERROR_WANT_CONNECT \n"); return read;
                case SSL_ERROR_WANT_X509_LOOKUP:printf("error = SSL=ERROR_WANT_X509_LOOKUP \n"); return read;
                case SSL_ERROR_SYSCALL: printf("error received is 5 : error = SSL_ERROR_SYSCALL \n"); return MQTT_ERROR_SOCKET_ERROR;

During execution, I get the following:
....
error received is 2 : error = SSL_ERROR_WANT_READ
error received is 2 : error = SSL_ERROR_WANT_READ
error received is 2 : error = SSL_ERROR_WANT_READ
error received is 2 : error = SSL_ERROR_WANT_READ
error received is 2 : error = SSL_ERROR_WANT_READ
[2021-08-30 20:56:29.875 (UTC+0800)] info/securitypolicy        The basic256sha256 security policy channel with openssl is created.
[2021-08-30 20:56:29.917 (UTC+0800)] info/channel       Connection 9 | SecureChannel 1 | SecureChannel opened with SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 and a revised lifetime of 600.00s
**error received is 1 : error = SSL_ERROR_SSL**
[2021-08-30 20:56:29.937 (UTC+0800)] error/server       **PubSub MQTT: yield: error: MQTT_ERROR_SOCKET_ERROR**

At this point, i like to inspect the source code to see what really caused the error "MQTT_ERROR_SOCKET_ERROR".
Could the issue be related to 
1. ca cert
2. server cert
3. server key
4. directory related issues

**Comment by jackybek** [comment]
i finally found the source code for SSL_read in openssl.

**Pull request closed without merging**
