### PR TITLE
[Review] First attempt of mDNS interface selection (relates to #2774)

### PR DESCRIPTION
**Pull request by Stasik0**
I made a most-easy way of setting the outbound inerface by entering exact IP. In case user wants some more sugar like selecting interface from string, e.g. "eth0", she will need to do it in user-space.

#2774

### CODE REVIEW

**Comment by ccvca** [comment]
I have only skimmed over the previous communication #2774 , wouldn't it make more sense to send on all interfaces where the OPC UA Server is reachable as fallback? Selecting the first one seems random to me.

**Comment by Pro** [comment]
That's a valid point...

Currently we are just adding a tcp socket for every interface we find:
https://github.com/open62541/open62541/blob/master/arch/network_tcp.c#L359
In the future this should be changed to give the user an option to select a specific interface by specifying an IP address where the server should listen (i.e., 0.0.0.0 is the default and means all interfaces). That should then also be part of #2408 here:
https://github.com/open62541/open62541/pull/2408/files#diff-431422d938c278cd653aa380ecdcfd40R292 (ping @mlgiraud)


For mDNS we could use this information and if the tcp listener interface is set to:
- 0.0.0.0:
	- default: check all interfaces which have multicast enabled, and send mDNS on all of them
    - in addition the user may limit the interface selection to a subset of these
- specific ip: only send mDNS packages on the interface which has that ip

Does that make sense?

The next issue is then, what about the case where a server only has UDP interface, or even ETH?
Maybe the most intuitive configuration option is, to configure the mDNS socket independent of the listener sockets.

I.e.:
- Default behaviour: check all interfaces which have multicast enabled, and send mDNS on all of them
- The user can select one or more interfaces where mDNS is sent

**Comment by Stasik0** [comment]
> I have only skimmed over the previous communication #2774 , wouldn't it make more sense to send on all interfaces where the OPC UA Server is reachable as fallback? Selecting the first one seems random to me.

This PR extends the default 0.0.0.0 behavior to be able to specify one non-random interface.

> Default behaviour: check all interfaces which have multicast enabled, and send mDNS on all of them
Here is some example linux-code https://github.com/troglobit/mdnsd/blob/b12ac76c456fb146a697bc3170e67a9ffc7dedbd/src/addr.c
Is there any posix way to do that?

+1 for @Pro's proposal. But it is done in #2408, right?

Do we still want to have this PR merged in? Maybe we should replace the one IP-String by an array of strings for later?

**Comment by jpfr** [comment]
👍 For merging this.
Many people have that problem on boxes with many interfaces (LAN, Wifi, VMWare, etc.)

And we need the hint for #2048.
There, we start with "normal" TCP for the new network manager and then bring over mDNS and other communication gradually over time.

@Stasik0 Welcome back!
Can you squash out your fix-commits in a rebase?

@Pro You're the master of mDNS. Can you do the merge when you are okay?

**Comment by Pro** [comment]
I opened a new issue #2864 to collect the ideas from this PR and squash-merged these changes.
Thanks @Stasik0

**Pull request merged**
