### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/open62541/open62541/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/open62541/open62541).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by jpfr** [comment]
Cool! The code analysis for python looks very helpful.
It should be easy to get a better ranking than "D".

**Comment by xcorail** [comment]
Hi @jpfr 
Happy you found it cool and helpful!

While you are fixing the python alerts, I recommend you to activate automated code review. LGTM will analyse immediately your Pull Requests and comment them, preventing new problems to reach your master while you are trying to fix the existing ones. It's a free and [one-click operation](https://lgtm.com/projects/g/open62541/open62541/ci/)

Cheers

**Comment by jpfr** [comment]
Done and done.

**Comment by xcorail** [comment]
👍 
And of course, if some public projects you are following are not yet on LGTM, feel free to add them [here](https://lgtm.com/dashboard)

**Pull request merged**
