### PR TITLE
add InfoBits Overflow

### PR DESCRIPTION
**Pull request by StalderT**
fix https://github.com/open62541/open62541/issues/1505

### CODE REVIEW

**Comment by StalderT** [comment]
image

**Comment by Pro** [comment]
@StalderT is this commit related to:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/open62541/5LylGYaew_Y/xaPxHtn8AQAJ

**Comment by StalderT** [comment]
> @StalderT is this commit related to:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/open62541/5LylGYaew_Y/xaPxHtn8AQAJ

Yes. Do we accept that the configuration is changed while running?

**Comment by StalderT** [comment]
I looked a little too fast. I will look at this tomorrow in more detail!

**Pull request merged**
