### PR TITLE
fix(nodeset-loader): Minor bugfixes

### PR DESCRIPTION
**Pull request by MurzynJ**

### CODE REVIEW

**Comment by MurzynJ** [comment]
@keba-uso
UA_Server_loadNodeset is declared to return UA_StatusCode, so I changed the implementation to return UA_STATUSCODE_GOOD or BAD.

But in all of the tests you treat the result as bool, so they fail now. Shall I go on and update the tests?

**Comment by keba-uso** [comment]
> @keba-uso UA_Server_loadNodeset is declared to return UA_StatusCode, so I changed the implementation to return UA_STATUSCODE_GOOD or BAD.
> 
> But in all of the tests you treat the result as bool, so they fail now. Shall I go on and update the tests?

@MurzynJ since the function returns `UA_StatusCode`, it is much cleaner to apply this fix and update the tests. Thank you!

**Comment by jpfr** [comment]
Thanks for this.
Suddely we have failing tests. E.g. check_nodeset_loader_di.

**Comment by MurzynJ** [comment]
> Thanks for this. Suddely we have failing tests. E.g. check_nodeset_loader_di.

Yes, I knew it, but wanted first to confirm with Srdjan if it's okay to update that many tests.
Now the tests are updated and the CI is green.

**Comment by jpfr** [comment]
Ok, merged.

**Pull request merged**
