### PR TITLE
add UA_Client_Subscriptions_removeMonitoredItems

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by jpfr** [comment]
@StalderT ,

do you understand why travis won't complete?
The log messages are not very helpful.

**Comment by StalderT** [comment]
I do not understand either. It's travis-ci/push not travis-ci/pr. Try rebuild?

**Comment by StalderT** [comment]
When travis-ci / push succeeded: 

image

Here it apparently did not work

image

Temporary network failure ?

**Comment by StalderT** [comment]
should be fixed in https://github.com/open62541/open62541/pull/1504

**Pull request merged**
