### PR TITLE
[Review] feat(ex): Add a VxWorks TSN publisher example

### PR DESCRIPTION
**Pull request by sarh2o**
This publisher is a complement to pubsub_interrupt_publish.c. It is a VxWorks
specific implementation with VxWorks-native TSN features and can be applied to
hard realtime scenarios.

### CODE REVIEW

**Comment by jpfr** [comment]
Looking good!
But can we keep the vxworks-specific definitions out of `include/open62541/server_pubsub.h`?

They are not used "inside" the SDK.
So they could be moved to the architecture definitions or the plugins.

**Comment by sarh2o** [comment]
Hi @jpfr ,
Thanks for your comments!
It seems that UA_ETFConfiguration is used for TSN purpose? Can we extend this structure instead of creating a new one?
If we can't, can we utilize "connectionProperties" attribute of struct UA_PubSubConnectionConfig to carry "streamName" and "stackIdx"?

Thanks for your guidance!

**Comment by sarh2o** [comment]
Hi @jpfr ,
Sorry for disturbing you again.
Could you please provide your insight about the solution of removing the vxworks-specific definitions out of include/open62541/server_pubsub.h?
We have two options:
1. Add  "streamName" and "stackIdx" to UA_ETFConfiguration to take instread of creating a new structure
2. Utilize "connectionProperties" attribute of struct UA_PubSubConnectionConfig to carry the information of "streamName" and "stackIdx"

Which one do you prefer?
Looking forward to you feedback.

Thanks and Best regards!

**Comment by jpfr** [comment]
I prefer the connectionProperties.
Keep up the good work!

**Comment by sarh2o** [comment]
Hi @jpfr,
Thanks for your advice! I have updated the code accordingly.
Besides your comments, I also align the code with the latest definition of struct “UA_DataSetVariableConfig”.
Now all checks have passed.

Thanks!

**Comment by jpfr** [comment]
Looks good.

Now you only have to remove the weird `_WRS_CONFIG_OPEN62541_UA_ENABLE_PUBSUB_ETH_UADP_VXWORKS_TSN` flag.

Is it really necessary to add a new compiler flag?
Usually there are system-defined macros to detect a specific OS.

**Comment by sarh2o** [comment]
Hi @jpfr ,
No problem! I have updated the code again.
Please have a look.

Thanks!

**Comment by jpfr** [comment]
Looks good and can be merged.
Can make it to 1.2 as well, as the change is non-breaking.

I changed the base to 1.2 instead of master (they are currently identical).
However, now I see merge conflicts.

Can you rebase and squash to a single commit?

**Comment by sarh2o** [comment]
Hi @jpfr,
Thanks for your reply.
I have rebased my dev branch on V1.2 and resolved the conflicts.
But I met building issue: open62541.open62541 (Windows (VS2017)) which I never saw in former CIs.
It seems that below test case failed:

Start 14: services_view

I think my changes should has no impact on this case.
I'd like to know whether it is an env issue? If it is my issue, how can I reproduce it locally?
Is there any manual or tutorial which can show me how to run such a test case locally?

Thanks for your help!

**Comment by jpfr** [comment]
Looks good. Thanks for shepherding until now.

**Pull request merged**
