### PR TITLE
fix: Really close the websocket connection

### LINKED ISSUE #3639: Websocket "transport" does not close lws connections
## Description
The websocket transport does not close lws connections,
That means all websocket connections stay open

## Background Information / Reproduction Steps
the callback is called but, the lib websockets is not "informed" about the
closing intent.
Because to close the connection -1 has to be returned within the lws callback 

Used CMake options:
UA_ENABLE_WEBSOCKET_SERVER:BOOL=ON
UA_BUILD_EXAMPLES:BOOL=ON

UA_ENABLE_WEBSOCKET_SERVER:BOOL=ON
```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [x] Other OPC UA SDKs used (client or server): wsopcua client (to be released soon)
 - [ ] Operating system: debian 10.3
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

### PR DESCRIPTION
**Pull request by demike**
as stated in issue #3639 the websocket connections are not closed,
because libwebsockets does not get informed about the close event.
As stated in the lws documentation: to close a connection return -1 from within the lws callback

I stumbled uppon this problem, when running wsopcua client reconnect integration tests against the open62541
(usually working against UA-CPP server with websocket proxy) 

* fixes #3639
* allows connections with the officially registered websocket protocols opcua+uacp, opcua+json

### CODE REVIEW

**Comment by jpfr** [comment]
Thanks for the fix!
You added a second commit to announce support for "opcua+json".
I'm not sure we can do that already.

At least we would need a SecureChannel that actually performs JSON decoding.

**Comment by demike** [comment]
> Thanks for the fix!
> You added a second commit to announce support for "opcua+json".
> I'm not sure we can do that already.
> 
> At least we would need a SecureChannel that actually performs JSON decoding.

- "opcua+json" would be a preparation for future work.
- "opcua+uacp" specifies the binary protocol
Should I comment out "opcua+json" until the secure channel supports it?

**Comment by jpfr** [comment]
>  Should I comment out "opcua+json" until the secure channel supports it?

Yes, please.

**Comment by jpfr** [comment]
Merged. Thanks!

**Pull request merged**
