### PR TITLE
LDS customizable timeout for automatic de-register

### PR DESCRIPTION
**Pull request by Pro**
Added field in config to modify default timeout for de-registering a server.
`config.discoveryCleanupTimeout` in seconds

### CODE REVIEW

**Comment by Pro** [comment]
Can be merged, if no objections.

**Comment by jpfr** [comment]
Hey @Pro,
the branches have diverged and I cannot write to your PR...
This can be merged from my side.

**Comment by Pro** [comment]
@jpfr just rebased it on the current master branch, for your convenience.
It should be possible to automatically merge it now.

**Comment by jpfr** [comment]
Thank you!
If you could just fix the memleak on valgrind, we can merge. :-)

**Comment by Pro** [comment]
@jpfr done

**Pull request merged**
