### PR TITLE
fix for #1411

### PR DESCRIPTION
**Pull request by StalderT**

### CODE REVIEW

**Comment by StalderT** [comment]
if you agree, for me you can merge

**Comment by Pro** [comment]
Fix for #1411

**Comment by jpfr** [comment]
I have to admit, I don't fully understand the change.

Every PublishResponse contains exactly one NotificationMessage.
And every NotificationMessage has a sequence number.
In the existing code we add the new number to the list of pending acknowledgements.

In the patch you add the pending acknowledgements in the list a second time.
I'm not sure about that. Can you add comments that explain what is happening?
Otherwise the next developer will be seriously stuck looking at the code.

**Comment by StalderT** [comment]
Ok, I missed something. Sorry!!!!

Thank you for the explanations.

I try to explain actual problem.

With current code : 

--------------

1) First publish response (with a notification message)

image

AvailableSequenceNumbers 1
Sequence Number 1

--------------

2) Next publish request ack sequenceNumber 1

image

-----------------

3) Next publish response (without notification message)

image

AvailableSequenceNumbers : none
Sequence Number 2

--------------

4) Next publish request ack sequenceNumber 2

image

--------------

5) Next publish response (without notification message) return BadSequenceNumberUnknow
because last publish request try to ack sequenceNumber 2.

Because SequenceNumber 2 is not present in retransmission message queue  : 

```
    if(notifications == 0) {
        /* Send sequence number for the next notification */
        message->sequenceNumber = sub->sequenceNumber + 1;
    } else {
        /* Increase the sequence number */
        message->sequenceNumber = ++sub->sequenceNumber;

        /* Put the notification message into the retransmission queue. This
         * needs to be done here, so that the message itself is included in the
         * available sequence numbers for acknowledgement. */
        retransmission->message = response->notificationMessage;
        UA_Subscription_addRetransmissionMessage(server, sub, retransmission);
    }
```


image

-----------------------------

I propose a new fix.

**Comment by StalderT** [comment]
Ok to merge or do you need more information ?

**Comment by StalderT** [comment]
Can we merge? Do you want changes or explanations?

**Pull request closed without merging**
