### PR TITLE
[REVIEW] Fix potential memleak in sks examples

### PR DESCRIPTION
**Pull request by NoelGraf**

### CODE REVIEW

**Comment by jpfr** [comment]
We have an "official" way to set/get information attached to a session: `UA_Server_getSessionAttribute`
The clientUserId used for the last activation is always available to get.
Please check if you can use that instead of the void-pointer session context.

**Comment by NoelGraf** [comment]
The session context must be set for the getUserExecutableOnObject_sks function callback.

**Comment by NoelGraf** [comment]
Changes made.
However, the `UA_Server_getSessionAttribute` function cannot be used directly because the session KeyValueMap is NULL.

**Comment by jpfr** [comment]
You don't have to set the attribute. `0:clientUserId ` is always available.
https://github.com/open62541/open62541/blob/dc91b22a34cdbe89311e09a036af44412c815253/include/open62541/server.h#L569C6-L569C21

**Comment by jpfr** [comment]
👍

**Pull request merged**
