### PR TITLE
[REVIEW] Fix HasInterface reference on types without HasInterface reference

### PR DESCRIPTION
**Pull request by basyskom-jvoe**
If a BaseObjectType object with a HasInterface reference is instantiated from a model, the HasInterface reference is missing.

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
Thanks for this fix. 🙏

**Comment by andreasebner** [comment]
Looks great. Thanks!

**Review by andreasebner — COMMENTED** [review]
Looks great, thanks!

**Review by andreasebner — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
