### PR TITLE
[Review] Added statistic counters for client and server

### PR DESCRIPTION
**Pull request by jonasgreen88**
Counters have been added for the network, secure channel and session
layer.

### CODE REVIEW

**Comment by jonasgreen88** [comment]
I have defined a proposal of a set of statistic counters for the network, the secure channel and the session layer according to the discussion in issue #2136.

Open for review to get the counter setup agreed before adding unittests.

**Comment by mlang-de** [comment]
Nice to see such PR!
IMHO it is the first step into direction of the specified ServerDiagnostics.
So if it make sense the specified names shall be used where possible?!

image

**Comment by jpfr** [comment]
Very cool feature!

I agree with @mlang-de that we should stay close to the counters defined in the standard.

Also, can the `_getStatistics` methods directly return the struct instead of pointers?
That's one source for bugs less. ;-)

Keep up the good job!

**Comment by jonasgreen88** [comment]
@jpfr @mlang-de Thanks for the feedback and the hint about the ServerDiagnosticsSummaryType. The session counters are now reflecting this type completely. The network and secure channel counters are harmonizing with the session counters as far as possible.

**Comment by jpfr** [comment]
> The session counters are now reflecting this type completely.

Perfect PR. We can merge when CI goes green.

**Comment by jonasgreen88** [comment]
Solved all obvious CI errors. 

Now there is some problem with Sphinx and documentation generation on Travis:
```
/home/travis/build/open62541/open62541/build/doc_src/nodeset_compiler.rst:383: ERROR: Unknown interpreted text role "numref".
/home/travis/build/open62541/open62541/build/doc_src/protocol.rst:92: ERROR: Unknown interpreted text role "numref".
```

Also clang fails on Travis in some file this PR doesn't touch:
```
/home/travis/build/open62541/open62541/src/client/ua_client_subscriptions.c:607:5: warning: Potential memory leak
    return;
```

Azure past before the last commit, now there is some error I can't figure out. It says all unittests passed.

**Comment by jpfr** [comment]
See #3399.

**Comment by jonasgreen88** [comment]
Merged in #3399

**Pull request closed without merging**
