### PR TITLE
feat: Lock-based enhancement using mutexes

### PR DESCRIPTION
**Pull request by ckmk14**
This PR implements a first approach to enable the parallel access of the public server api. 
A lock-based enhancement using mutexes is established to avoid race-conditions when accessing data structures in parallel threads.

### CODE REVIEW

**Comment by jpfr** [comment]
Looks really good!
One minor wish: We should document what the levels 0/100/200 mean.
In the .rst docs and very short also in the CMake variable description.

@Pro This build is failing on Azure.
Is this a general problem or only concerning this PR?
Looks like a general problem to me...

**Comment by Pro** [comment]
Yeah, just saw the error today. Will fix it today evening. It's a general caching issue

**Comment by jpfr** [comment]
Very nice! Merged.
We can remove the EXPERIMENTAL flag to MULTITHREADING=100 once the server API is covered.

**Comment by cmbahadir** [comment]
Hello All,

This merge breaks freertos build pipeline of me.

https://travis-ci.org/cmbahadir/opcua-esp32/builds/560100952

Seems like UA_MULTITHREAD is not enabled for other architectures as long as it is set as 100.

[ua_architecture.h](https://github.com/ckmk14/open62541/blob/cada90600c7766657ba351ce11e864f43df608d7/arch/posix/ua_architecture.h#L150)

**Comment by ckmk14** [comment]
Hello @cmbahadir 

you are absolutely right. The macros are not defined in all the different architecture.h files. Freertos is one of them. I will add the missing definitions.

**Comment by Pro** [comment]
@cmbahadir would you be able to provide a PR which adds FreeRTOS to out build pipeline?
Then we can avoid issues like this in the future.
See also #1910

**Comment by cmbahadir** [comment]
Hi @Pro created PR #3023

**Pull request merged**
