### PR TITLE
fix #1439 (UTC / LocalTime)

### LINKED ISSUE #1439: Logging time differs from system time
The time displayed in the logs is one hour behind my actual time. This happens on linux and windows.
Maybe something with summer/winter time?

revision: 926724d9256fcab391ddf5db526053c24fa2c9fe

### PR DESCRIPTION
**Pull request by StalderT**
fix https://github.com/open62541/open62541/issues/1439

### CODE REVIEW

**Comment by jpfr** [comment]
Very nice!

For symmetry, I propose we rename the current `UA_DateTime_now` to `UA_DateTime_nowUtcTime` and add a compatibility macro
```c
#define UA_DateTime_now() UA_DateTime_nowUtcTime()
```

so we have
- UA_DateTime_nowLocalTime
- UA_DateTime_nowUtcTime
- UA_DateTime_nowMonotonic

**Comment by StalderT** [comment]
@jpfr Good idea. I modify the PR accordingly.

**Comment by StalderT** [comment]
@jpfr Do you want that UA_DateTime_now is replaced everywhere by UA_DateTime_nowUtcTime? Or is it better to use compatibility macro?

**Comment by Infinity95** [comment]
Maybe it would be a good idea to add an indicator for the timezone to the logs?
Something like `%time% (UTC+%timediff%)`?

**Comment by jpfr** [comment]
Hello there,

I had a look at the standard.
> A DateTime value shall be encoded as a 64-bit signed integer (see Clause 5.2.2.2) which
represents the number of 100 nanosecond intervals since January 1, 1601 (UTC).

So DateTime should normally be UTC only. I think we are good if we just provide  UA_DateTime_localTimeUtcOffset,

The PR now contains some additional simplifications to time conversion.
We had lots of different macros defined. And they started to get confusing.

**Comment by jpfr** [comment]
Found the error. There was a utf8 character in a comment. Latex didn't like that.

**Pull request merged**
