### PR TITLE
Do not dynamically allocate a simple bool

### PR DESCRIPTION
**Pull request by basyskom-meerkoetter**
This PR is also an RFC.  :-)
Is there a good reason to allocate the bool on the heap? I saw it being done like this in a few places. I would tend to convert them all but want to collect feedback first.

### CODE REVIEW

**Comment by Pro** [comment]
I'd also with the stack version. At least I don't see any reason why it should be on the heap.

**Comment by basyskom-meerkoetter** [comment]
pushed a more complete patch where all instances of this pattern are converted

**Comment by jpfr** [comment]
We originally had an issue where users ran `UA_Server_run(server, &running)` in a background thread.
And wondered why this crashed.
Of course, stack-values cannot be accessed from another thread.
This came up a few times.

👍 For the initiative of @basyskom-meerkoetter ! This makes the code simpler.

In addition we should add a big warning to `UA_Server_run`.

**Comment by Pro** [comment]
Thank you very much!

**Pull request merged**
