### PR TITLE
Added callback function to get client config from config plugin

### PR DESCRIPTION
**Pull request by jonasgreen88**
The server implementation needs to initialize a client when it
shall register itself to a discovery server. To avoid including a
private header file of the plugin, a callback function has been
declared in the server header file to be implemented by the plugin
implementation. This callback function are called by the server
when it shall initialize a client.

### CODE REVIEW

**Comment by jonasgreen88** [comment]
Because ua_client.h is included in ua_server.h some include loop is created which causes the PR fail building. Any ideas how to solve that?

**Comment by jonasgreen88** [comment]
#1258

**Comment by jpfr** [comment]
The include loop should be solved by #ifdef include guards.
My guess is the problem stems from the amalgamation where we squash all files together.

Maybe we can have a file order for the amalgamation in CMakeLists.txt like that:
- ua_server.h
- ua_client.h
- ua_server_config.h

Otherwise, we might have to work with forward declarations of structures.

Best regards,
Jlius

**Comment by Pro** [comment]
In this case I would go for a forward declaration of UA_ClientConfig in `ua_server.h` and remove `#include "ua_client.h"` as it is already done for UA_ServerConfig.

Like this we do not include all the client dependencies in the server.

@jonasgreen88 thanks for the PR, nice idea!

**Comment by jonasgreen88** [comment]
@Pro @jpfr Before I uploaded the PR I tried to replace the include of ua_client.h with a forward declaration like this: 
```
struct UA_ClientConfig;
typedef struct UA_ClientConfig UA_ClientConfig;
```
But the problem I faced then was that the UA_ClientConfig was already type defined in ua_client.h. GCC does not allow a typedef to occur multiple times.

**Comment by Pro** [comment]
Isn't it enough to just use `struct UA_ClientConfig;` without the typedef in the forward decl? Not sure though...

**Comment by jonasgreen88** [comment]
If you don't typedef it I think you have to write `struct UA_ClientConfig UA_Server_getClientConfig(void)`. I'm not sure how the compiler would treat `UA_ClientConfig clientConfig = UA_Server_getClientConfig();` in that case.

**Comment by jpfr** [comment]
Would it be better to invent a (samll) header file `ua_client_config.h`?
Then the client and server can depend on that.
And it would be symmetric to `ua_server_config.h`.

**Comment by jonasgreen88** [comment]
> Would it be better to invent a (samll) header file ua_client_config.h?
Then the client and server can depend on that.
And it would be symmetric to ua_server_config.h.

I tried to add a ua_client_config.h and move the definition of UA_Struct to this file but kept the typedef in client.h. But I couldn't get rid of the include of ua_plugin_network.h which is needed as UA_Connection is defined there. Ua_plugin_network.h then includes ua_server.h and the include loop is created...

@jpfr Do you have an idea how to solve it?

**Comment by Pro** [comment]
@jonasgreen88 I think I found a solution for this, let's see if CI is happy

**Pull request merged**
