### PR TITLE
modify UA_Client_Subscriptions_manuallySendPublishRequest to return status

### PR DESCRIPTION
**Pull request by StalderT**
Hello,

If I modify the client (in example directory) with something like that : 

```
while(1)
{
    UA_Client_Subscriptions_manuallySendPublishRequest(client);
    sleep(1);
}
```
I don't have possibility to know if the client are connected to the server.

You can find a PR to correct this problem.

### CODE REVIEW

**Comment by Stasik0** [comment]
+1 here, @ichrispa owns the code
@StalderT could you squash your commits to one?

**Comment by StalderT** [comment]
@Stasik0 do you know how I can squash commits?

**Comment by jpfr** [comment]
Squashing can be done via rebase -i.
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

Then `push --force` the branch to overwrite your PR with the single commit.

**Comment by StalderT** [comment]
Sorry, I have tried, but I can't squash commits.

**Comment by ichrispa** [comment]
Seems reasonable to me :+1:

**Pull request merged**
