### PR TITLE
feat(tests): Extend tests for writing int32 into custom enum type

### PR DESCRIPTION
**Pull request by rickboks**
Extended tests to include creating a custom enumeration type and writing a int32 to it. As it stands, this test fails. See issue #6520

### CODE REVIEW

**Comment by jpfr** [comment]
I see the definition of the DataTypeNode.
But you don't add the custom UA_DataType description to the server config.
Historically the `UA_DataType` structure is used to describe datatypes for de/encoding.
And we look that up in the code path we are discussing.

Here is the example for adding custom types.

https://github.com/open62541/open62541/blob/46c5caae45e5523ac3021a33e74d3902f04d32f4/examples/custom_datatype/server_types_custom.c#L252

**Comment by rickboks** [comment]
Many thanks! I got it working. One thing that is not quite clear to me yet is the `UA_DataType.binaryEncodingId`. The examples in `server_types_custom.c` have different values for `.typeId` and `.binaryEncodingID`; the `namespaceIndex` and `identifierType` are identical between the two, but the `identifier` is chosen differently (see below snippet from `custom_datatype.h`). What is the reason behind this? Can't I simply use the same `.typeId` and `.binaryEncodingId`? Also, do the `indentifierType`s need to match between the two?

```
static const UA_DataType PointType = {
        UA_TYPENAME("Point")                /* .tyspeName */
        {1, UA_NODEIDTYPE_NUMERIC, {4242}}, /* .typeId */
        {1, UA_NODEIDTYPE_NUMERIC, {Point_binary_encoding_id}}, /* .binaryEncodingId, the numeric
                                            identifier used on the wire (the
                                            namespaceindex is from .typeId) */
        sizeof(Point),                      /* .memSize */
        UA_DATATYPEKIND_STRUCTURE,          /* .typeKind */
        true,                               /* .pointerFree */
        false,                              /* .overlayable (depends on endianness and
                                            the absence of padding) */
        3,                                  /* .membersSize */
        Point_members
};
```

**Comment by jpfr** [comment]
The type is being different is one of the warts of the standard. Maybe at some time we can use the typeid everywhere. But not now. And also all built in types in ns0 have a different encoding id for binary/json/xml.

**Comment by rickboks** [comment]
I see. But I *can* use the same type/binary encoding ID for my custom types, right?

**Comment by jpfr** [comment]
It will probably work alright.
Not sure if some other OPC UA product will complain.

**Comment by rickboks** [comment]
Great, thanks again for your help.

**Comment by maikrou** [comment]
Hi @rickboks, would it be possible to share the code you are using to get the custom enumerations working?

I had the exact same issue when using UA_Server_addDataSourceVariableNode, even after adding the data type to the configuration, I am probably adding it incorrectly or compiling with wrong settings? I tried with UA_NAMESPACE_ZERO "FULL" but no luck there either.

For me I got things working (not perfectly) by adding that enum to int32 check in compatibleDataTypes() at ua_services.attribute.c

Another question: does your enumerations work with all clients? I got mine working with UaExpert but not with OpcUaBrowser. Reason for the enumerations don't show up is because the data type is not visible in the OPC Binary DataTypeDictionary nor is the DataTypeDefinition attribute supported. OPC-10000-3 states that either one is mandatory for enumerations.

I am not sure if that DataTypeDictionary should get updated if the type is added properly to the stack but currently I can see that its content is compiled into: 

static const UA_Byte variablenode_ns_0_i_7617_variant_DataContents_byteArray[182253] = {...}

I can't see that it gets updated at any point, and the stack does not support the "DataTypeDefinition" attribute so I am not sure how that would work according to specification.

**Comment by rickboks** [comment]
Hi @maikrou. I added the following code **before** the call to `UA_Server_addDataTypeNode`. If you add it afterwards, UAExpert will show created variables with this enum type as plain `Int32`. I have only tested with `UAExpert` so far. Is [this](https://prosysopc.com/products/opc-ua-browser/) the OpcUaBrowser you refer to?

Regarding compile options, I only use `UA_ENABLE_ENCRYPTION=OPENSSL`

```
// I added the below block of code (needs to be BEFORE the call to UA_Server_addDataTypeNode)
UA_NodeId enumTypeNodeId = UA_NODEID_STRING_ALLOC(namespaceIndex, name);
UA_DataType *newEnumDataType = (UA_DataType*)(UA_malloc(1 * sizeof(UA_DataType)));
newEnumDataType[0] = UA_TYPES[UA_TYPES_ENUMERATION]; 
newEnumDataType->typeId = enumTypeNodeId;
newEnumDataType->binaryEncodingId = enumTypeNodeId;
newEnumDataType->typeName = strdup(name);
UA_ServerConfig* serverConfig = UA_Server_getConfig(server);
UA_DataTypeArray tempCustomDataTypes {serverConfig->customDataTypes, 1, newEnumDataType, UA_TRUE};
UA_DataTypeArray* newCustomDataTypes = (UA_DataTypeArray*) UA_malloc(sizeof(UA_DataTypeArray));
memcpy(newCustomDataTypes, &tempCustomDataTypes, sizeof(UA_DataTypeArray));
serverConfig->customDataTypes = newCustomDataTypes;

// This was already here
UA_StatusCode statusCode = UA_Server_addDataTypeNode(server, enumTypeNodeId, 
  UA_NODEID_NUMERIC(0, UA_NS0ID_ENUMERATION),
  UA_NODEID_NUMERIC(0, UA_NS0ID_HASSUBTYPE),
  UA_QUALIFIEDNAME (namespaceIndex, name),
  dattr, nullptr, nullptr));

// ... define EnumValues ...
```

**Comment by maikrou** [comment]
@rickboks Yes, Prosys OPC UA Browser. I managed to get the enumerations to show up like this: https://postimg.cc/gallery/d088gy9

I think I have done exactly like you but just added the data type to the config after calling UA_Server_addDataTypeNode, need to give it another try.

**Pull request closed without merging**
