### PR TITLE
[WIP]: Support for nodeset xml import

### PR DESCRIPTION
**Pull request by matkonnerth**
This PR uses the nodestore switch feature (https://github.com/open62541/open62541/pull/2748)  and plugs in a xml sax parser (from libxml). Nodestore_xml is relying on a valid nodeset, nodes are directly loaded into the nodestore, there are no checks implemented (e.g. check for invalid references). 

Example is provided by server_nodestore_switch.c, multiple nodeset can be provided on the commandline (in depending order, e.g. server_nodestore_switch DI PlcOpen).

### CODE REVIEW

**Comment by jpfr** [comment]
Oh wow. Loading the Nodesets at runtime is super cool!

Do you see a chance to get this working without integration into a specific nodestore?
By using the "public API" for all the nodestores...

**Comment by matkonnerth** [comment]
You mean by using the nodestore plugin API declared in nodestore.h? Then the loading of a xml would become indepedent of the storage/memory management of the nodes, sounds good for me. I will think of it and restructure this pr.

Another question:
Is it possible to add datatype (like a structure, enum) at runtime to the server? I mean, the things that are hardcoded in examples/custom_datatype/custom_datatype.h

**Comment by jpfr** [comment]
> Is it possible to add datatype (like a structure, enum) at runtime to the server?

Yes. By appending an entry to the linked list here:

https://github.com/open62541/open62541/blob/master/include/open62541/server_config.h#L101

**Comment by matkonnerth** [comment]
I've added a PR which is using the interface defined in nodesetore.h. https://github.com/open62541/open62541/pull/2937

I think you can close this PR.

**Pull request closed without merging**
