### PR TITLE
CLIENT : Fix log level in initConnect

### PR DESCRIPTION
**Pull request by StalderT**

### CODE REVIEW

**Comment by jpfr** [comment]
How is this a fix?
We should inform the user that he should be using the library differently.

**Comment by StalderT** [comment]
In sample we have :

https://github.com/open62541/open62541/blob/master/examples/client_connect_loop.c#L44-L47

If we start client_connect_loop.c with WARNING LOGS enabled we have the log on each cycle. The log is displayed endlessly.

**Comment by jpfr** [comment]
Run _connect only once and _iterate in a loop. This could be recommended in the warning.

**Comment by StalderT** [comment]
If we lose connection in the loop, _connect will automatically attempt to reestablish communication. The client has nothing more to manage. In my opinion this is really a plus that we cannot ignore. IMHO it would be good to fix this before the release of version 1.2.

**Pull request closed without merging**
