### PR TITLE
Fixing build failures caused by UA_FORCE_CPP flag

### PR DESCRIPTION
**Pull request by yagnasrinath**
Compiling with a C++ compiler caused failures due to some variables not initialized before goto jumps. This PR tries to fix those errors.

### CODE REVIEW

**Comment by yagnasrinath** [comment]
@jpfr I don't know how I could add reviewers. Could you please review or add appropriate reviewers?

**Comment by jpfr** [comment]
I put in myself.
Which compiler are you using? It might make sense to add it to the CI builds.

**Comment by yagnasrinath** [comment]
I have tried with :
clang++70 (Android arm32/arm64/x86_64 - ndk-r18b), 
gcc-7(x86_64),  
and gcc-linaro-7.2.1(arm32/arm64).

**Comment by yagnasrinath** [comment]
@jpfr let me know if you need any other info.

**Comment by jpfr** [comment]
Squashed and merged.
Thanks!

**Pull request merged**
