### PR TITLE
[Review] Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by mlang-de**
Remove trailing whitespaces from all c-source and header files.

### CODE REVIEW

**Comment by mlang-de** [comment]
Please rerun CI after memory leak is fixed which was introduced by commit 4fdee9623f65deb5f09ad7e61afebac93b6ddf9e.

**Comment by jpfr** [comment]
Let’s do this in all public header files.
Not a big fan of mass-commits otherwise.

There are ways to enforce good whitespace practices on changes code. For example by a CI Test that enforces it.

Can you make this PR for public headers only?

**Comment by mlang-de** [comment]
"Can you make this PR for public headers only?"  done by commit 472ce23
What is with the example header and/or deps folder headers? These are public headers too?

"There are ways to enforce good whitespace practices on future code changes. For example by a CI Test that enforces it."
I would appreciate it.

**Comment by mlang-de** [comment]
AppVeyor was cancelled, not sure why. Please retrigger.

**Comment by jpfr** [comment]
Resolved conflicts

**Pull request closed without merging**
