### PR TITLE
fix(PubSub): Fix decoding of rawdata message

### PR DESCRIPTION
**Pull request by keba-estr**
Fix decoding of rawdata message with rtLevel UA_PUBSUB_RT_FIXED_SIZE.

Resolves issue #5975

### CODE REVIEW

**Comment by keba-estr** [comment]
Does not work for multiple connections yet.

**Comment by jpfr** [comment]
Oh nice!
That’s a good contribution.

two wishes:
- extend the unit tests to prevent a future regression of the feature. Somehow this wasn’t caught by the pubsub j it tests that we have already.
- the networkmessage code deliberately didn‘t include ua_pubsub.h. In the future we might even make the message decoding part of the public API. And hence should not depend on internals in the invocation. You only need the dataSetMetaData from the reader. Please only forward that. And not the entire reader.

Keep up the good work!

**Comment by keba-estr** [comment]
Changed interface to use only dataSetMetaData.

**Comment by keba-estr** [comment]
For the UNIT tests the test PublishSubscribeWithWriteCallback in check_pubsub_subscribe_rt_levels.c should be extended with a second transferred variable.

**Pull request merged**
