### PR TITLE
[Review] Send ethernet packets with ethertype 0xb62c in PubSub

### PR DESCRIPTION
**Pull request by opcua-tsn-team-kalycito**
- Changed ethertype from LLC to ETHERTYPE_UADP(0xb62c) according to PubSub Specification
 - Handled the padding bytes in the src file

### CODE REVIEW

**Comment by jpfr** [comment]
There are two comments /* TODO: Need to handle padding bytes for UDP */
Please clarify the status.
Does the current code break for udp?

**Comment by opcua-tsn-team-kalycito** [comment]
No, it will not break the current UDP code. For now, UDP packets are never padded by the hardware as the minimum packet size exceeds 60 bytes. 

OPC UA UDP packet size: 
Default minimum header size: MAC header(14 bytes) + IP header(20 bytes) + UDP header(8 bytes)
Network message header size: 31 bytes - Current implementation with all pubId, DSWId and WGId enabled 
Total: 73 bytes (padding will not happen if total data is above 60 bytes)

In the future, OPC UA NetworkMessageHeader size can have minimum size (for eg: keepAlive message) less than 18 bytes which introduces padding while transmission. When this happens, multiple receiving of the messages feature is not handled.

**Comment by rexsum** [comment]
This patch only works when specifying a VLAN otherwise the header still contains a protocol type of LLC. It should not be necessary to specify a VLAN to get the proper Ethernet header as required by Part 14 section 7.3.3 of the OPC UA specification.

**Comment by opcua-tsn-team-kalycito** [comment]
@rexsum Thanks for pointing out the issue. It is resolved now.

**Pull request merged**
