### PR TITLE
[REVIEW] Allow dynamic port assignment

### PR DESCRIPTION
**Pull request by NoelGraf**

### CODE REVIEW

**Comment by keba-estr** [comment]
If dynamic port assignment should be fully supported with this pull request, should there really be a warning if this feature is used?

**Comment by keba-estr** [comment]
Is there any suitable documentation that can be extended to document the usage of port 0 as dynamic port assignment?

**Comment by NoelGraf** [comment]
Typically, dynamic port assignment is not used; it is intended primarily for test environments.
Therefore, a warning is issued.

**Comment by jpfr** [comment]
👍

**Pull request merged**
