### PR TITLE
Two build fixes for normal (non-amalgamated) builds

### PR DESCRIPTION
**Pull request by tobijk1**
First one installs a missing include
Second one fixes the include structure to not rely on the amalgamated open62541.h

This enables a clean normal build for me!

### CODE REVIEW

**Comment by tobijk1** [comment]
I consider the failing CI test wrong, as it does rely on amalgamation while not actually defining it!
Yet this can be fixed if actually the patches are considered allright!

**Comment by Pro** [comment]
I'm currently fixing some of the things you also include in the PR #2302 

I would like to merge 2302 first, since it includes some more changes and bugfixes. If you have specific suggestions/improvements to my changes in 2302, feel free to post a comment/review there

**Comment by tobijk1** [comment]
Oh, i did not check this time - silly me. Yeah most changes are the same, I will skim over them. I let this one open just for cross-checks on your side (if useful). Feel free to close it, i will come back with a new one if i run into trouble after #2302.

**Comment by Pro** [comment]
Yes, thanks! As soon as #2302 is all green, feel free to test that version and create a new PR/Issue if necessary.

**Comment by Pro** [comment]
Closing as already included/fixed by #2302

**Pull request closed without merging**
