### PR TITLE
Namespaces initialization code overhaul

### PR DESCRIPTION
**Pull request by ebissonn**
Current code crash Intel Compiler 18.1 possibly because the number of functions exhausts the stack memory

### CODE REVIEW

**Comment by Pro** [comment]
Thanks! Skimming through the changes, it looks good.

There's still an issue with multiple definition of `function_namespace0_generated`

Can you update the PR and fix the other CI issues?
Than I can do a final review and merge.

**Comment by ebissonn** [comment]
ok will do thanks!

**Comment by jpfr** [comment]
Hey @ebissonn 

Can you sign the CLA linked from this page?
Otherwise we cannot merge your contribution.

**Comment by ebissonn** [comment]
> Hey @ebissonn
> 
> Can you sign the CLA linked from this page?
> Otherwise we cannot merge your contribution.

Sorry but I am still waiting for our legal departement to review CLA and autorize my contribution...

**Comment by Pro** [comment]
@ebissonn any update regarding the CLA?
We would like to include this PR in the next release candidate which is planned around July 23rd 2019.

**Comment by Pro** [comment]
@ebissonn ping?

**Comment by Pro** [comment]
@ebissonn if your legal department can not authorize the whole CLA, it would also suffice for now that you give us the consent to use these specific changes according to the CLA?
Even better if you just declare these contributions under the MPL2.0 license (write it here), then we can merge.

**Comment by jpfr** [comment]
@ebissonn has not signed the CLA and seems to be unable to.
That’s a pity, but we cannot use the code in that case.

**Comment by andreasebner** [comment]
Thanks for the contribution. Since the CLA is not signed we will close the PR. Your welcome to support the open62541 again ;)

**Comment by andreasebner** [comment]
Thanks for the contribution. Since the CLA is not signed we will close the PR. Your welcome to support the open62541 again ;)

**Pull request closed without merging**
