### PR TITLE
Additional logic of setting monitoring mode

### LINKED ISSUE #1520: Setting Monitoring Mode
Description
===========
Hi! I read about *Monitoring Mode* in service specification.

> Disabled
*The item being monitored is not sampled or evaluated, and Notifications are not generated or queued. Notification reporting is disabled.*

> REPORTING
*The item being monitored is sampled and evaluated, and Notifications are generated and queued. Notification reporting is enabled.*

So, I think it needs to add some more code to open62541.

Background Information / Reproduction Steps
===========================================
I want to suggest below codes.

*ua_services_subscription.c*

```
In Operation_SetMonitoringMode

.....

if(mon->monitoringMode == UA_MONITORINGMODE_REPORTING) {
        MonitoredItem_registerSampleCallback(server, mon);
    } else if (mon->monitoringMode == UA_MONITORINGMODE_DISABLED){
        /*  Setting the mode to DISABLED causes all queued Notifications to be delete */
    	MonitoredItem_queuedValue *val, *val_tmp;
		TAILQ_FOREACH_SAFE(val, &mon->queue, listEntry, val_tmp) {
			TAILQ_REMOVE(&mon->queue, val, listEntry);
			UA_DataValue_deleteMembers(&val->value);
			UA_free(val);
		}
		mon->currentQueueSize = 0;
        /* initialize lastSampledValue */
		mon->lastSampledValue.data = NULL;
		mon->lastSampledValue.length = 0;

		MonitoredItem_unregisterSampleCallback(server, mon);
    }

```

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): v0.2 release
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu 14.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by ChaJiWon**
fix #1520  issue.

This commit is related with service specification (Part4)

```
7.18 Monitoring Mode

DISABLED_0
The item being monitored is not sampled or evaluated, and Notifications are not generated or queued. Notification reporting is disabled.

REPORTING_2
The item being monitored is sampled and evaluated, and Notifications are generated and queued. Notification reporting is enabled.
```

### CODE REVIEW

**Comment by StalderT** [comment]
Thanks. You should use 

```UA_ByteString_deleteMembers(&mon->lastSampledValue);``` 

instead of 
```
	mon->lastSampledValue.data = NULL;
	mon->lastSampledValue.length = 0;
```

and use space for indent not tab.

@jpfr 

If we call ```Operation_SetMonitoringMode``` with UA_MONITORINGMODE_REPORTING after with an invalid mode and after with UA_MONITORINGMODE_REPORTING, then the callback is registered twice.

Would it not be more prudent to do this:

```
    mon->monitoringMode = op_monitoringMode;
    if(mon->monitoringMode == UA_MONITORINGMODE_REPORTING) {
        MonitoredItem_registerSampleCallback(server, mon);
    } else  {
        /*  Setting the mode to DISABLED or invalid mode causes all queued Notifications to be delete */
        MonitoredItem_queuedValue *val, *val_tmp;
        TAILQ_FOREACH_SAFE(val, &mon->queue, listEntry, val_tmp) {
			TAILQ_REMOVE(&mon->queue, val, listEntry);
			UA_DataValue_deleteMembers(&val->value);
			UA_free(val);
		}
		mon->currentQueueSize = 0;

		/* initialize lastSampledValue */
		mon->lastSampledValue.data = NULL;
		mon->lastSampledValue.length = 0;

        MonitoredItem_unregisterSampleCallback(server, mon);
}
```

**Comment by StalderT** [comment]
@Pro 

DrMemory generate a memory leak here : 

https://ci.appveyor.com/project/open62541/open62541/build/5116/job/7oetuoqqf9jd3m5d#L10201

But appveyor return green. Can you check?

**Comment by jpfr** [comment]
> If we call Operation_SetMonitoringMode with UA_MONITORINGMODE_REPORTING after with an invalid mode and after with UA_MONITORINGMODE_REPORTING, then the callback is registered twice.

This can be circumvented if we set the monitoringmode only when a valid monitoringmode is set.
So `mon->monitoringMode = op_monitoringMode;` should only be done inside the if-clauses.

**Comment by StalderT** [comment]
> This can be circumvented if we set the monitoringmode only when a valid monitoringmode is set.
So mon->monitoringMode = op_monitoringMode; should only be done inside the if-clauses.

👍

**Comment by Pro** [comment]
> @Pro
> 
> DrMemory generate a memory leak here :
> 
> https://ci.appveyor.com/project/open62541/open62541/build/5116/job/7oetuoqqf9jd3m5d#L10201
> 
> But appveyor return green. Can you check?

Hopefully fixed in https://github.com/open62541/open62541/pull/1523

**Comment by ChaJiWon** [comment]
I update code applied upper comments.
Please review this pull requests.

**Comment by StalderT** [comment]
If Operation_SetMonitoringMode is called with

1)   UA_MONITORINGMODE_REPORTING
2)   UA_MONITORINGMODE_SAMPLING
3)   UA_MONITORINGMODE_REPORTING

So the callback is registered twice.

**Pull request merged**
