### PR TITLE
[Review] Subscriber information model

### PR DESCRIPTION
**Pull request by opcua-tsn-team-kalycito**
Subscriber Information model restructuring as per specification

- Restructuring done until dataSetReader

- TODO: Place susbcribedDataSet under DataSetReader

### CODE REVIEW

**Comment by andreasebner** [comment]
Hey @opcua-tsn-team-kalycito,

are there any updates on this pull request? How much effort is needed to make it ready? It would be sad if we lost this work.

**Comment by opcua-tsn-team-kalycito** [comment]
@andreasebner Yes we shouldn't lose this work. We will revisit this PR and make it ready.

**Review by andreasebner — COMMENTED** [review]
The code looks pretty good and straight forward. I think the SubscribedDataSetType is currently not visible in the information model. Maybe it would be a nice extension to this PR to make it also part of the information model.

**Comment by jpfr** [comment]
Ready to merge @andreasebner ?

**Comment by andreasebner** [comment]
Look's great now and can be merged from my point of view.

**Pull request merged**
