### PR TITLE
refactor completion/buffering of chunks

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by Stasik0** [comment]
@nikita158 could you test this one please

**Comment by nikita158** [comment]
@Stasik0 works fine with WinCC 7.4
<br>
TeslaScada still can't connect:
```
13:37:08.057 DEBUG: open62541: Connection 8 | New connection over TCP from 172.16.4.157:4765
13:37:08.059 DEBUG: open62541: Connection 8 | Process a HEL
13:37:08.068 DEBUG: open62541: Connection 8 | Process a OPN
13:37:08.068 DEBUG: open62541: Connection 8 | SecureChannel 13 | OpenSecureChannel: Opened SecureChannel
13:37:08.078 DEBUG: open62541: Connection 8 | Process a MSG
13:37:08.078 DEBUG: open62541: Connection 8 | SecureChannel 13 | Final chunk message
13:37:08.078 DEBUG: open62541: Try to use Session with token {00000000-0000-0000-0000-000000000000} but is not found
13:37:08.078 DEBUG: open62541: Connection 8 | SecureChannel 13 | Session {00000000-0000-0000-0000-000000000000} | Processing GetEndpointsRequest with an empty endpointUrl
13:37:08.086 DEBUG: open62541: Connection 8 | Process a MSG
13:37:08.086 DEBUG: open62541: Connection 8 | SecureChannel 13 | Final chunk message
13:37:08.086 DEBUG: open62541: Connection 8 | SecureChannel 13 | Unknown request 450
13:37:08.087 DEBUG: open62541: Connection 8 | Connection closed from remote
13:37:08.095 DEBUG: open62541: Connection 8 | New connection over TCP from 172.16.4.157:4766
13:37:08.096 DEBUG: open62541: Connection 8 | Process a HEL
13:37:08.102 DEBUG: open62541: Connection 8 | Process a OPN
13:37:08.102 DEBUG: open62541: Connection 8 | SecureChannel 14 | OpenSecureChannel: Opened SecureChannel
13:37:08.113 DEBUG: open62541: Connection 8 | Process a MSG
13:37:08.113 DEBUG: open62541: Connection 8 | SecureChannel 14 | Final chunk message
13:37:08.113 DEBUG: open62541: Connection 8 | SecureChannel 14 | Session {152CA78D-6003-027C-F3BF-BB7BEEFEEFBE} created
13:37:09.200 DEBUG: open62541: Connection 0 | SecureChannel 13 | SecureChannel has timed out
```
but i don't think it's chunk-related probleb

**Comment by nikita158** [comment]
@Stasik0 Sorry, didn't notice #708
TeslaScada works

**Comment by Stasik0** [comment]
Nice, which version is working, 1 or 2?

**Comment by jpfr** [comment]
> TeslaScada works

Great! Merged.

**Comment by nikita158** [comment]
@Stasik0 > Nice, which version is working, 1 or 2?
tested only on TeslaScada 2.06.1

**Pull request merged**
