### PR TITLE
Move tests into subdirectories for better organization

### PR DESCRIPTION
**Pull request by Infinity95**
Instead of just throwing every test into a single directory i thought it would be a good idea to organize them reflecting the src directory structure.

### CODE REVIEW

**Comment by Pro** [comment]
Good idea :+1: 
When all the CI issues are fixed we can merge it.

**Comment by Infinity95** [comment]
Was just about to fix the path but you beat me to it :smile:

**Comment by Pro** [comment]
Jep, just fixed another small one, now it should run through, let's see :+1:

**Comment by Infinity95** [comment]
Can you merge this as soon as CI is green (looks like it will be)? I'd like to use this structure for the new unit tests.

**Comment by Pro** [comment]
It looks like travis currently has general problems with OS X. We have to wait and re-trigger a build later...

**Comment by Infinity95** [comment]
Since everything seems to be fine i went ahead and merged this branch into my unit test branch.
Travis being slow again and having problems as usual :smile:

**Comment by Infinity95** [comment]
By the way, it seems travis in general is completely down right now..... See https://travis-ci.org/Infinity95/open62541/builds/299631442?utm_source=github_status&utm_medium=notification for example

**Comment by Pro** [comment]
I think the previous problem is due to the BGP network update: http://status.macstadium.com/incidents/qbvgd7gc7dk2
Let's wait a bit. Your referenced url is something different. Maybe the .gitmodules is corrupt in your commit.

**Pull request merged**
