### PR TITLE
Request committers to sign CLA

### PR DESCRIPTION
**Pull request by Pro**
This PR should not be merged.

Its sole purpose is to ask all previous committers, which did not yet sign the CLA, to sign it.

Here is the list of contributors, which we kindly ask to sign:
@ichrispa has current lines of code: 25135
@Stasik0 has current lines of code: 2346
@uleon has current lines of code: 1869
@lorenzhaas has current lines of code: 176
@ChristianFimmers has current lines of code: 76
@BLeeEZ has current lines of code: 55
@HolgerJeromin has current lines of code: 50
@LEvertz has current lines of code: 48
@jgilje has current lines of code: 31
@ngoossens has current lines of code: 28
@StalderT has current lines of code: 24
@truschival has current lines of code: 23
@pschoppe has current lines of code: 22
@TorbenD has current lines of code: 18
@Wtango has current lines of code: 15
@janitza-luwe has current lines of code: 6
@l29ah has current lines of code: 6
@Root-Core has current lines of code: 5
@Ecosmos has current lines of code: 4
@otronarp has current lines of code: 3
@tbs2017 has current lines of code: 2
@joyhope has current lines of code: 2
@MikeLooijmans has current lines of code: 2
@mmarb has current lines of code: 2
@reza-ebrahimi has current lines of code: 1
@tpiat has current lines of code: 1

If you are in the list, please open the following link and login with your github account, to sign it:
https://cla-assistant.io/open62541/open62541?pullRequest=1170

If you cannot sign the CLA for **technical reasons** leave the following comment to agree to the CLA:
```
I hereby sign the CLA mentioned in https://gist.github.com/7d90e84b0765e7aa9068667e3418ef52
```

If you cannot sign the CLA for other **reasons whatsoever** and you cannot grant us permission to use your contributed code under the current license, please leave a comment and we will try to solve the problem.

### CODE REVIEW

**Comment by Pro** [comment]
Additional users we request to sign:

@mklingn has current lines of code: 22
@NetoLe has current lines of code: 3

**Comment by lorenzhaas** [comment]
Hi, 

in the CLA it is written that "You understand and agree that Eclipse projects and Your contributions are public[...]". Which Eclipse projects? Shouldn't that be "open62541 projects" or what do I miss.

Thanks.

**Comment by Pro** [comment]
@lorenzhaas yes, sorry for the confusion! We based our CLA on the Eclipse CLA. It is fixed now.

**Comment by Stasik0** [comment]
@Pro now everyone ever commited has to sign off again ;)

**Comment by Pro** [comment]
> @Pro now everyone ever commited has to sign off again ;)

Oh, damn it, sorry. Anyways, CLA assistant still has a list of previously signed committers. So if they do not create a new commit, the do not need to sign again.

**Comment by HolgerJeromin** [comment]
Technical a very interesting PR with the fake commits. :)

**Comment by Pro** [comment]
A reminder, from the following people the CLA is still missing:

@ichrispa 
@uleon 
@ChristianFimmers 
@BLeeEZ 
@LEvertz 
@ngoossens 
@l29ah 
@Ecosmos 
@otronarp 
@tbs2017 
@mmarb 
@MikeLooijmans 
@joyhope 
@reza-ebrahimi 
@NetoLe 
@JGrothoff 

We kindly ask you to sign the CLA due to your previous contributions to the open62541 project.
Click on the following link and login with your github account:

https://cla-assistant.io/open62541/open62541?pullRequest=1170

**Comment by HolgerJeromin** [comment]
I (kindly) pushed LEvertz so he has done it. :)

Probably many of them are not active on github so you should try to use another way to contact them.

**Comment by lorenzhaas** [comment]
FYI: "Lykurg" = "lorenzhaas". I renamed my account a while ago and I do not know how such a situation is handled in this CLA-signing process. If you need something, let me know. Cheers.

**Comment by Root-Core** [comment]
@lorenzhaas [You could add the email address - used while committing with your old name - to your current account.](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) Once linked, this should work. If you have not used or used an invalid email address, we might have a problem.

**Comment by jpfr** [comment]
The CLA is a tool to give us more legal certainty on contributions.
To me, the additional level of legal certainty we get from tracking down people who already signed the previous CLA is minimal. I don't see how that would open a legal "attack vector" as the old CLA was practically identical (only typos changed).
New PRs need to be come with the current CLA signed anyway.

But I am not a lawyer. So take this with the usual grain of salt.

**Comment by lorenzhaas** [comment]
@Root-Core Unfortunately it seems that I can't. At least I do not know how, because something is strange here. I made my three little commits with "Lykurg". Then I changed to "lorenzhaas". By github-magic one commit was "re-authored" to "lorenzhaas" (71e9f8003178c8d8be7f3cb7004c2aded372cae5) the other two (941598c6554188016eb90337603b30f598b9ebb2, b9c89634561869ff6665b502658e482c3cef4506) are still "Lykurg" but with an invalid email Lykurg@users.noreply.github.com. Taking into account that my commits are neither big nor important, we can leave it with that. It was just an information that if you are hunting down the last commiters you can take Lykurg off the list :)

(I signed the CLA only with lorenzhaas and haven't changed the user afterwards. Maybe that part was not precisely written in my previous post.)

**Comment by Pro** [comment]
No worries, it's just an additional way of precaution to avoid any legal issues (if there are any). The important thing is that the main contributors sign the CLA.

I used some scripts and github API to extract all the commiters, that's why you (Lykurg) are still in the list. Commits with the email `users.noreply.github.com` are in general commits which were made using the Github web gui (i.e., merges, online changes, ...).

**Comment by Pro** [comment]
I will close this for now since all the major contributors have signed the CLA

**Pull request closed without merging**
