### PR TITLE
[Review] fix(pubsub): Memory fixes

### PR DESCRIPTION
**Pull request by keba-estr**
fix(pubsub): Free memory for sequence number

Memory for sequence number variables has been allocated in
ua_pubsub_networkmessage.c with UA_Variant_setScalarCopy, but not
freed.

fix(pubsub): Symmetric free of WG bufferedMessage

bufferedMessage is initialized in
UA_Server_freezeWriterGroupConfiguration, so it shall be cleared in
UA_Server_unfreezeWriterGroupConfiguration instead of
UA_WriterGroup_clear.

fix(pubsub): Free memory for dataSetPayloadHeader

dataSetWriterIds and dataSetPayload.sizes in payload header are set
irrespective of the variable payloadHeaderEnabled, thus the buffer
also has to be freed independently of this variable.

### CODE REVIEW

**Comment by jpfr** [comment]
Nice!
A few things were discovered by the CI.
```
2022-06-01T21:31:17.5998511Z 48: [1601-01-01 00:02:35.290 (UTC+0000)] [32minfo/eventloop[0m	The EventLoop has stopped
2022-06-01T21:31:17.5998929Z 48: [1601-01-01 00:02:35.290 (UTC+0000)] [32minfo/server[0m	PubSub cleanup was called.
2022-06-01T21:31:17.5999205Z 48: free(): invalid pointer
2022-06-01T21:31:17.8522043Z 48/72 Test #48: check_pubsub_subscribe_rt_levels ............Subprocess aborted***Exception:   1.49 sec
```

Please check that. We can merge once the CI is green.

**Comment by keba-estr** [comment]
> Nice! A few things were discovered by the CI.
> 
> ```
> 2022-06-01T21:31:17.5998511Z 48: [1601-01-01 00:02:35.290 (UTC+0000)] �[32minfo/eventloop�[0m	The EventLoop has stopped
> 2022-06-01T21:31:17.5998929Z 48: [1601-01-01 00:02:35.290 (UTC+0000)] �[32minfo/server�[0m	PubSub cleanup was called.
> 2022-06-01T21:31:17.5999205Z 48: free(): invalid pointer
> 2022-06-01T21:31:17.8522043Z 48/72 Test #48: check_pubsub_subscribe_rt_levels ............Subprocess aborted***Exception:   1.49 sec
> ```
> 
> Please check that. We can merge once the CI is green.

Is there a specific reason why UA_Variant_setScalarCopy or UA_Variant_setScalar is used in different cases?
Please re-run the UNIT tests.

**Comment by keba-estr** [comment]
UA_Server_unfreezeWriterGroupConfiguration is called twice in the failed unit tests (e.g. check_pubsub_subscribe_msgrcvtimeout.c: Test_fast_path): once in the unit test and once in teardown in context of UA_server_delete / UA_PubSubManager_delete. Thus the function must either correctly handle the freeze state to inhibit double free or reset all freed variables to 0 - or both.

**Comment by jpfr** [comment]
Thanks!
I had reworked the original PR a bit. So that the logic can be reused as UA_NetworkMessageOffsetBuffer_clear in multiple places.

**Pull request merged**
