### PR TITLE
fix(server): Add check for EventNotifier attribute value

### PR DESCRIPTION
**Pull request by opcua-tsn-team-kalycito**
- According to 'Table 42 – EventNotifierType Definition' in
   Part 3 Address Space Model specification, the
   'SubscribeToEvents' bit of EventNotifier attribute should be set
   to 1, to subscribe to Events within an object
 - If the condition is true, monitored item can be created, else it
   returns UA_STATUSCODE_BADNOTSUPPORTED status code to the client

Change-Id: Ib6acfed9c1b1c0d84e8061d8f7feb2028d77d7ba

### CODE REVIEW

**Comment by jpfr** [comment]
Looks good. Three small comments. Can be merged when they are resolved.

Use `readWithReadValue` or similar instead of `UA_Server_readEventNotifier`.
You are already in a lock-protected region with multithreading enabled.
`UA_Server_readEventNotifier` would take the lock a second. We deliberately fail that.

The error case warrants an info-log.
Otherwise an unsuspecting user might take a loong time to figure out the problem.

You `return` early in the error case.
The code is simple of you put the error case in an `if`-bracket.
And the continue for the good-case outside of any if/else.

**Comment by opcua-tsn-team-kalycito** [comment]
> Looks good. Three small comments. Can be merged when they are resolved.
> 
> Use `readWithReadValue` or similar instead of `UA_Server_readEventNotifier`.
> You are already in a lock-protected region if thread-safety for multithreading is enabled.
> `UA_Server_readEventNotifier` would take the lock a second. We deliberately fail that.
> 
> The error case warrants an info-log.
> Otherwise an unsuspecting user might take a loong time to figure out the problem.
> 
> You `return` early in the error case.
> The code is simple of you put the error case in an `if`-bracket.
> And the continue for the good-case outside of any if/else.

Thank you for the review comments. We have addressed all the comments and have provided a PR which can be merged into the master.

**Comment by jpfr** [comment]
Nice! Merged.

**Comment by jpfr** [comment]
A question for my understanding.
Does the EventNotifier flag also impact the "blubbling up" of events in the information model?

**Comment by opcua-tsn-team-kalycito** [comment]
> A question for my understanding.
> Does the EventNotifier flag also impact the "blubbling up" of events in the information model?

No. The EventNotifier flag does not impact the creating of events in the information model. It only decides if the generated event in the information model, can be monitored by a client or not.

**Pull request merged**
