### PR TITLE
[Review] feat(server): Add user token signature check for x509 identity token

### PR DESCRIPTION
**Pull request by juangburgos**
To support x509 certificates as user identity tokens, two things are needed:

1) Verify the user token signature (verify user is in possesion of private key).

2) Verify the user token (certificate) is trusted.

This PR implements step 1. Step 2 is left to the library user, to be implemented in the access control plugin.

See issue #3962 for discussion with @jpfr.

NOTE : the library user also needs to add the certificate token policy to the server configuration as follows:

```c
UA_ServerConfig * config = UA_Server_getConfig(server);
UA_AccessControl * ac = &config->accessControl;

// add support for certificate user token (not supported yet by open62541)

// delete old list of supported tokens
UA_Array_delete((void*)(uintptr_t)ac->userTokenPolicies,
	ac->userTokenPoliciesSize,
	&UA_TYPES[UA_TYPES_USERTOKENPOLICY]);
// cerate new list of suported tokens
ac->userTokenPolicies     = NULL;
ac->userTokenPoliciesSize = 3; // support anon, user/pass and certs
ac->userTokenPolicies     = (UA_UserTokenPolicy*)
	UA_Array_new(ac->userTokenPoliciesSize, &UA_TYPES[UA_TYPES_USERTOKENPOLICY]);
// support anonymous
ac->userTokenPolicies[0].tokenType = UA_USERTOKENTYPE_ANONYMOUS;
ac->userTokenPolicies[0].policyId  = UA_STRING_ALLOC(ANONYMOUS_POLICY);
// support username and password
ac->userTokenPolicies[1].tokenType = UA_USERTOKENTYPE_USERNAME;
ac->userTokenPolicies[1].policyId  = UA_STRING_ALLOC(USERNAME_POLICY);
// support certs
ac->userTokenPolicies[2].tokenType = UA_USERTOKENTYPE_CERTIFICATE;
ac->userTokenPolicies[2].policyId  = UA_STRING_ALLOC(CERTIFICATE_POLICY);
// because we added cert support, we need to re-allocate the endpoints
for (size_t i = 0; i < config->endpointsSize; ++i)
	UA_EndpointDescription_deleteMembers(&config->endpoints[i]);
UA_free(config->endpoints);
config->endpoints     = NULL;
config->endpointsSize = 0;
st = UA_ServerConfig_addAllEndpoints(config);
```

### CODE REVIEW

**Comment by jpfr** [comment]
Looks really good!
Have you tested against any other client SDKs?

**Comment by juangburgos** [comment]
Just UaExpert, any other as good?

**Comment by nokem61** [comment]
> Just UaExpert, any other as good?

Prosys OPC UA Browser and SampleClient from OPC Foundation

**Comment by juangburgos** [comment]
> > Just UaExpert, any other as good?
> 
> Prosys OPC UA Browser and SampleClient from OPC Foundation

I have been trying with *Prosys OPC UA Browser* all morning. It is quite bad, cannot even connect. First there is no discovery, have to open UaExpert to get server URL so I can copy back to Prosys. 

Then instance certificate validation is not working. I added both my CA and Server instance certificates into Prosys, and they appear listed:

image

But still I keep getting conneciton error:

image

There is like no log window to give you further information or anything, I give up.

I also tried `Matrikon OPC UA Expert`, and also cannot discover or connect. This time my `open62541` based server sends the warning:

```
"Connection 924 | SecureChannel 42 | The server sends no timestamp in the request header. See the 'verifyRequestTimestamp' setting."
```

image

And finally I was not able to even find where to download the `SampleClient from OPC Foundation`, do you have a link @nokem61 ?

**Comment by jpfr** [comment]
Can we reverse this and connect with an open62541 and certificate authentication to a prosys server?
We might learn about the differences by looking at the (decoded) response.

**Comment by juangburgos** [comment]
@jpfr , the problems I am having with Prosys and Matrikon are not related to this PR. 

In the case of Matirkon I cannot even connect with  `SecurityPolicy#None`.

The open62541 server gives the warning:

```
The server sends no timestamp in the request header. See the 'verifyRequestTimestamp' setting.
```

Matrikon OPC UA Explorer logs:

```
Find Server call for opc.tcp://localhost:4840 failed due to BadNotFound: A requested item was not found or a search operation ended without success.(0x803E0000)
```

In the case of Prosys I can connect with `SecurityPolicy#None`, but with encryption enabled I cannot even browse the security modes or policies supported by the server, because it seems Prosys is not able to validate the server's application instance certificate properly. Eventhough, as I shosed in the screenshots, I have installed the CA properly in the Prosys client.

My guesses; in the case of Matrikon, there is some incompatiblity with open62541, I don't know on which side the issue might be. In the Prosys case, my opnion is that Prosys does not have certificate validation implemented properly.

So in both cases I have not even reached the point of being able to test x509 authorization, because I cannot even connect!

By the way, I also tested node-red OPC UA client and can connect with `SecurityPolicy#None`, but username/password auth does not work. The node-red OPC UA client does not support x509 certs auth, so could not test.

So much for interoperability!

**Comment by nokem61** [comment]
https://opcfoundation.org/developer-tools/samples-and-tools-unified-architecture/net-stack-and-sample-applications/

**Comment by nokem61** [comment]
https://github.com/OPCFoundation/UA-.NETStandard

**Comment by juangburgos** [comment]
@nokem61 thanks for the links, I have tested it, None and Username/Password connection works, but could not test x509 Certs because I cannot find out in the Sample Client where to put the user's Cert and private key. 

It just says `<Browse...>`, and then nothing? See GIF below:

ua_sample

Also I could not find a way to install a CA cert in the Sample Client, but that is a minor issue because at least it allows you to bypass the server cert validation.

**Comment by nokem61** [comment]
Standard path to certs C:\ProgramData\OPC Foundation

https://opcfoundation.github.io/UA-.NETStandard/help/index.htm#ua_sample_client.htm

**Comment by nokem61** [comment]
You probably need to enter the path to the certificate in this field

**Comment by juangburgos** [comment]
Hey @nokem61 , thanks for the links. Still I have not found information on how to achieve x509 cert authorization, tihs requires to set two paths in the client, one for the **certificate** that will be presented to the server, and another path for the **private key**, that the client will use to sign the nonce sent by the server during session activation.

The fact that the Sample Client only has one text line edit for one path does not help. How to I tell the client to use a specific *certificate* **and** *private key*? I tried looking in here:

* <https://opcfoundation.github.io/UA-.NETStandard/help/index.htm#ua_sample_client.htm>

But there is no information on how to set these paths in the `Opc.Ua.SampleClient.Config.xml` file that the Sample Client uses.

On the upside, at least now I managed to make the Sample Client trust my server by validating the server's application instance certificate. 

Still no luck connecting form Matrikon.

I recoreded the procedure for `UaExpert` (**Works**), `Prosys` (**Does not work**) and `Sample Client` (**Works**).

## Server Application Instance Certificate

### UaExpert (Works)

ua_expert_instance_cert

### Prosys (Does not work)

prosys_instance_cert

### Sample Client (Works)

opc_foundation_instance_cert

**Comment by jpfr** [comment]
> The server sends no timestamp in the request header. See the 'verifyRequestTimestamp' setting.

As mentioned in the log output, there is a configuration option for the server where you can set the handling of this problem with some SDKs. The standard is quite clear that this is invalid behaviour.

```c
    /* Rule Handling */
    UA_RuleHandling verifyRequestTimestamp; /* Verify that the server sends a
                                             * timestamp in the request header */
```

The possible options for the setting are:
```c
typedef enum {
    UA_RULEHANDLING_DEFAULT = 0,
    UA_RULEHANDLING_ABORT,  /* Abort the operation and return an error code */
    UA_RULEHANDLING_WARN,   /* Print a message in the logs and continue */
    UA_RULEHANDLING_ACCEPT, /* Continue and disregard the broken rule */
} UA_RuleHandling;
```

**Comment by juangburgos** [comment]
@jpfr thank you for the pointer, now Matrikon can list security policies and modes. It seems Matrikon does not support x509 cert authentication though, it only lists `Anonymous` and `User Details` options, so no good for testing.

I tried at least username/password atuh and it **works** with `Basic256Sha256` but fails with `Aes128_Sha256_RsaOaep`, specifically in `Service_ActivateSession` in the test:

```c
/* Test if the encryption algorithm is correctly specified */
if(!UA_String_equal(&userToken->encryptionAlgorithm,
                   &securityPolicy->asymmetricModule.cryptoModule.encryptionAlgorithm.uri)) {
   response->responseHeader.serviceResult = UA_STATUSCODE_BADIDENTITYTOKENINVALID;
   goto securityRejected;
}
```

`userToken->encryptionAlgorithm` contains `http://opcfoundation.org/UA/security/rsa-oaep-sha2-256ýýýýÝÝÝÝÝÝÝÝÝÝÝ`, while
`securityPolicy->asymmetricModule.cryptoModule.encryptionAlgorithm.uri` contains `http://www.w3.org/2001/04/xmlenc#rsa-oaep`

Is Matrikon not following the standard again in this case? Did I misconfigured something?

Really what I get from all this, is that `UaExpert` is the only decent client out there.

image

**Comment by jpfr** [comment]
> userToken->encryptionAlgorithm contains http://opcfoundation.org/UA/security/rsa-oaep-sha2-256ýýýýÝÝÝÝÝÝÝÝÝÝÝ, while
securityPolicy->asymmetricModule.cryptoModule.encryptionAlgorithm.uri contains http://www.w3.org/2001/04/xmlenc#rsa-oaep

The UserToken can use a different encryption from the SecureChannel.
It is possible that we don't have support for `http://opcfoundation.org/UA/security/rsa-oaep-sha2-256`.

In the plugins folder, I only see `http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep`.

**Comment by juangburgos** [comment]
@jpfr I don't thnk so, because:

1. The server lists only the modes that it supports.

2. `Aes128_Sha256_RsaOaep` works with `UaExpert`.

Actually `UaExpert` sends `http://www.w3.org/2001/04/xmlenc#rsa-oaep` in the `userToken->encryptionAlgorithm`, see below:

user_token

**Comment by jpfr** [comment]
> So if I understand correctly, the client can encrypt the userToken how ever they want regardless of what the server has stated it supports? That confuses me.

That is not what I meant.
The UserToken can be encrypted even though it is transported inside a SecureChannel.
So you can send an encrypted UserToken over an unencrypted SecureChannel.
Or a 256bit encrypted Token over an 128bit SecureChannel.

**Comment by jpfr** [comment]
rebased, streamlined and added to the server config.
this is now ready to be merged.

**Comment by jpfr** [comment]
Finally merged.
Thanks for the code and the patience @juangburgos !

**Pull request merged**
