### PR TITLE
check datasource callback before invoking

### PR DESCRIPTION
**Pull request by Wtango**

### CODE REVIEW

**Comment by jpfr** [comment]
Cool, that looks like a sensible change.
Can you please also change that documentation to match the implemented behavior?

ua_server.h currently says
```c
/**
 * Datasources are the interface to local data providers. It is expected that
 * the read and release callbacks are implemented. The write callback can be set
 * to null.
 */
```

**Comment by Stasik0** [comment]
Yes, this is cool :) A unit-test to test this feature, or don't you have the time?

**Comment by Wtango** [comment]
Unit-test is added.

**Comment by jpfr** [comment]
Thanks @Wtango!

**Pull request merged**
