### PR TITLE
fix possible infinity loops and add a unit test unit

### PR DESCRIPTION
**Pull request by StalderT**

### CODE REVIEW

**Comment by StalderT** [comment]
Can maybe fix SecureChannel_timeout_fail test. I will try to reactivate the test if all green.

**Comment by StalderT** [comment]
I think we must add ```connection->close(connection);``` here

https://github.com/open62541/open62541/blob/dfc2543739e19e2ae86d875e4d3c7ae4adaaf49c/plugins/ua_network_tcp.c#L200-L203

@jpfr @Pro do you agree ?

**Comment by Pro** [comment]
@StalderT  thanks for the hint about `--track-fds=yes`.
I added a new PR which enables this. See #1395
That PR also includes all the necessary close calls so that no connection remains open

**Comment by StalderT** [comment]
What is the best way to force Travis/AppVeyor to rebuild?

**Comment by Pro** [comment]
@StalderT only we (admins) can force Travis/Appveyor to requild. If you really really need to force a new build you could e.g. rebase your branch on master, or if it is already up to date then push a new commit to your branch.

The better way would be if you enable Travis and Appveyor for your own fork and then you develop your features first only in your fork where you can restart Travis/Appveyor on your own, and when all is green you can create a PR.

**Comment by StalderT** [comment]
@Pro Ok thanks. I understand. Do you know where can I activate Appveyor / Travis in my fork.

**Comment by Pro** [comment]
It's the same as adding a normal project:

https://stackoverflow.com/questions/26343492/test-a-forked-github-project-by-travis

https://www.appveyor.com/docs/

**Comment by StalderT** [comment]
for me you can merge

**Pull request merged**
