### PR TITLE
[Review] Allow binding a listening socket before the network interface is configured

### PR DESCRIPTION
**Pull request by dbeinder**
Fixes https://github.com/open62541/open62541/issues/5709, please see the issue for a detailed description of the problem and proposed change

### CODE REVIEW

**Comment by dbeinder** [comment]
The CI test failed due to a corrupted linked list?

```

2023-04-06T12:43:47.5962956Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	Start import nodeset: /home/runner/work/open62541/open62541/deps/ua-nodeset/DI/Opc.Ua.Di.NodeSet2.xml
2023-04-06T12:43:47.6002857Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported ReferenceTypes: 3
2023-04-06T12:43:47.6007370Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported DataTypes: 7
2023-04-06T12:43:47.6007823Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported ObjectTypes: 40
2023-04-06T12:43:47.6008283Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported VariableTypes: 2
2023-04-06T12:43:47.6008725Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported Objects: 81
2023-04-06T12:43:47.6009357Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported Methods: 45
2023-04-06T12:43:47.6027087Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported Variables: 234
2023-04-06T12:43:47.6027739Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	imported Views: 0
2023-04-06T12:43:47.6045971Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	Start import nodeset: /home/runner/work/open62541/open62541/deps/ua-nodeset/PNRIO/Opc.Ua.PnRio.Nodeset2.xml
2023-04-06T12:43:47.6065230Z 67: corrupted double-linked list
2023-04-06T12:43:47.9498807Z 67/72 Test #67: check_nodeset_loader_ua_nodeset ................Subprocess aborted***Exception:  16.40 sec
```

**Comment by jpfr** [comment]
Funny. Retriggered the failing test.

**Comment by dbeinder** [comment]
Same crash happened again - since my change is fairly minimal, this almost has to be another bug getting triggered due to timing?
```
2023-04-06T14:33:19.4019466Z 67: [1601-01-01 00:02:35.290 (UTC+0000)] debug/userland[0m	Start import nodeset: /home/runner/work/open62541/open62541/deps/ua-nodeset/PNRIO/Opc.Ua.PnRio.Nodeset2.xml
2023-04-06T14:33:19.4040492Z 67: corrupted double-linked list
2023-04-06T14:33:19.6087757Z 67/72 Test #67: check_nodeset_loader_ua_nodeset ................Subprocess aborted***Exception:  16.52 sec
```

**Comment by jpfr** [comment]
The PR should be green when you rebase on the current master.

**Comment by jpfr** [comment]
Nice. Merged.

**Pull request merged**
