### PR TITLE
First Changes for freeRTOS

### PR DESCRIPTION
**Pull request by cabralfortiss**
An adaptation of the code to freeRTOS OS using LwIP stack. It was tested with LwIP 2.0.3 and worked partially (the opcua server became unstable after many nodes were added, but the problem was on the heap management, and wans't solved yet). 
Related to pull request #1160 and issue #1149

### CODE REVIEW

**Comment by jpfr** [comment]
Nice! This looks good!

We now support Windows/Linux/MacOS/BSDs/vxWorks/QNX/FreeRTOS.

On the other hand, it becomes difficult to understand the nested ifdefs.
The plugins seem to have reached a point where they "break under their own weight".
The API to the server is pretty stable.
Imho we should start implementing architecture ports in separate files.

@cabralfortiss Can you just copy the three plugins you ported into separate files?
These can then be lwip only and remove a lot of the macro-magic.
`/plugins/ua_networklayer_tcp_lwip.c`
`/plugins/ua_networklayer_udp_lwip.c`
`/plugins/ua_clock_freertos.c`

Then cmake can select the correct source file based on the architecture.
@open62541/open62541-core Are you okay if we adapt the source structure in this way?

@cabralfortiss 
Is it possibe to compile for Linux against FreeRTOS as a library or simulator?
Then we can add continuous integration for the FreeRTOS port.

**Comment by Stasik0** [comment]
Any ideas how to get it into ci?

**Comment by cabralfortiss** [comment]
Hi. regarding the new files for the freeRTOS in the plugin folder, I also agree that the defines are getting uglier and uglier. But I noticed that the worst part is in the includes and defines at the top of them. Would be a good idea to have a header file with all \#incluedes and \#defines for each architecture with the same same but in different folders? For example, a plugins/general/ua_arch.h and plugins/freertos/ua_arch.h files with all necessary includes and defines for each architecture. Then, in CMake, include folder plugins/general OR plugins/freertos. And where needed, just included <ua_arch.h>.

plugins/general could also be then subdivided in WIN32 and posix separate folders.

**Comment by HolgerJeromin** [comment]
In the past (2015ish) we had code like this
```
#ifndef UA_free
#define UA_free(ptr) free(ptr)
#endif
```
That way a user can overwrite the memory management without changing our code...
https://github.com/open62541/open62541/commit/e62e5a409fbf62472c76bdb6731a7b887120e718

This looks much cleaner and flexible.

**Comment by cabralfortiss** [comment]
I'm not sure if I understand exaclty what the relation of my comment to yours. I just meant to put all defines and include in a separate ua_arch.h file and include that file. If a new architecture doesn't have a proper ua_arch.h file (for example a missing include, or doesn't have a  ioctl function), the compilation will fail.

**Comment by HolgerJeromin** [comment]
> I'm not sure if I understand exaclty what the relation of my comment to yours.

an architecture does not need to define everything, but only special stuff. This way an architecture could be easier to keep up to date.

**Comment by cabralfortiss** [comment]
Exactly. I meant to put in this new file only what now is already behind the architecture definition (UA_FREERTOS in this case)

**Comment by Stasik0** [comment]
http://www.ovpworld.org/about_continuous_integration

Here a ci proposal

**Comment by jpfr** [comment]
👍 for an ua_arch_freertos.h file.
Maybe we can resurrect the `/ports` folder.

For networking, if there is still a big overlap, is it maybe sensible to split the implementation?
`ua_networking_generic.c`
`ua_networking_posix.c`
`ua_networking_lwip.c`

The clock port is a 100% replacement. So it cold live in a separate file.

**Comment by cabralfortiss** [comment]
I like the idea and the direction where this is going. The cleanest way of doing platform-independent I think is to have all hardware related functions in their own folder. Each folder can have its own CMakefile that adds the files to the list to compile when a variable in CMake selected the platform. So in the main CMakefile you just select the platform on a variable. I'm not sure about copying a file to ${BUILD_DIR}/ua_arch.h since I never did that in CMake, but I find #include <ua_arch.h> easier. 

Since the port change I think will be a big one, maybe it would be better to have in another branch (I think), so what should I do with this pull request? I just want to add that I have another commit for cleaning before this request is merged.

**Comment by jpfr** [comment]
>  I'm not sure about copying a file to ${BUILD_DIR}/ua_arch.h since I never did that in CMake, but I find #include <ua_arch.h> easier.

It would be cool if users would no need to modify their code once cmake did its thing.
We can include ua_arch.h from ua_config.h which is also generated/copied by cmake.

> Since the port change I think will be a big one, maybe it would be better to have in another branch

Ok. Tell us when you are ready and we merge this first.

**Comment by StalderT** [comment]
Just a question. With this method, will we still have a single amalgated file (open62541.c/h) containing all the platforms or will we have one file per platform?

**Comment by cabralfortiss** [comment]
This is now ready to be merged

**Comment by jpfr** [comment]
Cool. Just two minor things.
- Can `UA_freeRTOS` in the cmake script be renamed to all-uppercase? For consistency.
- Is it necessary to have `../deps/queue.h`? Normally, cmake should have added /deps to the include directories.

**Comment by cabralfortiss** [comment]
I'll change the UA_freeRTOS to all uppercase.

The problem with queue.h is that in freeRTOS there's also a file called queue.h so there are problems in including and a really mess. By including directly the deps/queue.h the queue.h in freeRTOS is properly included when needed.

**Comment by jpfr** [comment]
Merged. 😄

**Comment by Pro** [comment]
Regarding the architecture structure discussion:
In FORTE (https://www.eclipse.org/4diac/en_rte.php) we are already using different folders for architecture dependent code. 
The arch folder contains independent code, whereas all the subfolders implement it for the corresponding platform. See here:
https://git.eclipse.org/c/4diac/org.eclipse.4diac.forte.git/tree/src/arch?h=develop

Adding a new architecture will automatically extend the options for CMake, and in CMake you can then select which architecture you are using. This will then also work with Amalgamation.

I'm currently doing some experiments with open62541 and Arduino, and started to propose a similar structure for open62541 here, more on that later
https://github.com/Pro/open62541/commit/2212f0c6e7ac16cc4ecf58dd4104a43407099344

**Pull request merged**
