### PR TITLE
Add parentNodeContext to the createOptionalChildCallback

### PR DESCRIPTION
**Pull request by ja4nm**

### CODE REVIEW

**Comment by ja4nm** [comment]
Connected issue: https://github.com/open62541/open62541/issues/1733

**Comment by jpfr** [comment]
The nodeid of the parent is passed.
You can use that to load the parents context from inside the callback.
So this breaking change doesn’t give us functionality  we don’t already have.

Please close if the issue is resolved.

**Comment by ja4nm** [comment]
The issue can be resolved the way you have suggested.
However, all the other callbacks contain both the nodeId and context parameter, so I thought it would be nice to be consistent.

**Comment by jpfr** [comment]
There are different node contexts to consider.
The parent, the new source node, etc.
If this was a new API, yes having the context is a good idea.
But since this API is already used in the wild, let's keep it stable if it is just a little effort to get the context manually.

Btw, `UA_NODESTORE_GET` needs to be matched with `UA_NODESTORE_RELEASE`.

It's good to see so many suggestions for the stack from you.

**Comment by ja4nm** [comment]
Okay, than I am closing the PR. Thanks for your input.

**Pull request closed without merging**
