### PR TITLE
add connectivity check background task 

### PR DESCRIPTION
**Pull request by StalderT**
When #1497 will be merged.

According to the specification, periodically reading the State Variable

image

### CODE REVIEW

**Comment by StalderT** [comment]
Can not be a part of 0.3?

**Comment by Pro** [comment]
Yes, it can be, if we manage to merge #1497 within the next two weeks, this one should be easy to merge.

**Comment by StalderT** [comment]
> Yes, it can be, if we manage to merge #1497 within the next two weeks, this one should be easy to merge.

Thanks !

**Comment by StalderT** [comment]
replaced by #1598

**Pull request closed without merging**
