### PR TITLE
Fix #2394: Remaining memory leak with asynchronous connect

### LINKED ISSUE #2394: Remaining memory leak with asynchronous connect
Issue #2295 has not been entirely fixed. I still get two blocks of memory marked "definitely lost" with the latest version of open62541. To reproduce, create the following files:

CMakeLists.txt

```
cmake_minimum_required(VERSION 3.0)

include(ExternalProject)

ExternalProject_Add(
  external_open62541
  GIT_REPOSITORY "https://github.com/open62541/open62541.git"
  GIT_TAG "fe01551f83df6f2b466a17e7695d78640ded6289"
  CMAKE_CACHE_DEFAULT_ARGS -DUA_ENABLE_AMALGAMATION:BOOL=ON
  INSTALL_COMMAND ""
)

ExternalProject_Get_Property(external_open62541 binary_dir)
set(OPEN62541_LIBRARY open62541)
set(OPEN62541_LIBRARY_PATH ${binary_dir}/bin/${CMAKE_FIND_LIBRARY_PREFIXES}${OPEN62541_LIBRARY}.a)
add_library(${OPEN62541_LIBRARY} UNKNOWN IMPORTED)
set_property(TARGET ${OPEN62541_LIBRARY} PROPERTY IMPORTED_LOCATION ${OPEN62541_LIBRARY_PATH})
set_property(TARGET ${OPEN62541_LIBRARY} PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${binary_dir})
add_dependencies(${OPEN62541_LIBRARY} external_open62541)

add_executable(memory_leak_demo memory_leak_demo.c)
set_property(TARGET memory_leak_demo PROPERTY C_STANDARD 99)
target_link_libraries(memory_leak_demo ${OPEN62541_LIBRARY})
```

memory_leak_demo.c

```
#include <stdio.h>
#include <unistd.h>
#include <sys/wait.h>
#include <open62541.h>

static void
onConnect (UA_Client *client, void *userdata, UA_UInt32 requestId, void *status) {
    printf ("Async connect returned with status code %s\n",
            UA_StatusCode_name (*(UA_StatusCode *) status));
}

static void clientProcess() {
    UA_Client *client = UA_Client_new(UA_ClientConfig_default);
    const char* uri = "opc.tcp://localhost:4840";
    const int iterations = 20;

    for (unsigned int i = 0; i < iterations; i++) {
        UA_Client_connect_async(client, uri, onConnect, NULL);
        UA_Client_run_iterate(client, 0);
        usleep(250000);
    }

    UA_Client_delete(client);
}

static void serverProcess() {
    UA_ServerConfig* config = UA_ServerConfig_new_default();
    UA_Server* server = UA_Server_new(config);
    UA_Server_run_startup(server);

    // Run the server for 100 iterations = 5 seconds.
    for (int i = 0; i < 100; i++) {
        UA_Server_run_iterate(server, true);
    }

    UA_Server_run_shutdown(server);
    UA_Server_delete(server);
    UA_ServerConfig_delete(config);
}

int main() {
    if (fork()) {
        clientProcess();
        waitpid(-1, NULL, 0);
    } else {
        // Delay before starting the server process.
        sleep(2);
        serverProcess();
    }
    return 0;
}
```

Put the files side by side in a directory, and run

```
mkdir build
cd build
cmake ..
make
valgrind ./memory_leak_demo
```

Valgrind report:

```
==11313== 
==11313== HEAP SUMMARY:
==11313==     in use at exit: 0 bytes in 0 blocks
==11313==   total heap usage: 3,025 allocs, 3,025 frees, 1,462,154 bytes allocated
==11313== 
==11313== All heap blocks were freed -- no leaks are possible
==11313== 
==11313== For counts of detected and suppressed errors, rerun with: -v
==11313== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==11312== 
==11312== HEAP SUMMARY:
==11312==     in use at exit: 288 bytes in 4 blocks
==11312==   total heap usage: 202 allocs, 198 frees, 947,775 bytes allocated
==11312== 
==11312== 288 (160 direct, 128 indirect) bytes in 2 blocks are definitely lost in loss record 2 of 2
==11312==    at 0x4C2DBB6: malloc (vg_replace_malloc.c:299)
==11312==    by 0x4707BE: UA_ClientConnectionTCP_init (open62541.c:51766)
==11312==    by 0x45CEF5: UA_Client_connect_async (open62541.c:43843)
==11312==    by 0x403FDE: clientProcess (in /home/alajovic/tmp/async-problem/build/memory_leak_demo)
==11312==    by 0x4040A3: main (in /home/alajovic/tmp/async-problem/build/memory_leak_demo)
==11312== 
==11312== LEAK SUMMARY:
==11312==    definitely lost: 160 bytes in 2 blocks
==11312==    indirectly lost: 128 bytes in 2 blocks
==11312==      possibly lost: 0 bytes in 0 blocks
==11312==    still reachable: 0 bytes in 0 blocks
==11312==         suppressed: 0 bytes in 0 blocks
==11312== 
==11312== For counts of detected and suppressed errors, rerun with: -v
==11312== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

The first part of the report (PID 11313) is for the server process – no leaks there – and the second (PID 11312) is for the client. 160 bytes in 2 blocks appear to be lost.

_Adapted from a post originally posted by @alajovic in https://github.com/open62541/open62541/issues/2295#issuecomment-454811714_

### PR DESCRIPTION
**Pull request by mlgiraud**
Please merge #2482 first

Fixes #2394

### CODE REVIEW

**Comment by Pro** [comment]
@Infinity95 #2482 is merged. Can you rebase and fix this PR so we can merge it?

**Comment by Infinity95** [comment]
@Pro I don't think i can fix this with the current networking code. There seem to be some memory issues with the "fix" and i don't see how i can fix them without rewriting major parts of the code.
Since the networking code will be discarded anyway, as soon as my other PR lands, i don't think it's worth the time.

**Comment by Pro** [comment]
So should we close this PR without merge?

**Comment by Pro** [comment]
@mlgiraud ping.
What should we do with this PR?

**Comment by mlgiraud** [comment]
I would close the PR, since I have absolutely no idea what is causing the problem.
Since the issue is already solved in my networking overhaul afaik I don't see the benefit of fixing this separately.

**Comment by jpfr** [comment]
Async connect was fully refactored.

**Pull request closed without merging**
