### PR TITLE
Try to fix random appveyor build fails

### PR DESCRIPTION
**Pull request by Pro**
Hopefully this fixes random fails on AppVeyor. Let's see what the result of this PR shows...

### CODE REVIEW

**Comment by jpfr** [comment]
Appveyor failed...
Funny.

**Comment by Pro** [comment]
All green!
Looks like multithreaded compilation causes problems with msbuild. Maybe the project dependencies are not set correctly when cmake is used to create VS projects and thus two simultaneous compilations overwrite the same file.

**Comment by jpfr** [comment]
Nice!
This was a nuissance for a long time.

**Comment by Stasik0** [comment]
btw, could you include creation of a .dll into appveyor builds?

**Comment by Pro** [comment]
@Stasik0 see #1039 for .dll builds on appveyor

**Pull request merged**
