### PR TITLE
(nc) Fixed generation of nested strctures values. Added support for generating Guid values

### LINKED ISSUE #4900: Nodeset Compiler Issue: Value of a Structure containing an Array of Structures.
## Description
The generated code won't compile for a variable that has a value of a custom Structure DataType, which contains an array of Structures.

Test code (including a sample nodeset):
https://github.com/MurzynJ/open62541/tree/NcIssue_NestedArrayOfStructures

Example:
image
image

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): Latest master: b061554990ab38cd9062212aaa69c322f1415f33
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by MichalTyndel**
Fixes #4900

### CODE REVIEW

**Comment by Fischer-Thomas** [comment]
I tried to compile the tests but i´m getting some errors. 
I use ubuntu 20.04 and gcc 10.3.

`In file included from /home/dev/workspace/open62541/arch/posix/ua_architecture.h:13,
                 from /home/dev/workspace/open62541/build/src_generated/open62541/config.h:147,
                 from /home/dev/workspace/open62541/include/open62541/types.h:19,
                 from /home/dev/workspace/open62541/include/open62541/util.h:11,
                 from /home/dev/workspace/open62541/include/open62541/server.h:20,
                 from /home/dev/workspace/open62541/build/src_generated/tests/namespace_tests_testnodeset_generated.h:11,
                 from /home/dev/workspace/open62541/build/src_generated/tests/namespace_tests_testnodeset_generated.c:4:
/home/dev/workspace/open62541/build/src_generated/tests/namespace_tests_testnodeset_generated.c: In function ‘function_namespace_tests_testnodeset_generated_14_begin’:
/home/dev/workspace/open62541/build/src_generated/tests/namespace_tests_testnodeset_generated.c:442:26: error: ISO C forbids zero-size array ‘arrayDimensions’ [-Werror=pedantic]
  442 | UA_STACKARRAY(UA_UInt32, arrayDimensions, 0);
      |                          ^~~~~~~~~~~~~~~
/home/dev/workspace/open62541/include/open62541/architecture_definitions.h:117:48: note: in definition of macro ‘UA_STACKARRAY’
  117 | #  define UA_STACKARRAY(TYPE, NAME, SIZE) TYPE NAME[SIZE]`

**Comment by MichalTyndel** [comment]
> I tried to compile the tests but i´m getting some errors.
> I use ubuntu 20.04 and gcc 10.3.

Good catch. I had UA_FORCE_WERRORUA_FORCE_WERROR cmake option disabled. Latest commit fixes this issue.

**Comment by jpfr** [comment]
Nice!

@andreasebner please review for merging.

**Comment by jpfr** [comment]
Also, please rebase for the 1.3 branch.
This should be in the next release.

**Comment by andreasebner** [comment]
Looks great! Since @NoelGraf worked on the latest nodeset-compiler and value generation tasks i forward the deep review to him. @NoelGraf could you please make a review?

**Comment by NoelGraf** [comment]
@andreasebner Looks good! Can be merged.

**Comment by andreasebner** [comment]
The changes look great! Since the target branch changes to 1.3., it would be nice if you can rebase your changes to 1.3.

**Comment by MichalTyndel** [comment]
@andreasebner now it's based on 1.3.

**Comment by jpfr** [comment]
Cool. Merging when the CI clears.

**Pull request merged**
