### PR TITLE
fix #1230

### LINKED ISSUE #1230: reconnecting timeout
Description
===========
By removing cable between OPC-UA server and client the data won't be sent. The reconnecting function in the example runs client_connect but stays in this method for about 70 seconds before starting a new connection. 

Using the pause and resume button the connection will be restored immediately after the resume button has been pressed.

[connection timeout.pcapng.zip](https://github.com/open62541/open62541/files/1336315/connection.timeout.pcapng.zip)

Background Information / Reproduction Steps
===========================================
Windows 10 virtual machine with B&R simulator which runs the OPC-UA server, also tried with proses simulation server. Same problem.
Mac with open62541 client, example code: client loop connect.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3
 - [x] Other OPC UA SDKs used (client or server): Prosys simulation server, B&R simulator
 - [x] Operating system: Windows 10 and Os X
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by StalderT**

### CODE REVIEW

**Comment by jpfr** [comment]
You want to handle timeouts of up to 1 ms differently?

**Comment by StalderT** [comment]
With this commit https://github.com/open62541/open62541/commit/e5f33bb7b436f748d5891b18688e6c41179b3cec, client never detect connection lost  with server and always return UA_STATUSCODE_GOODNONCRITICALTIMEOUT

**Comment by StalderT** [comment]
timeouts <1 ms = expired ?

**Comment by StalderT** [comment]
Do you agree ? What must we make for UA_Client_Service_publish ? See https://github.com/open62541/open62541/issues/1332

**Pull request closed without merging**
