### PR TITLE
fix bug what case segment fualt when writing to a readonly value

### PR DESCRIPTION
**Pull request by Wtango**

### CODE REVIEW

**Comment by Stasik0** [comment]
Cool stuff!  Feel free to write a corresponding unit test if you like to.

**Comment by Wtango** [comment]
I'd like to,but i really new about test.How can i do?

**Comment by Stasik0** [comment]
okay, first look into how or unit tests are built up: https://github.com/open62541/open62541/tree/master/tests

look into this file from this line: https://github.com/open62541/open62541/blob/master/tests/check_services_attributes.c#L584

You will need to create a write request like the one you found the bug, you will may need to add a node that is not writable in the function ```makeTestSequence()``` that is bootstrapping the test server.

did it help?

**Comment by Wtango** [comment]
Is there any problem and not to be merged?

**Comment by Stasik0** [comment]
no, i just thought you wanted to add a unit test.

**Comment by HolgerJeromin** [comment]
He did :)

**Comment by Stasik0** [comment]
@Wtango sorry, i did not notice your test -- got no email, eveything is fine! Feel free to add more tests if you would like to!

**Comment by Wtango** [comment]
@Stasik0 Tests for DataSource or any other?I'm glad to contribute to this project.

**Comment by Stasik0** [comment]
@Wtango yes, you can track the coverage here https://coveralls.io/builds/4576939?all=true just look what is not yet covered, what can be tested with less effort and, of course, where you have fun

**Pull request merged**
