### PR TITLE
Removal of liburcu (userspace-rcu)

### PR DESCRIPTION
**Pull request by janitza-thbe**
Completely removed `liburcu`.
Replaced rcu-queues by usage of native queues from `queue.h` that are secured by mutexes.

### CODE REVIEW

**Comment by jpfr** [comment]
Nice! Some code broke, but its not a big problem.

> /home/travis/build/open62541/open62541/src/server/ua_services_discovery.c:464:9: error: implicit declaration of function ‘uatomic_add_return’ [-Werror=implicit-function-declaration]
> server->registeredServersSize = uatomic_add_return(&server->registeredServersSize, -1);

We define internal definitions for atomic aoperations in /src/ua_util.h.
E.g. UA_atomic_add

**Comment by janitza-thbe** [comment]
Ah yes, sorry for that!
I already harmonised that using the idea of the existing `UA_Atomic_add` function
 Didn't realise that these were connected. I'll do the changes here later.

**Comment by jpfr** [comment]
> This branch cannot be rebased due to conflicts

Sorry, some other change conflicts the merge.
This can be merged otherwise.

**Comment by janitza-thbe** [comment]
Travis needs to be retriggered due to internal connections problems that induced build failures.

**Comment by Pro** [comment]
done

**Pull request merged**
