### PR TITLE
Avoiding conditional directives that split up statements.

### PR DESCRIPTION
**Pull request by RomeroMalaquias**

### CODE REVIEW

**Comment by RomeroMalaquias** [comment]
Ok, sorry for that.
Fixing it

**Comment by Stasik0** [comment]
okay, this seems to be a non-functional coding-style issue @jpfr, @FlorianPalm what do you think?

**Comment by RomeroMalaquias** [comment]
Hi @Stasik0,
It is only aesthetic refactoring, that compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

**Comment by Stasik0** [comment]
+1 on that in this case

**Pull request merged**
