### PR TITLE
speedup namespace compiler

### PR DESCRIPTION
**Pull request by markusgraube**
reordering of nodes takes quite a big amount of time when also including
all nodes from ns0. Thus, first remove all ignored nodes will make the
sorting much faster

@ichrispa can I do this or are there some side effects?

### CODE REVIEW

**Comment by Stasik0** [comment]
@markusgraube IT seems to work, but I did not notice any speedup - is it really faster? I do not mind if we merge, though.

**Comment by markusgraube** [comment]
@Stasik0 It is only for `UA_BUILD_EXAMPLES_NODESET_COMPILER`. Then it should be faster. For me it reduces the namespace compiler time for server_nodeset.xml from around 70 sesconds to 30 seconds.

**Comment by Stasik0** [comment]
@markusgraube okay, namespace compiler is a black-box for me, probably you or @ichrispa can decide at best what to merge and what not

**Comment by Stasik0** [comment]
@markusgraube okay, same here down from 70 to 30 secs, @ichrispa you okay with the code? Changes seem to be trivial

**Comment by Stasik0** [comment]
it seems that the topological sorting is one of the bottlenecks... can't we use some heuristics like this one? http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.47.7745 it is dead-simple to implement, however it is unclear for me what the "edges" actually are. Are these references with isForward flag?

**Comment by markusgraube** [comment]
@Stasik0 Nice idea to fasten the sort algorithm itself.

However, your cited paper is about a FAS problem (feedback arc set), isn't it? I thought, we just need a topologic sort since the `HasTypeDefinition` and `HasSubtype` relations should already be an DAG (directed acyclic graph), shouldn't they?

But it seems that the current algorithm can be improved for example by Kahn's algorithm (https://en.wikipedia.org/wiki/Topological_sorting). Or we just take an existing implementation https://pypi.python.org/pypi/topological_sort or https://pypi.python.org/pypi/toposort/1.0

or just follow a python recipe: https://algocoding.wordpress.com/2015/04/05/topological-sorting-python/

**Comment by Stasik0** [comment]
@markusgraube okay, that is correct it thought the sorting considers all relations e.g. Ogranizes aswell, by the way, the xml nodesets coming from UaModeller seem already to be sorted, so no reorganization is needed

**Comment by markusgraube** [comment]
Okay. I think we can close this and continue completely in #725

**Pull request closed without merging**
