### PR TITLE
fix(tools): fix compilation for Microsoft C

### PR DESCRIPTION
**Pull request by RolfKal**
Microsoft C does not have a unistd.h header for the ssize_t data type

### CODE REVIEW

**Comment by jpfr** [comment]
Looks good.
Please ensure all CI tests are green.

**Comment by RolfKal** [comment]
> Looks good. Please ensure all CI tests are green.

Both failures seem to be due to tests not terminating within their allocated timeout. I have no idea how to fix that, nor which of my almost cosmetical changes could cause that.

The only real fix in this is a borked macro to UA_LOCK_ASSERT with the last commit, that completely disallowed compilation of project with SKS enabled. The first fix cleans up Microsoft header specialties and shouldn't have any effect on Linux compilation nor running of the unit tests. The last is a cosmetic fix to make the conditional macros the same as in master.

**Comment by jpfr** [comment]
Rerunning failed jobs.

**Comment by RolfKal** [comment]
> Rerunning failed jobs.
Is there any idea what is the problem? The CI toolchain for the 1.4 branch seems somehow broken.

**Comment by jpfr** [comment]
grafik

**Comment by RolfKal** [comment]
> grafik

I see that, but according to my understanding, that test can't even compile with current 1.4 as in the repository!

**Comment by RolfKal** [comment]
It seems to me you find the culprit that made the tests fail! Great!

**Comment by jpfr** [comment]
Nice, thanks for the work.

**Pull request merged**
