### PR TITLE
Generate nodemacros

### PR DESCRIPTION
**Pull request by truschival**
Minor fix in CMakelists.

Add a rudimentary replacement function to avoid issue #578. The resulting identifiers are not guaranteed to be unique.

Please review!

### CODE REVIEW

**Comment by Stasik0** [comment]
@truschival could you please squash the commits https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by jpfr** [comment]
@Stasik0 That's not necessary any more.
Commits can now be squashed by github. There's a button in the merge GUI.

**Comment by jpfr** [comment]
Thanks for the PR @truschival!

**Comment by HolgerJeromin** [comment]
> There's a button in the merge GUI.

Wow, I suggested that github a while ago. :-)

**Comment by truschival** [comment]
@Stasik0 & @jpfr : I deliberately did not squash all commits. I generated 2 distinct commits to make it apparent that the PR treated two different aspects (fix #581) plus a quick hack for the CMakeLists.txt.
Anyway, thanks for the merge!

**Pull request merged**
