### PR TITLE
[Review] Config: Add custom logger initialization when creating server config

### LINKED ISSUE #1836: Unable to set logger when creating server
Consider the following code (from the tutorial examples):

```cpp
UA_Boolean running = true;
UA_ServerConfig *config = UA_ServerConfig_new_default();
config->logger = &my_fancy_logging_function;
UA_Server *server = UA_Server_new(config);
UA_Server_run(server, &running);
// ...
```

I want to set a custom logging function (`my_fancy_logging_function`).

This is not possible since `UA_ServerConfig_new_default()` already uses `UA_Log_Stdout` to initialize the network layer. So setting `config->logger` after `UA_ServerConfig_new_default()` doesn't have any effect.

Is this a known flaw? Does this exceed the "default" config and so I need generating my own config manually?

References: https://github.com/open62541/open62541/issues/1139, https://github.com/open62541/open62541/pull/1566, https://github.com/open62541/open62541/pull/1641, @janitza-thbe, @jpfr, @Pro

### LINKED ISSUE #2132: Need a logger parameter added to all the UA_ServerConfig create functions
Description
===========
If you use a custom logger function you potentially miss log calls generated inside any of the `UA_ServerConfig` create functions.

Background Information
===========================================
The problem is that when calling a `UA_ServerConfig` create function e.g. `UA_ServerConfig_new_minimal()`  the `conf->logger` field is set to the default logger function internally which then may be called multiple times before the create function returns.

This field can only be updated **after** the create function returns
`conf->logger=my_logger;`

To fix this a logger parameter must be  added to all the `UA_ServerConfig` create functions.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version: 0.3-rc2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: All
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by Pro**
Fixes #1836 and fixes #2132

### CODE REVIEW

**Comment by jpfr** [comment]
I agree that we need to work in issue #2132.

But it would be unwise to let the config-creation functions go the way of the crappy Win32-API.
With many many arguments that are mostly left to NULL.
Where do we stop adding more arguments for possible configuration-items?

Can we encourage people to make changes to the returned config?
We could have a UA_ServerConfig_setLogger.
But that is overkill. Since everybody can just set the variable.

**Comment by Pro** [comment]
> Can we encourage people to make changes to the returned config?
> We could have a UA_ServerConfig_setLogger.
> But that is overkill. Since everybody can just set the variable.

I agree with you, that users should use the returned config. The problem is, that within that method, the network layers for example already use the logger which is created by the default config. So there is currently no way to change the logger, e.g., to a file logger and log all the messages, including the network layer output.

Otherwise we need to think of a two way configuration step, where we firstly only return the default config, the user can then change the config, and then we initialize the network layers. With this we can also put the buffer size into the config, without passing it as a parameter.

**Comment by jpfr** [comment]
Okay. I agree with you.
Let's talk about a config overhaul when 0.3 is out.

**Comment by Pro** [comment]
Closing in favour of #2263

**Comment by Pro** [comment]
Closing this in favour of #2263 which correctly handles the logger initialization also for the network layer

**Pull request closed without merging**
