### PR TITLE
fix: Fixed Zephyr example and introduced CI

### PR DESCRIPTION
**Pull request by xR3b0rn**
Fixed bugs introduced in the "cleaned up" [PR](https://github.com/open62541/open62541/pull/6792) by reverting some of the changes. The original PR can be found [here](https://github.com/open62541/open62541/pull/6741).

### CODE REVIEW

**Comment by xR3b0rn** [comment]
@jpfr I now fixed the example and the Zephyr integration while keeping the adapted folder structure (without the top level zephyr folder). To avoid regressions, I added a CI for building the Zephyr server example.

**Comment by jpfr** [comment]
Nice, looks good.
The Zephyr build throws a few warnings (which we would abort on for the other architectures).
But nothing scary at the moment.

If you want to keep the current commit history, please use the commit line prefixes `fix(arch)`, `feat(ci)`, etc. described here:
https://github.com/open62541/open62541/blob/master/CONTRIBUTING.md

Otherwise I can squash-merge the entire PR as `feat(ci): Add CI build for Zephyr`.

Thanks for putting in the effort.

**Comment by xR3b0rn** [comment]
I don't mind if you squash.

**Comment by jpfr** [comment]
👍

**Pull request merged**
