### PR TITLE
adding samplingInterval to UA_Client_Subscriptions_addMonitoredItem

### PR DESCRIPTION
**Pull request by StalderT**
If you agree, I can modify examples/includes/tests files.

### CODE REVIEW

**Comment by jpfr** [comment]
Yes! This is a good addition!
Please align the tests and examples to use the new API.
We can merge then.

@open62541/open62541-core 
We will have a breaking API change for the client monitoreditems.
Is that acceptable?

**Comment by StalderT** [comment]
Ok. What do you want as default value in examples ? 250 like UaExpert (I think) ?

**Comment by StalderT** [comment]
https://github.com/open62541/open62541/issues/710

**Comment by jpfr** [comment]
This looks good!

@open62541/open62541-core 
Okay to squash&merge?

**Comment by FlorianPalm** [comment]
I am good with it!

**Comment by Pro** [comment]
:+1:

**Pull request merged**
