### PR TITLE
Fix PubSub configuration loading (issue #5656)

### PR DESCRIPTION
**Pull request by OgreTransporter**
Bugfix for broken PubSub (issue #5656)

### CODE REVIEW

**Comment by jpfr** [comment]
Ugh. Good find.
Please add a commit that enables this feature in our continuous integration builds.
So this cannot happen again.
See /tools/ci.sh.

**Comment by OgreTransporter** [comment]
Done

**Comment by jpfr** [comment]
Thanks for looking into it.
We still have a few failing tests with pubsub config parsing enabled.

**Comment by jpfr** [comment]
Rebased.
The CI tests are still failing. Please check, thanks.

**Pull request closed without merging**
