### PR TITLE
fix #1443

### LINKED ISSUE #1443: client delete/disconnect, secure channel related?
Description
===========
Total edit:

Using the connect example and breaking the connection results in malloc error.
Also not breaking cable with current master results in malloc error.

Program breaks on UA_Client_delete and _disconnect. I think because of the secure channel changes made since 0.3

Reverted back to 0.2 stable and it worked there.

Wireshark:
[readrequest in closesessions requests.pcapng.zip](https://github.com/open62541/open62541/files/1547229/readrequest.in.closesessions.requests.pcapng.zip)
lldb: 
schermafbeelding 2017-12-11 om 09 57 19
Background Information / Reproduction Steps
===========================================
reconnecting example
Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): current master
 - [x] Other OPC UA SDKs used (client or server):  Siemens PLC/uaCppServer
 - [x] Operating system: OS X
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by StalderT**
fix #1443

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
After this change the code is clean but not fast, isn't it?
You delete the old content, copy the content to target and delete the source.

Would this be faster?

```
UA_ChannelSecurityToken_deleteMembers(&client>channel.securityToken);
client>channel.securityToken=response>securityToken;
response>securityToken = null;
```

**Comment by StalderT** [comment]
@HolgerJeromin something like that : https://github.com/open62541/open62541/pull/1446/commits/200e951c5ff03bbf465b209ccc9c4aee216f635e ?

**Comment by StalderT** [comment]
I deleted the last commit that did not work. We can not set to NULL because it is not a pointer. Do you have another idea? Currently the PR works very well.

**Comment by jpfr** [comment]
Copying can fail with BADOUTOFMEMORY. You have to check the return code.

I think the simplest solution is to "move" the securityToken and serverNonce.
The problem is that we clean them up afterwards...

Just delete
```
UA_ChannelSecurityToken_deleteMembers(&response->securityToken);
UA_ByteString_deleteMembers(&response->serverNonce); 
```
and we are good.

**Comment by jpfr** [comment]
Done. Can you confirm?

**Comment by StalderT** [comment]
If not deleted in UA_OpenSecureChannelResponse_deleteMembers, I agree !

https://github.com/open62541/open62541/blob/53de7fd986ec675347a9291c08984a9a98eb173d/src/client/ua_client_connect.c#L190

**Comment by StalderT** [comment]
With the current PR, tests fails and blocks : 

```
21: 80%: Checks: 5, Failures: 1, Errors: 0
21: /data/open62541/tests/client/check_client_securechannel.c:159:F:Client SecureChannel:SecureChannel_cableunplugged:0: Assertion 'retval == 0x80ae0000' failed: retval == 11141120, 0x80ae0000 == 2158886912
21/24 Test #21: client_securechannel .............***Failed    0.64 sec
test 22
      Start 22: client_async

22: Test command: /data/open62541/bin/tests/check_client_async
22: Test timeout computed to be: 9.99988e+06
22: Running suite(s): Client
22: [01/01/1601 00:00:00.000] info/network	TCP network layer listening on opc.tcp://debian:4840/
22: [01/01/1601 00:00:00.000] info/network	Connection 8 | New connection over TCP from ::1
22: [01/01/1601 00:00:00.000] info/channel	Creating a new SecureChannel
22: [01/01/1601 00:00:00.000] info/channel	Connection 8 | SecureChannel 1 | Opened SecureChannel
22: [01/01/1601 00:00:00.000] info/session	Connection 8 | SecureChannel 1 | Session 152ca78d-6003-027c-f3bf-bb7beefeefbe | ActivateSession: Session activated
#### BLOCKS HERE
```

**Comment by WoutvdBerg** [comment]
Ran wireshark but now every cycle there is a new opensecurechannelrequest. It uses the same channelId but keeps sending message.

**Comment by StalderT** [comment]
@WoutvdBerg  And now? (with https://github.com/open62541/open62541/pull/1446/commits/2ce4acca4899f7cc0bc995c689bb88960c8a47cf)

**Comment by jpfr** [comment]
@WoutvdBerg Fixed and pushed here.

**Comment by WoutvdBerg** [comment]
It's fixed

**Comment by StalderT** [comment]
@jpfr thanks !!!

It would be nice to know why the check_client_async test blocks before the last fix.

**Comment by StalderT** [comment]
for info : 

```
UA_ByteString a;
UA_ByteString b;
a=UA_BYTESTRING("TEST");
b=a;
UA_ByteString_init(&a);
UA_ByteString_deleteMembers(&a);
UA_ByteString_deleteMembers(&b);
```
cause 

```
==5557== Invalid free() / delete / delete[] / realloc()
==5557==    at 0x4C2CDDB: free (vg_replace_malloc.c:530)
==5557==    by 0x114FC4: UA_Array_delete (ua_types.c:1064)
==5557==    by 0x114CFF: deleteMembers_noInit (ua_types.c:985)
==5557==    by 0x114D3D: UA_deleteMembers (ua_types.c:993)
==5557==    by 0x1120EC: UA_ByteString_deleteMembers (open62541.h:6124)
==5557==    by 0x112370: main (test.c)
```

I think we need to use UA_ByteString_copy

**Pull request merged**
