### PR TITLE
remove monitoringitem item id from handler

### PR DESCRIPTION
**Pull request by WoutvdBerg**
adds parameter to the datachange handler to identify a monitored item when multiple subscriptions are used

### CODE REVIEW

**Comment by StalderT** [comment]
@WoutvdBerg Just to know, why are you using monId and subId in the callback? Why do not you use the variable "context"? Should not we remove monId from the callback function and only use the context?

**Comment by WoutvdBerg** [comment]
@StalderT, because I didn't know where to use the context for.
Can the context be used to assign some custom data that will be transferred later to the handler?

**Comment by StalderT** [comment]
see https://github.com/open62541/open62541/issues/1283

**Comment by WoutvdBerg** [comment]
I understand, I will remove the subId and monId from the handler functions tomorrow. leaving only datavalue and context.

**Comment by jpfr** [comment]
Hey @WoutvdBerg ,

I'm unconvinced about using the context for everything and removing the MonitoredItem identifier.
It simplifies. And simplification is always good. But ...

- Having the identifer in the callback has practically zero cost.
- Maybe a user does not want to allocate custom memory for a monitoreditem and uses a NULL-context. Still, the identifier can be useful. For example to look up more information in a third system.
- We would break the API for many existing applications.

Can have a fresh look at this after the 0.3 release when we make big API changes?
Actually, I quite liked to first approach where the subscription identifier was added to the callback. 😄

**Comment by WoutvdBerg** [comment]
I agree with your points but I didn't get the concept with only a monitoreditemid returned. This only makes sense in singlesubscription applications. Both solutions are in the pull request.

> Can have a fresh look at this after the 0.3 release when we make big API changes?
Agreed

I will let the pull request as it is.

**Comment by jpfr** [comment]
#1497 has landed and the API was completely revamped.
The old API is still available, but marked as deprecated.
Please reopen if you want to make these changes to the (now) deprecated API.

**Pull request closed without merging**
