### PR TITLE
Various fuzzer bug fixes

### PR DESCRIPTION
**Pull request by Pro**
See the corresponding commit messages

### CODE REVIEW

**Comment by Pro** [comment]
@Infinity95 can you please review the first commit?
If an `ActivateSession` call is made two times immediately following each other, the same session will be added two times to the channel:
https://github.com/open62541/open62541/pull/1537/commits/b51b9e8d7e9f769bb2c65b12bb6802d27140da51#diff-43b83dcbe0ed74d0819aa0e6096cd436R277

Which leads to an infinite loop during cleanup:
https://github.com/open62541/open62541/blob/b51b9e8d7e9f769bb2c65b12bb6802d27140da51/src/ua_securechannel.c#L84

**Comment by Infinity95** [comment]
@Pro Isn't that only possible if we use multithreading?

**Comment by Pro** [comment]
> @Pro Isn't that only possible if we use multithreading?
No, a client can simply call the ActivateSession service two times with the exact same data/or the second time with the already activated session.

(found by oss-fuzz)

**Comment by Infinity95** [comment]
Right. This can only happen when using SecurityPolicy#None. Should be fine like this now.

**Pull request merged**
