### PR TITLE
[REVIEW] Networking code overhaul

### PR DESCRIPTION
**Pull request by mlgiraud**
Continuation of #2271 after rebasing onto master.
I had to solve some massive conflicts and a lot of stuff is now broken again, so i will continue fixing on this branch and leave the old one as is.

### CODE REVIEW

**Comment by Infinity95** [comment]
@Pro or @jpfr , do you have any idea where the linker errors in e.g. https://travis-ci.org/open62541/open62541/jobs/489086012 are coming from? Locally everything builds fine, and it's also strange that `UA_Client_setNetworkManager` cannot be found, because it is in the same TU as the UA_Client_getconfig function, which is linked just fine.

**Comment by Infinity95** [comment]
@jpfr I think the PR is ready for a review now. There remains a build issue on OSX that i really don't know how to fix and there seem to be some memory issues on windows that i currently don't have the time to investigate due to exams coming up.
I will add unit tests and write some more detailed documentation, as soon as the exams are over in the second half of March.

**Comment by Pro** [comment]
@Infinity95 before we start reviewing, you should try to get all the unit tests green, at least on travis.

When this PR is ready for review, change the title from 'WIP: ..' to '[REVIEW]'

**Comment by Pro** [comment]
@mlgiraud tell me if you need support for this PR. I may have some time to help you fix some last issues, if there are any.
Otherwise as soon as CI is green, ping me and jpfr, then we will start the review to get this into master as soon as possible.

**Comment by mlgiraud** [comment]
@Pro I'm having some troubles with the windows unit tests, if you'd like to take a look at them.

**Comment by jpfr** [comment]
The windows build that failed ran for exactly 1h.
Presumably it was killed by the CI afterwards.
We only have free-accounts that are compute-restricted.

**Comment by mlgiraud** [comment]
@Pro The corpus generation fails because of too much log output. Should i remove the printing of the hex messages? I'm not sure why this is more compared to the master branch.

**Comment by Pro** [comment]
> @Pro The corpus generation fails because of too much log output. Should i remove the printing of the hex messages? I'm not sure why this is more compared to the master branch.

I think you can just remove this line:
https://github.com/open62541/open62541/blob/9eae38bd228c815af2428229a4b8c0540b966fea/CMakeLists.txt#L337

It's just debug output and not deeded for the generator.

**Comment by mlgiraud** [comment]
@Pro Any idea why the unit tests for the new node_inhreitance fail?
The tests fail because `Parent node i=17602 not found` which is strange, because i didn't change anything regarding that code.

**Comment by Pro** [comment]
> @Pro Any idea why the unit tests for the new node_inhreitance fail?
> The tests fail because `Parent node i=17602 not found` which is strange, because i didn't change anything regarding that code.

Did you update the git submodule? 17602 is in the newest ua-nodeset v1.04 branch.

**Comment by mlgiraud** [comment]
@Pro I had to use git submodule update --remote. No it works, thank you.

**Comment by mlgiraud** [comment]
@jpfr Is anything left to do before this can be merged? I cannot test the websocket modifications, so maybe i should pull those into a separate PR?

**Comment by jpfr** [comment]
The EventLoop has landed and incorporated much of this.
Many thanks!

**Pull request closed without merging**
