### PR TITLE
Added Basic256Sha256 plugin according to Basic128Rsa15, added endpoint in the default config.

### PR DESCRIPTION
**Pull request by bobbthebuilder**
This is a first try to start with Basic256Sha256 encryption.
The specs i followed can be found on:

| Encryption | Security Policy Specification |
| ----------- |:----------|
| Basic128Rsa15  | http://opcfoundation.org/UA-Profile/UA/SecurityPolicy%23Basic128Rsa15 |
| Basic256Sha256 | http://opcfoundation.org/UA-Profile/UA/SecurityPolicy%23Basic256Sha256 |

According to the advice of @Infinity95 i basically added a new endpoint and modified the Basic128Rsa15 plugin by (re)defining
```c
#define UA_SECURITYPOLICY_BASIC256SHA256_RSAPADDING_LEN 66
#define UA_SHA256_LENGTH 32
#define UA_SECURITYPOLICY_BASIC256SHA256_SYM_KEY_LENGTH 32
#define UA_SECURITYPOLICY_BASIC256SHA256_MINASYMKEYLENGTH 256
#define UA_SECURITYPOLICY_BASIC256SHA256_MAXASYMKEYLENGTH 512
```
and replacing the mbedtls function calls from Sha1 to Sha256.

When i use UA_ServerConfig_new_basic256sha256 in `/examples/encryption/server_basic128rsa15.c/`
the server starts successfully but when i connect with UaExpert (setting Basic256Sha256 and SignAndEncrypt) the error is: `BadSecurityPolicyRejected`.
However, the problem is in:
```c 
static UA_StatusCode
asymmetricModule_compareCertificateThumbprint_sp_basic256sha256(const UA_SecurityPolicy *securityPolicy,
                                                               const UA_ByteString *certificateThumbprint) {
    if(securityPolicy == NULL || certificateThumbprint == NULL)
        return UA_STATUSCODE_BADINTERNALERROR;

    Basic256Sha256_PolicyContext *pc = (Basic256Sha256_PolicyContext*)securityPolicy->policyContext;
    if(!UA_ByteString_equal(certificateThumbprint, &pc->localCertThumbprint))
        return UA_STATUSCODE_BADCERTIFICATEINVALID;

    return UA_STATUSCODE_GOOD;
}
```
where certificateThumbprint->length = 20 but pc->localCertThumbprint.length = 32.
Thats probably an issue related to Sha1 (160 Bits/20Bytes) vs. Sha256 (256 Bits/32Bytes).

I can see that the `UA_SecureChannel `has a fixed size remoteCerificateThumbprint buffer that has size 20
and is afterwards initialized in `UA_SecureChannel_init` but increasing the buffer size to 32 did not help.
Admittedly, i'm a bit confused about that because i don't expect `src/ua_securechannel.c` to exclusively work with Basic128Rsa15 only.

To try this out, replace UA_ServerConfig_new_basic128rsa15 with UA_ServerConfig_new_basic256sha256 in examples/encryption/server_basic128rsa15.c.

Its clear that both `ua_securitypolicy_basic128rsa15.c` and `ua_securitypolicy_basic256sha256.c` are almost equal. I'd like to do the refactoring and put them together. Not to mention unit tests and an example.

Most probably i have a general misunderstanding in the procedure or oversaw an important point. Maybe @Infinity95 or any of the experienced contributors/maintainers here can guide me a bit or give further advices how to get this working?

### CODE REVIEW

**Comment by bobbthebuilder** [comment]
To try this out, replace `UA_ServerConfig_new_basic128rsa15` with `UA_ServerConfig_new_basic256sha256` in `examples/encryption/server_basic128rsa15.c`.

**Comment by Infinity95** [comment]
I believe the certificate thumbprint is always a 20 bit sha1 hash. Can you check with the specification? I don't have acces to it right now.

**Comment by bobbthebuilder** [comment]
Thank you for your response! I searched the the specification and made a find in Part 4 "Services" of the Specifiation, p. 157: "_EncryptingCertificate | ByteString | The SHA1 thumbprint of the DER form of the encrypting Certificate._" - seems you were right! :-)

I changed my code and got rid of the reported error, now getting the next from from mbedTLS:
"mbedTLS returned an error: RSA - Input data contains invalid padding and is rejected"

**Comment by Infinity95** [comment]
You have to change the encryption as well, since this uses the oaep padding scheme.
Take a look at mbedtls_rsa_rsaes_oaep_encrypt

**Comment by Pro** [comment]
thanks for the PR! You should set up your git environment correctly, i.e. your config.email is not set to the email address you use on github, thus the strange CLA message.
See https://help.github.com/articles/setting-your-commit-email-address-in-git/

After doing that, you need to amend your commit and change the author, then force push to your branch:
https://stackoverflow.com/questions/750172/change-the-author-and-committer-name-and-e-mail-of-multiple-commits-in-git

**Comment by jpfr** [comment]
Nice! This is a very welcome addition.

I sense an opportunity to reduce code duplication.
The code is 85% identical to the basic128rsa15 policy.

The existing implementation has a struct `Basic128Rsa15_PolicyContext`.
We could rename that to `MBedTLS_PolicyContext` and specialize in the structure.
So the main code remains the same.

- Put keylength etc. in the context struct
- Put function pointers to specific encryption algorithms in the context struct
- If that is too complicated, use an enum in the context struct to differentiate between policies and put `if/else` in the code

**Comment by bobbthebuilder** [comment]
@Infinity95 You are right, the RSAES-OAEP padding scheme is used for asym_encrypt.
The error "mbedTLS returned an error: RSA - Input data contains invalid padding and is rejected" i however got comes out of the asym_decrypt function. Using mbedtls_rsa_rsaes_oaep_decrypt() instead of 
mbedtls_pk_decrypt() didn't solve it, no matter what i tried. Do you understand why?

**Comment by Infinity95** [comment]
Before calling the function you have to set the correct padding scheme in the rsa context. Did you consider that?

**Comment by bobbthebuilder** [comment]
Yes, i call mbedtls_rsa_set_padding before:
```c
mbedtls_rsa_context *rsaContext = mbedtls_pk_rsa(cc->policyContext->localPrivateKey);
mbedtls_rsa_set_padding(rsaContext, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA1); // also tried other parameter combinations
//...
int mbedErr = mbedtls_rsa_rsaes_oaep_decrypt(rsaContext,                 // ctx
                                             mbedtls_ctr_drbg_random,    // f_rng
                                             &pc->drbgContext,           // p_rng
                                             MBEDTLS_RSA_PRIVATE,        // mode
                                             label,                      // label
                                             0,                          // label_len
                                             &outLength,                 // olen
                                             data->data + inOffset,      // input
                                             decrypted.data + offset,    // output
                                             decrypted.length - offset); // output_max_len
```

**Comment by bobbthebuilder** [comment]
@Infinity95 i got rid of the aforementioned mbedtls errors by my last commit.
When i start the server and try to connect with UaExpert, the error message i'm getting is "Error 'Bad' was returned during OpenSecureChannel". The server log however shows no errors and despite many debug output i was not yet able to locate the faulty function.

@Pro I followed your description yesterday and afterwards CLA was displayed as signed here. Unfortunately, the next commit after a pull from another box produced another not CLA signed commit, that was not intended by me of cause. I try to fix it.

@jpfr Full agree, my plan is to get the feature basically working, then refactor both Basic128Rsa15 and Basic256Sha256 following the steps you outlined.

**Comment by Infinity95** [comment]
Since the encryption algorithm uses sha1 as rsa padding you only have an overhead of 42 bytes. You specified the padding length for sha256. Try changing that.

**Comment by bobbthebuilder** [comment]
@Infinity95 changed UA_SECURITYPOLICY_BASIC256SHA256_RSAPADDING_LEN to 44, that didn't help.

**Comment by bobbthebuilder** [comment]
I took a closer look and observed:

- on the asymmetric side each and every function is invoked at least once and none of them raises a bad status code.

- on the symmetric side the following function are invoked:
1. sym_getEncryptionKeyLength_sp_basic256sha256
2. sym_generateNonce_sp_basic256sha256
3. sym_generateKey_sp_basic256sha256
4. swapBuffers_Basic256Sha256
- on the symmetric side the following functions are NOT invoked:
1. sym_verify_sp_basic256sha256
2. sym_sign_sp_basic256sha256
3. sym_getSignatureSize_sp_basic256sha256
4. sym_encrypt_sp_basic256sha256
5. sym_decrypt_sp_basic256sha256
- channelContext's functions are all invoked except
1. channelContext_compareCertificate_sp_basic256sha256

Thus i blame the symmetric part to be erroneous.

Here is the call stack on the server side when a client connects:
```
info/network       Connection 5 | New connection over TCP from 127.0.0.1
info/userland     after continue 1
info/channel       Creating a new SecureChannel
info/channel       Connection 5 | SecureChannel 1 | Opened SecureChannel
info/channel       Connection 5 | SecureChannel 1 | CloseSecureChannel
info/network       Connection 5 | Closed by the server
info/network       Connection 5 | New connection over TCP from 127.0.0.1
info/userland     continue 1
info/userland     after continue 1
info/userland     asymmetricModule_compareCertificateThumbprint_sp_basic256sha256
info/channel       Creating a new SecureChannel
info/userland     channelContext_newContext_sp_basic256sha256
info/userland     parseRemoteCertificate_sp_basic256sha256
info/userland     asym_makeThumbprint_sp_basic256sha256
info/userland     asymmetricModule_compareCertificateThumbprint_sp_basic256sha256
info/userland     asym_decrypt_sp_basic256sha256
info/userland     asym_getRemoteSignatureSize_sp_basic256sha256
info/userland     asym_verify_sp_basic256sha256
info/userland     sym_getEncryptionKeyLength_sp_basic256sha256
info/userland     sym_generateNonce_sp_basic256sha256
info/userland     sym_getEncryptionKeyLength_sp_basic256sha256
info/userland     sym_generateKey_sp_basic256sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     sym_8_last
info/userland     channelContext_setRemoteSymSigningKey_sp_basic256sha256
info/userland     channelContext_setRemoteSymEncryptingKey_sp_basic256sha256
info/userland     channelContext_setRemoteSymIv_sp_basic256sha256
info/userland     sym_generateKey_sp_basic256sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     swapBuffers_Basic256Sha256
info/userland     sym_8_last
info/userland     channelContext_setLocalSymSigningKey_sp_basic256sha256
info/userland     channelContext_setLocalSymEncryptingKey_sp_basic256sha256
info/userland     channelContext_setLocalSymIv_sp_basic256sha256
info/channel       Connection 5 | SecureChannel 2 | Opened SecureChannel
info/userland     asym_getLocalSignatureSize_sp_basic256sha256
info/userland     channelContext_getRemoteAsymEncryptionBufferLengthOverhead_sp_basic256sha256
info/userland     channelContext_getRemoteAsymPlainTextBlockSize_sp_basic256sha256
info/userland     channelContext_getRemoteAsymPlainTextBlockSize_sp_basic256sha256
info/userland     asym_getLocalSignatureSize_sp_basic256sha256
info/userland     asym_decrypt_sp_basic256sha256
info/userland     asym_decrypt_sp_basic256sha256
info/userland     asym_getLocalSignatureSize_sp_basic256sha256
info/userland     channelContext_getRemoteAsymEncryptionBufferLengthOverhead_sp_basic256sha256
info/userland     channelContext_getRemoteAsymPlainTextBlockSize_sp_basic256sha256
info/userland     asym_getLocalSignatureSize_sp_basic256sha256
info/userland     asym_sign_sp_basic256sha256
info/userland     asym_encrypt_sp_basic256sha256
info/userland     channelContext_getRemoteAsymPlainTextBlockSize_sp_basic256sha256
info/userland     channelContext_getRemoteAsymEncryptionBufferLengthOverhead_sp_basic256sha256
info/userland     channelContext_getRemoteAsymPlainTextBlockSize_sp_basic256sha256
info/network       Connection 5 | Closed by the server
info/channel       Connection 0 | SecureChannel 2 | SecureChannel has timed out
info/userland     channelContext_deleteContext_sp_basic256sha256
```
Does anybody see what goes wrong here?

**Comment by jpfr** [comment]
How do you generate the server certificate/key pair?
Note that you will need a longer key for 256 bit.

**Comment by Infinity95** [comment]
The minimum required size is 2048 bit, which is the default length configured in the script.

**Comment by bobbthebuilder** [comment]
@jpfr i generated the server certificate the key pair using `open62541/tools/certs/create_self-signed.py`.
I also tried setting the default length to 4096 bit, but that didn't change anything.

**Comment by Infinity95** [comment]
Here are my changes we made today:
https://github.com/Infinity95/open62541/tree/feist/feature/SecurityPolicy%23Basic256Sha256_new

**Comment by bobbthebuilder** [comment]
@Infinity95 thank you for pushing the changes! Great that you also changed md_hmac to md_hmac_Basic256Sha256 and UA_SHA256_LENGTH vs. UA_SHA1_Length mixup i forgot to commit.

According to the spec v. 1.0.4., chapter 7. page 19 the SymmetricEncryptionAlgorithm_AES256-CBC has a key size of 256 bits and a block size of 16 bytes. The counterpart in sym_decrypt_sp_basic256sha256 makes use auf a keylength that has size 128, do you agree it has to be 256 here instead?
(tried using 256 bits but it had no effect).

**Comment by Infinity95** [comment]
Since symmetric encryption is just what the name implies, i.e. symmetric, the key should be the same for both directions. In this case 32 bytes (256 bits /8).
So it should be block size = 16 byte and key length = 32 byte for both sides.

I'll try to make the nececarry API changes we discussed as soon as possible. Stay tuned for that.

**Comment by Infinity95** [comment]
I think i might have found a possible error we have. Currently we return the block size as key length but that's wrong. The key length is 32 byte whereas the block size is 16 byte. This is possible since aes uses the actual 32 byte key to derive 16 byte round keys which are then xored onto the actual 16 byte block (simplified of course)

**Comment by jpfr** [comment]
Can you just add the whole shebang of
- cleartextblocksize
- encryptedblocksize

directly as integers into the UA_SecurityPolicyCryptoModule structure?

And since we are already on it, do we really need methods to get getLocalEncryptionKeyLength and getLocalEncryptionKeyLength or isn't this rather predefined by the policy?
If not, a sentence in the comments about varying keylengths would help.

**Comment by Infinity95** [comment]
@jpfr That was the plan.
In the asymmetric case the sizes have to be extracted from the certificates/keys. In the symmetric case the sizes are always constant for one policy. It would be best though to always use the getLocalEncryptionKeyLength etc. functions to be consistent i believe. I don't really have time today but i'll try to make the necessary changes tomorrow after my exam and create a separate PR for that. Shouldn't be too many changes required but we should try to include it in 0.3 i think.

**Comment by Infinity95** [comment]
I fixed it. Please rebase on my branch that i linked in a previous comment.
Also add your name to the header.

**Comment by bobbthebuilder** [comment]
@Infinity95 sorry for the late response, i had the opportunity to test your changes on friday afternoon and can confirm that you succeeded - great, thank you very much for your effort! I waited for #1613  to be reviewed by @jpfr and now did the rebase.

One side note: The endpoints in `plugins/ua_config_default.c` do not support logins with username and  password as they are still commented out in the endpoints of Basic128Rsa15 as well as Basic256Sha256. Did we oversaw putting them in or is this intentional?

**Comment by Infinity95** [comment]
I'll have to check. Don't know off the top of my head what's going on there.
As soon as the other PR is merged you should probably rebase on master to get rid of the redundant commits.

**Comment by bobbthebuilder** [comment]
@Infinity95 no problem, just to let you know, i enabled the username/password policy in the Basic256Sha256 endpoint and grabbed open62541/examples/encryption/server_basic128rsa15.c (using UA_ServerConfig_new_basic256sha256()) and hoped the best but the error i got is BadIdentityTokenInvalid because of 
```c
if(token->encryptionAlgorithm.length > 0)
    return UA_STATUSCODE_BADIDENTITYTOKENINVALID;
```
in open62541/plugins/ua_accesscontrol_default.c

(when outcommenting this check, UA_String_equal(&token->password, pw) is false later).

**Comment by Infinity95** [comment]
@bobbthebuilder Please rebase on master before continuing to work on this. It will probably save you a lot of work later on, since some of the api changed.

The user identity tokens use their own policy which can be different from the one in the securechannel. I don't know exactly how this works right now but if the securechannel is already encrypted i believe it is not necessary to encrypt anything in the user token.
You'll have to check with the standard here.

**Comment by Pro** [comment]
Replaced by #1634

**Pull request closed without merging**
