### PR TITLE
Extract EndpointUrl Splitting

### LINKED ISSUE #778: connect issue - DNS lookup of 192.163.1.193 failed with error Servname not supported for ai_socktype
Hello

I use open62541 SDK v0.2 today to connect to the OPC UA Foundation Server.
Open62541 client is on the ubuntu(virtualbox)
Server is on the windows PC.
I can do this connection before.

Error message : (when connect to the Unified Automation Server)
[08/29/2016 06:31:21.456] warning/network	DNS lookup of tq021110740 failed with error Servname not supported for ai_socktype

Error message : (when connect to the OPC UA Foundation Server)
[08/29/2016 07:10:09.713] error/client	GetEndpointRequest failed with statuscode 0x80b90000

### PR DESCRIPTION
**Pull request by Pro**
Fixes #778 and improves handling of invalid urls.

Can you think of any other valid/invalid combination to test in the unit tests?

Otherwise ready to merge.

### CODE REVIEW

**Comment by jpfr** [comment]
Nice! With the tests and all, this is a posterboy PR. :+1: 
Some last (last) comments before merging.

- Some embedded targets don't have atoi. In `/src/server/ua_services_attributes.c` there is a function
```c
static size_t readNumber(UA_Byte *buf, size_t buflen, UA_UInt32 *number)
```
doing the same job. You could make that an "utility function" and use it in both places.
- Why return the path with a leading slash? Imho most users would have to remove it. If there are use cases needing the slash, we can keep it.

ua_connection.c:236
- The case with and without pathTmp differ only in the value of portLen. Make the if-else part short and do the work in a shared block.
- Is it possible to use memcpy instead of strncpy? That saves the nasty macro switches.

**Comment by HolgerJeromin** [comment]
It is quite common that in an URI the Path includes the leading /

**Comment by HolgerJeromin** [comment]
Your code does not seem to support IPv6 Syntax `opc.tcp://[2001:0db8:85a3::8a2e:0370:7334]:1234/path`

Supporting this syntax is not fun. I did it for the [ACPLT Runtime](https://github.com/acplt/rte/blob/5f7c61c5795083767828b395c7cb49fcdcf3eedb/syslibs/comm/kshttp/source/httpClient_genericClient.c#L153-L321). But this code is not plain C.

**Comment by Pro** [comment]
@HolgerJeromin yes, you are right, IPv6 is not supported.
I'll add it here using a simple state variable, but IPv6 is not supported anywhere else in open62541.

**Comment by Pro** [comment]
@HolgerJeromin IPv6 is now included in the PR (without the username and password notation)

@jpfr this should now be ready to merge.

We maybe should add somewhere a check if the hostname is `IPv6` and then show an error message, that IPv6 is not supported in open62541 (at least for now).

**Comment by HolgerJeromin** [comment]
Nice! You could test for `"opc.tcp://hostname:1234"` and `"opc.tcp://hostname:1234?query"`

**Comment by Pro** [comment]
The unit test for `opc.tcp://hostname:1234` is already there?!
Endpoint urls should not contain query parameters, thus I think we shouldn't care about those. If an URL with query is passed, it will return a bad status code.

**Comment by jpfr** [comment]
Great!
I did some last cosmetic changes (untabify) and squashed into one commit with @Pro as the author.

All merged in 0.2 via 0fdfcc43d467d0ea4bf003733c0fd50549677279.

**Comment by HolgerJeromin** [comment]
Sorry, I missed the test. :-) 
You are right with the query. Good job

**Pull request closed without merging**
