### PR TITLE
fix(server): Range check in getNamespaceByIndex (#5527)

### PR DESCRIPTION
**Pull request by chhuebner**

### CODE REVIEW

**Comment by basyskom-meerkoetter** [comment]
Could you please also extend the unit test to cover this boundary condition?
See https://github.com/open62541/open62541/blob/8eeb6c33da78a0d020aeafcf20eab6cbf84a3c0a/tests/server/check_server.c#L49

**Comment by jpfr** [comment]
If this can be backported I’d to have this as a pr for the 1.3 branch.

**Comment by jpfr** [comment]
I switched the target branch to 1.3.
But this pulled in hundreds of commits.
Please rebased on top of  1.3.

**Comment by chhuebner** [comment]
I will create a new PR for 1.3 branch

**Pull request closed without merging**
