### PR TITLE
[Review] Add capability to call/reference a method from a FunctionalGroup

### PR DESCRIPTION
**Pull request by mlang-de**
See issue #2193 for further details.

Should this part be switchable in cmake?
[Update] In release mode with gcc 4.5.2 the difference is 0,4kB.

### CODE REVIEW

**Comment by jpfr** [comment]
I'm a bit hesitant to put specifics of the DI namespace into the core service definition.
But we should support the case obviously.

Let's put this on the agenda for the conference call.

**Comment by Pro** [comment]
image

From the spec:
`A method shall be a component of an Object`

**Comment by mlang-de** [comment]
DI specify:
image
[...] FunctionalGroupType is used to organize Parameters and Methods [...]

**Comment by mlang-de** [comment]
@jpfr @Pro How could this PR be handled? Some preferred solution like a plugin/callback which could be configured?

**Comment by mlang-de** [comment]
@jpfr Should I do some defines around this parts? So an user can decide via the CMake file to use the DI-method support or not.

**Comment by jpfr** [comment]
Give a clear reference to the DI spec in the comments.
Mention that this is a *workaround* done only for DI.

**Comment by jpfr** [comment]
This is still earmarked for v1.1.
Can be merged when the CI goes green.

**Comment by jpfr** [comment]
Finally merged.
Thanks for being patient. 👍

**Pull request merged**
