### PR TITLE
Corrected format of LocaleId in LocalizedText attributes

### PR DESCRIPTION
**Pull request by jonasgreen88**
The LocaleIds was formatted with an underscore as separator between the language and region. According to the OPC UA specification the language and the region shall be separated by a hyphen.
Also removed LocaleId in those cases where a specific language is not addressed, i.e. when presenting a type name.

Changes based on discussion of issue #1173

### CODE REVIEW

**Comment by Pro** [comment]
@jonasgreen88 thanks for the PR!

One of the unit tests is still failing. I think here you have to remove the locale:
https://github.com/jonasgreen88/open62541/blob/7a58e6c0a5f97327bce47b170c99a5a40b110fe5/tests/check_services_attributes.c#L338

Can you please change that and then from my side we can merge it

**Comment by Pro** [comment]
Hm, Travis is still failing.
https://travis-ci.org/open62541/open62541/jobs/270753390#L5438
Can you check the test locally and try to fix it? Thanks!

To run the tests use:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DUA_BUILD_EXAMPLES=ON -DUA_ENABLE_DISCOVERY=ON -DUA_ENABLE_DISCOVERY_MULTICAST=ON -DUA_BUILD_UNIT_TESTS=ON -DUA_ENABLE_COVERAGE=ON -DUA_ENABLE_VALGRIND_UNIT_TESTS=ON ..
make -j && make test ARGS="-V"
```

**Comment by jonasgreen88** [comment]
Thanks for the assistans. I'll try run the tests local next week.

**Comment by Pro** [comment]
@jonasgreen88 I just commited a fix for the failing unit test.
Let's see if CI is happy, then we can merge this

**Comment by jonasgreen88** [comment]
@Pro Thanks! Unfortunately I've had no time so far this week to look into it.

**Pull request merged**
