### PR TITLE
Add Test, Documentation and Example for instantiation and inheritence

### PR DESCRIPTION
**Pull request by markusgraube**
The rest of #812 

I tried to align examples, documentation and tests.

Is it now easier to understand the instantiation?

### CODE REVIEW

**Comment by markusgraube** [comment]
Hmm, it seems, that we have to enable -DENABLE_GENREATE_NAMESPACE0 on Travis. What do you think?

**Comment by jpfr** [comment]
It would be better, if the example worked with the precompiled dll/.so from our release.

When I last checked, it was possible to generate only new nodes.
And to use the ns0 bootstrapping in ua_server.c

Do you want to show an example where ns0 is bootstrapped by the nodeset compiler as well?

**Comment by Pro** [comment]
@markusgraube if you want to create a specific unit test for the ns0 initialization, you could also use the following approach:

https://github.com/Pro/open62541/commit/950d078a0e903cd15f9e8567df08912f8979438e

It first runs all the other unit tests without ns0 and then the specific instantiation check with ns0.

**Comment by Pro** [comment]
@markusgraube any update on this?
It would be really nice if we can add your tutorials!

**Comment by markusgraube** [comment]
sorry, I have just forgotten that this task is still open. I will find some time for this in the next week

**Comment by markusgraube** [comment]
closed in favor of #1169

**Pull request closed without merging**
