### PR TITLE
[Review] add build/test for security policy source code using openssl in Linux

### PR DESCRIPTION
**Pull request by wenshan1**
1. Add a new line at the end of the file for some old compiler is needed.
2. add UA_ENABLE_ENCRYPTION_OPENSSL in test/CMakeLists.txt to support to test the source code using OpenSSL.
3. Add the build/test script to protect the source code with OpenSSL in Linux.
4. Because most test cases are testing functions that are not related to encryption，in order to speed up CI, I think that only one configuration can test encryption-related functions.

If the review is approved, please merget the PR to master.

### CODE REVIEW

**Comment by wenshan1** [comment]
using the OpenSSL compiled with source code, set the correct vale of OPENSSL_ROOT_DIR. Don't show the test verbose for the CI will fail by the too long log.

**Comment by jpfr** [comment]
Looking good.

Why building OpenSSL from source?
An install of openssl-dev should suffice. And it will take less time.

**Comment by wenshan1** [comment]
Using the system pre-installed openssl and change the PR to WIP again.

**Comment by wenshan1** [comment]
Minimal C code modification which add a new line at the end of files.  All test cases ran in Linux are passed.  The status of windows checks are expected. The PR should not impact the test cases for windows. So change PR to Review.

**Comment by wenshan1** [comment]
rebase.

**Comment by jpfr** [comment]
Good improvements. 👍

**Pull request merged**
