### PR TITLE
[Review] bug(server) UA_Server_cleanupTimedOutSecureChannels could remove securechannel whereby socket connection is already established

### PR DESCRIPTION
**Pull request by mlang-de**
The timer callback UA_Server_cleanupTimedOutSecureChannels is going to be executed each 10 seconds by internal software timers.
The problem is, if a TCP socket was opened/established, Hel- and Ack-Msg was exchanged and no OpenSecureChannelRequest was received so far.
In this case the UA_Server_iterate process first executes the named timer callback and removes the SecureChannel since it is marked as closed (closed is the initial value for a new secure channel).

The outstanding OpenSecureChannelRequest will end up in a TCP RST since the socket was already closed too. 

How to reprduce:
- in the loop:
    - create tcp connection
    - create securechannel
    - read something
    - close connection gracefully (SecureChannel then socket)

The misbehaviour occurs sometimes after 100 attempts, sometimes after 1000 attempts.

May this is not the best solution, let me know how to fix it in your way. For instance intrudoces a new state UA_SECURECHANNELSTATE_INIT?

### CODE REVIEW

**Comment by jpfr** [comment]
Thanks for uncovering this.
I would prefer an explicit solution.

Could you make it work with the following enum options for SecureChannel state?
```c
typedef enum {
    UA_SECURECHANNELSTATE_FRESH = 0,
    UA_SECURECHANNELSTATE_HEL_SENT,
    UA_SECURECHANNELSTATE_HEL_RECEIVED,
    UA_SECURECHANNELSTATE_ACK_SENT,
    UA_SECURECHANNELSTATE_ACK_RECEIVED,
    UA_SECURECHANNELSTATE_OPN_SENT,
    UA_SECURECHANNELSTATE_OPEN,
    UA_SECURECHANNELSTATE_CLOSING,
    UA_SECURECHANNELSTATE_CLOSED
} UA_SecureChannelState;
```

**Comment by mlang-de** [comment]
@jpfr I had some problem to update the unit test cases. Please advice.

**Comment by mlang-de** [comment]
Rebased.
I can't rid off the commits from today, in which 6 of 7 are duplicated ones from August 2020. 
@jpfr Is this mergable? (After all tests passed)

**Comment by mlang-de** [comment]
@jpr or @Pro  
No glue how I could resolve this conflict by my PR.

Could you resolve the conflicts according:
In file src/server/ua_server_binary.c
```c
<<<<<<< (Bug)-UA_Server_cleanupTimedOutSecureChannels-could-remove-securechannel-whereby-socket-conneciton-already-establishment
    if(channel->state != UA_SECURECHANNELSTATE_FRESH)
        return UA_STATUSCODE_BADINTERNALERROR;
    size_t offset = 8; /* Go to the beginning of the TcpHelloMessage */
=======
    if(channel->state != UA_SECURECHANNELSTATE_CLOSED)
        return UA_STATUSCODE_BADINTERNALERROR;
    size_t offset = 0; /* Go to the beginning of the TcpHelloMessage */
>>>>>>> 1.2
```
with
```c
    if(channel->state != UA_SECURECHANNELSTATE_FRESH)
        return UA_STATUSCODE_BADINTERNALERROR;
    size_t offset = 0; /* Go to the beginning of the TcpHelloMessage */
```



and in file src/server/ua_services_securechannel.c:
```c
<<<<<<< (Bug)-UA_Server_cleanupTimedOutSecureChannels-could-remove-securechannel-whereby-socket-conneciton-already-establishment
    if(channel->state != UA_SECURECHANNELSTATE_FRESH) {
=======
    if(channel->state != UA_SECURECHANNELSTATE_ACK_SENT) {
>>>>>>> 1.2
```
with
```c
if(channel->state != UA_SECURECHANNELSTATE_FRESH) {
```

TIA

**Comment by jpfr** [comment]
Rebased and merged.
Thanks @mlang-de !

**Pull request merged**
