### PR TITLE
[Review] fix(core): LibreSSL API change

### PR DESCRIPTION
**Pull request by GoetzGoerisch**
* API change in LibreSSL >3.5 (https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.0-relnotes.txt)
* URI Checks where changed https://github.com/libressl-portable/openbsd/issues/131
* Segfault in >3.5.0 <3.7.0 fixed for URI checks: https://github.com/openbsd/src/commit/215e6767bc08f6f1f7de1bf68c9ef05ca9b21e78

Thank you @ccvca for your contribution

Co-authored-by: Christian von Arnim <christian.von-arnim@isw.uni-stuttgart.de>

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
@jpfr CI failures are the same like current master @ https://github.com/open62541/open62541/commit/cdc1a3173b9a884d055d38aa5e9f24bc29632c8c

**Comment by ccvca** [comment]
`X509_STORE_CTX_get_check_issued` is replaces by simpler `X509_check_issued` as discussed here: https://github.com/libressl-portable/portable/issues/748

**Comment by jpfr** [comment]
Looks good.
Just one remaining error.
Merging when green.

```
/home/runner/work/open62541/open62541/plugins/crypto/openssl/ua_openssl_create_certificate.c:87:9: error: ‘ERR_get_error_line_data’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
[170](https://github.com/open62541/open62541/actions/runs/3858032845/jobs/6576094953#step:4:171)
   87 |         ERR_get_error_line_data(&file, &line, &data, &flags);
[171](https://github.com/open62541/open62541/actions/runs/3858032845/jobs/6576094953#step:4:172)

**Comment by GoetzGoerisch** [comment]
@jpfr  ready for a second review.

**Comment by jpfr** [comment]
👍

**Pull request merged**
