### PR TITLE
Using portable format specifiers

### PR DESCRIPTION
**Pull request by cldhms**
Now using portable format specifiers for UA_LOG macros

### CODE REVIEW

**Comment by jpfr** [comment]
These are not available on all of our systems, notably some old Visual C++ versions.
Other projects have added a compatibility layer.
E.g. here https://github.com/unicorn-engine/unicorn/blob/master/include/unicorn/platform.h

Happy to merge when all is green!

**Comment by cldhms** [comment]
It looks better after your recommended changes. I'm not sure why it fails now though, the build is cancelled after 60 minutes? @jpfr

**Comment by jpfr** [comment]
Nice!
Yes, the timeouts should disappear after a restart.
There's no reason why you changes make things slower.

**Comment by cldhms** [comment]
Is it possible for me to trigger a restart without adding a new commit?

**Comment by cldhms** [comment]
@jpfr I'm not sure why it's failing now as I haven't changed anything, do you have any idea?

**Comment by jpfr** [comment]
This problem is logged on Azure:

```
42 : ~~Dr.M~~ error #1: LEAK 40 direct bytes 0x01c5e208-0x01c5e230 + 368 indirect bytes [D:\a\1\s\build\tests\test-verbose.vcxproj]
  42: ~~Dr.M~~ # 0 replace_malloc                                               [d:\drmemory_package\common\alloc_replace.c:2577]
  42: ~~Dr.M~~ # 1 __UA_Client_AsyncServiceEx                                   [d:\a\1\s\src\client\ua_client.c:484]
  42: ~~Dr.M~~ # 2 UA_Client_Subscriptions_backgroundPublish                    [d:\a\1\s\src\client\ua_client_subscriptions.c:1289]
  42: ~~Dr.M~~ # 3 UA_Client_run_iterate                                        [d:\a\1\s\src\client\ua_client_worker.c:92]
  42: ~~Dr.M~~ # 4 Client_subscription_createDataChanges_async_fn               [d:\a\1\s\tests\client\check_client_subscriptions.c:494]
  42: ~~Dr.M~~ # 5 tcase_run_tfun_nofork                                        [c:\vcpkg\buildtrees\check\src\0.13.0-7fecf5a3e2\src\check_run.c:419]
  42: ~~Dr.M~~ # 6 srunner_iterate_tcase_tfuns                                  [c:\vcpkg\buildtrees\check\src\0.13.0-7fecf5a3e2\src\check_run.c:259]
  42: ~~Dr.M~~ # 7 srunner_run_tcase                                            [c:\vcpkg\buildtrees\check\src\0.13.0-7fecf5a3e2\src\check_run.c:401]
  42: ~~Dr.M~~ # 8 srunner_iterate_suites                                       [c:\vcpkg\buildtrees\check\src\0.13.0-7fecf5a3e2\src\check_run.c:218]
  42: ~~Dr.M~~ # 9 srunner_run_tagged                                           [c:\vcpkg\buildtrees\check\src\0.13.0-7fecf5a3e2\src\check_run.c:813]
  42: ~~Dr.M~~ #10 srunner_run                                                  [c:\vcpkg\buildtrees\check\src\0.13.0-7fecf5a3e2\src\check_run.c:826]
  42: ~~Dr.M~~ #11 srunner_run_all                                              [c:\vcpkg\buildtrees\check\src\0.13.0-7fecf5a3e2\src\check_run.c:765]
  42: ~~Dr.M~~ 
```

This is an actual bug. But it could be a random problem that is already on 1.0.
What;s your assessment?

**Comment by cldhms** [comment]
I don't think it's possible for my changes to have caused a memory leak as I've only changed the format specifiers for printouts.

**Comment by jpfr** [comment]
Very nice! Thanks.

**Pull request merged**
