### PR TITLE
CMake: only add -Werror in Debug builds

### PR DESCRIPTION
**Pull request by DerDakon**

### CODE REVIEW

**Comment by jpfr** [comment]
This still adds -werror for all builds.
The line `if(CMAKE_BUILD_TYPE STREQUAL "Debug")` is below.

On a different note: why disable werror?

**Comment by Pro** [comment]
Also setting the CMAKE_C_FLAGS_DEBUG variable is not recommended. It's better to use the `add_definition` function, wrapped by a corresponding if.

Same question here: Why do you need to remove Werror?

**Comment by DerDakon** [comment]
Because you don't know which warnings a new compiler will introduce on an older version that suddenly become errors.

It set's the flags for debug builds, see the variable name. CMake will automatically select the flags for debug builds, even for generators that support more than one configuration at once.

**Comment by Pro** [comment]
Makes sense! Thanks for the clarification

Good idea.
IMHO we can merge.

**Comment by DerDakon** [comment]
add_definitions() is for definitions (i.e. -Dsomething), not for compiler flags. Who says one should use add_definitions()?

**Comment by traversaro** [comment]
> The line `if(CMAKE_BUILD_TYPE STREQUAL "Debug")` is below.

Not directly related to this PR, but I just noticed this from your reply: adding Debug-specific options by checking `CMAKE_BUILD_TYPE` will not work properly when using multiple-config CMake generators (for example Xcode), as `CMAKE_BUILD_TYPE` is only meaningful for single-config generators (see related docs: https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html).

The way of specifying compile  options just for Debug configurations in a way that works for both single-config and multiple-config generators is by combining [generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html) and the [`target_compile_options`](https://cmake.org/cmake/help/latest/command/target_compile_options.html) command: 
~~~
target_compile_options(lib PRIVATE $<$<CONFIG:Debug>:-debug-specific-option> 
~~~

**Comment by DerDakon** [comment]
… or just use CMAKE_<LANG>_FLAGS_<CONFIG> ;)

**Comment by DerDakon** [comment]
Ping?

**Comment by jpfr** [comment]
@traversaro 
Let's do it per-config when the need arises.
It is more simple like this.

Is this a blocker on MacOs?

**Comment by traversaro** [comment]
> 
> 
> @traversaro
> Let's do it per-config when the need arises.
> It is more simple like this.
> 
> Is this a blocker on MacOs?

Sorry, I missed this message back in time. As you may imagine, it was not a blocker: simply those flags will not be passed to Debug builds if a multiple-config generator is used.

**Pull request merged**
