### PR TITLE
made client non blocking during connecting stage;

### PR DESCRIPTION
**Pull request by sherylll**
only for review, code that use the modified function has to be changed

### CODE REVIEW

**Comment by jpfr** [comment]
Hey @sherylll ,

thanks for the contribution. You said this is work-in-progress.
Just tell us when you are ready for a review before merging.

With regards to the new API. When do I know if a connection failed (and why it failed)?
`UA_Client_connect_async` returns a statuscode. Could it also take a callback function for async notification of fail/success?

**Comment by Pro** [comment]
@sherylll note that your first two commits were not made with the correct git committer email. Can you change the committer there and then force push to this PR?
https://help.github.com/articles/changing-author-info/

**Comment by jpfr** [comment]
Hello @sherylll ,

we should try to get this merged soon.

I see a lot of code duplication going on.
Can the sync version reuse the async version internally?

**Comment by sherylll** [comment]
Hi,

@Pro I have reconfigured my account settings as in the link, hope everything works fine now.

@jpfr I think that's possible by passing some extra arguments to specify sync/async, but in the next month I won't have much time to work on the code... If it's not urgent I can come back to it in October

**Comment by Pro** [comment]
@sherylll the user is still not correct.
I modified the script for you, can you please execute the following steps:

1. Change into your local git repo and make sure your `async_client_loop` branch is checked out
2. Execute the following bash script:
```
#!/bin/sh

git filter-branch --env-filter '
OLD_EMAIL="sherylsun14.gmail.com"
CORRECT_NAME="Sun"
CORRECT_EMAIL="sherylsun14@gmail.com"
if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- 3d7a4aab130e86d9e014d702ef03026212cf3aa3..HEAD
```
3. Force Push the changes: `git push -uf origin async_client_loop` (Replace origin with the name of your remote which points to your local fork)

**Comment by sherylll** [comment]
Hi,
The issue with my account is finally resolved, and I'm back working on integrating my last changes with the newest master code.

**Comment by Pro** [comment]
@FlorianPalm is the `open62541:async_client_loop` still active/used by you (your were the last working on it)?
Otherwise I would suggest that we merge all the commits of `open62541:async_client_loop` into this PR and then change the base of this PR to master

**Comment by FlorianPalm** [comment]
@Pro The branch can be removed. The work is happening within the pull request of sherylll.

**Comment by Pro** [comment]
@sherylll do you want to integrate the commits from the branch `open62541:async_client_loop`, then use `git rebase upstream/master` and force push to your branch? Afterwards you can change the PR to use master as base.

Otherwise I can also do it, but for that you need to make sure that you do not have any local commits left, otherwise these will be broken after a force push.

**Comment by sherylll** [comment]
Hi I haven't made any changes since I last pushed, so you can safely
integrate the mentioned branch. (sorry for pushing all the generated files
by mistake...)

2017-10-19 9:11 GMT+02:00 Stefan Profanter <notifications@github.com>:

**Comment by Pro** [comment]
@sherylll I changed the base of this PR to master, so there is now a bit less commits.
Can you edit your commit where you added the generated files so that we have a clean `Changed Files` list?

**Comment by sherylll** [comment]
@Pro I ran "git commit --amend" and edited the commit message, then forced puth. This seems to have no real effect on the pushed files on my fork, but hopefully it is enough to get a clean commit message? Or do I need to redo the whole commit?

**Comment by Root-Core** [comment]
Non blocking connection is still missing after #1497, if I'm right.
To have a `UA_Client_connect_async()` functionality is really important imho, the PR was closed though.
It there any reason to not clean it up and merge into `master`?

**Comment by sherylll** [comment]
Hi, I've opened a new PR: [](https://github.com/open62541/open62541/pull/1512), since it was easier to work on the new copy than cleaning up the old one.

However that one also experienced some problem with building: [](https://travis-ci.org/open62541/open62541/builds/336317828?utm_source=github_status&utm_medium=notification), any help would be appreciated.

**Pull request closed without merging**
