### PR TITLE
WIP: More SecureChannel unit tests

### PR DESCRIPTION
**Pull request by Infinity95**
This PR is a continuation of #1336

### CODE REVIEW

**Comment by jpfr** [comment]
This PR currently doesn't do much. Shall we close or are you working on it?

**Comment by Infinity95** [comment]
I'm working on it.

**Comment by jpfr** [comment]
Can we rebase/merge?

**Comment by jpfr** [comment]
Can we merge?

**Comment by Infinity95** [comment]
I'm not done working on this yet, but we could merge in what's here for now. Although i'd first like to add some more tests.

**Comment by Pro** [comment]
Note: #1536 enables installation of mbedtls on Continuous integration and also enables the switch `UA_ENABLE_ENCRYPTION`

**Comment by Pro** [comment]
@Infinity95 should we merge this for 0.3 release or do you think that you can add your desired tests within the next two weeks?

**Comment by Infinity95** [comment]
I will see what i can add until the end of next week. then we can merge

**Comment by Pro** [comment]
@Infinity95 any updates on this?

**Comment by Infinity95** [comment]
Im currently in the last week of my bachelors thesis so very short on time.
If you want you can merge what's there for now.

**Pull request merged**
