### PR TITLE
[Review] build(deps): Switches branch for `deps/ua-nodeset` -> UA v1.05

### PR DESCRIPTION
**Pull request by GoetzGoerisch**
* The `latest `branch is a merge between v1.05 base spec and all CS

Base UA Spec is v1.05 now.

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
Between v1.04 and v1.05 the _ModellingRuleType_ was changed.

Thanks, @ccvca for pointing this out.

v1.04 [https://reference.opcfoundation.org/v104/Core/ObjectTypes/ModellingRuleType/](https://reference.opcfoundation.org/v104/Core/ObjectTypes/ModellingRuleType/)
vs
v1.05: [https://reference.opcfoundation.org/v105/Core/ObjectTypes/ModellingRuleType/](https://reference.opcfoundation.org/v105/Core/ObjectTypes/ModellingRuleType/)

The failing test (introduced with #4865 is:
https://github.com/open62541/open62541/blob/22883e54027366190a5c38abdfa28c9268fbbc1f/tests/server/check_services_nodemanagement.c#L593-L646

@jpfr and @basyskom-jvoe please suggest how to fix

**Comment by basyskom-jvoe** [comment]
@GoetzGoerisch The test just instantiates an object of a type with at least one variable child node.
It doesn't matter which object type, any type with at least one variable child node will do.

**Comment by jpfr** [comment]
This needs to be rebased as the nodeset was updated on master.

**Comment by GoetzGoerisch** [comment]
Yes, I have to fix the tests as well.

**Comment by GoetzGoerisch** [comment]
Thanks @ccvca for your help.

**Comment by jpfr** [comment]
Updated the branch to include #5062.

**Pull request merged**
