### PR TITLE
CodeQuality: Fix issues found by lgtm.com

### PR DESCRIPTION
**Pull request by Pro**
See also https://lgtm.com/projects/g/open62541/open62541/alerts

### CODE REVIEW

**Comment by Pro** [comment]
@xcorail I now fixed some issues, and also enabled PR checking before that.

What is quite annoying is that the comment from LGTM is posted under my name. I do not really like that, and it has a disadvantage that you can not ignore comments from LGTM.

Can you change that and use a specific user for LGTM as it is done for @CLAassistant and @coveralls as shown e.g. #2240 

I really like that feature, but as long as the comments are posted under my name, I will disable PR checking...

**Comment by Pro** [comment]
This pull request **fixes 83 alerts** when merging 380808f30284a53b51e4694655c4dd8d3a4ee3d6 into 22bccbdde9565cfb0d0b20ba901081b9f1a05823 - [view on LGTM.com](https://lgtm.com/projects/g/open62541/open62541/rev/pr-a9ad8a08e6340a6b06c823092668e5339375f6e4)

**fixed alerts:**

* 24 for Testing equality to None
* 16 for Unused import
* 15 for Missing call to \_\_init\_\_ during object initialization
* 9 for &#39;import \*&#39; may pollute namespace
* 5 for Unused local variable
* 4 for Except block handles &#39;BaseException&#39;
* 2 for Inconsistent equality and inequality
* 2 for Variable defined multiple times
* 2 for Nested loops with same variable
* 2 for \_\_init\_\_ method calls overridden method
* 1 for Module is imported more than once
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by sjvs** [comment]
Hi @Pro! @xcorail asked me to chip in on this one.

We're currently working on implementing the new GitHub Apps API for LGTM; this will also introduce comments from a dedicated LGTM bot account. There are various reasons why we can't do that at the moment, but it'll be sorted soon.

In the meantime, it's very easy to set up your own bot account for LGTM's integration into open62541. Some other projects have done that already; e.g. AMPHTML: https://github.com/ampproject/amphtml/pull/15373

Here's how to do it (won't take more than a minute or two):

1. Create a new GitHub account, like "open62541-LGTM-bot"
2. Temporarily elevate the bot account's privileges on open62541 to repository admin
3. Disable LGTM.com code review integration using your personal account
4. Log into LGTM.com with the bot account (e.g. using the GitHub OAuth)
5. Set up LGTM code review integration with the bot account from the open62541 project's "Integrations" tab
6. Optional: revoke the bot's repo admin privileges on GitHub (the integration will continue to work)

Let me know if you have any other questions/comments!

**Comment by jpfr** [comment]
Wow. You're a machine @Pro.
83 issues in one PR. That mus be a record. 👍

**Comment by Pro** [comment]
@sjvs I added a separate bot account (`open62541-LGTM-bot`) as owner of the project for now.
Unfortunately it looks like LGTM has cached a previous limited access of the bot to the repo and after I changed it to owner it is not updated on LGTM. Now I can not enable the PR integration... ("Not admin/owner of repository"). On github the bot is listed as Maintainer for the project (hidden, thus not visible publicly).

Can you check that?

**Pull request merged**
