### PR TITLE
Enable PubSub tests and static code analysis

### PR DESCRIPTION
**Pull request by andreasebner**
Enable PubSub unit tests and static code analysis for tranvis.

### CODE REVIEW

**Comment by Pro** [comment]
Should we also enable it on appveyor + drMemory?

**Comment by jpfr** [comment]
Delta frames off by default?

I have no opinion here. A bit of documentation would be good though.

**Comment by jpfr** [comment]
> Should we also enable it on appveyor + drMemory?

It can only help..

**Comment by andreasebner** [comment]
@Pro @jpfr I will fix the current travis/test problems and enable the PubSub port for appveyor + drMemory.

**Comment by andreasebner** [comment]
@jpfr The PubSub option is disabled by default. The UA_ENABLE_PUBSUB_DELTAFRAMES make only sense while PubSub is enabled. Because of this i changed the default to OFF. If you like, we can change this back. I will update the PR and add some documentation for the flags.

**Comment by jpfr** [comment]
> The PubSub option is disabled by default. The UA_ENABLE_PUBSUB_DELTAFRAMES make only sense while PubSub is enabled. 

Cool.

**Pull request merged**
