### PR TITLE
fix(client) connection between the example server_encryption and client_encryption is not encrypted

### PR DESCRIPTION
**Pull request by wenshan1**
This PR is fix the issue https://github.com/open62541/open62541/issues/3578. 
The client want to connect with the server by encryption.
Root cause: 
  1.   The client open a secure channel with http://opcfoundation.org/UA/SecurityPolicy#None
   2.  The client get the end point information from the server and set it to the client.
   3.  But the client don't close the secure channel, the client still use the secure channel to create/active a new session.

Solution:
1.  If the client isn't set the endpoint information:
     Then  the client open a secure channel with http://opcfoundation.org/UA/SecurityPolicy#None.
     The client get the end point information from the server and set it to the client.
2.  If the client want to connect with encryption:
      set the security policy to the client's channel.
3. connect the server.

Test:  
1. start the example server_encryption:
$bin/examples/server_encryption   ~/open62541-cert/server_cert.der  ~/open62541-cert/server_key.der  ~/open62541-cert/client_cert.der
2. start the example client_encryption to connect the server and read data:
 $bin/examples/client_encryption opc.tcp://localhost:4840 ~/open62541-cert/client_cert.der ~/open62541-cert/client_key.der ~/open62541-cert/server_cert.der
3. Capturing packets with Wireshark, the wireshark shows:
the client can connect with the server with the signed and encryption information.

basic128rsa15

Also test the OPEN62541 client can connect/read data from the server without encryption.

### CODE REVIEW

**Comment by wenshan1** [comment]
This is a security hole for OPEN62541 client.

**Comment by jpfr** [comment]
Hello @wenshan1 ,

the PR #3549 was merged a few days ago.
This development has started quite some time earlier and also touches on this subject.

Did the PR fix the behavior already?
Otherwise, let's merge your fix on top.

The analysis is very welcome!

**Comment by wenshan1** [comment]
The PR #3549 don't fix this subject. 
Based on the latest source code, I have re-fixed this subject.

This fix Solution:
To open an encrypted security channel, we need to obtain the public certificate and the other end point information from the server first.
If the client isn't set the endpoint information:
a) The client open a secure channel with http://opcfoundation.org/UA/SecurityPolicy#None.
b) The client get the end point information from the server and set it to the client.
c)  The client disconnect the secure channel.

The client open an encrypted security channel with the end point information.

**Comment by wenshan1** [comment]
Check failed because the build environment preparation failed.

**Comment by jpfr** [comment]
Can you have a look at #3592?
That should do it for both the synchronous and asynchronous case.

**Comment by jpfr** [comment]
#3592 has landed.

The fix in #3592 uncovered a bug in the OpenSSL SecurityPolicies.
We had an access to uninitialized data. So there were intermittent fails.
https://github.com/open62541/open62541/commit/391d226c570dd29cb487f467f6941320452b1d96

Can you confirm that fix?

**Comment by jpfr** [comment]
Closed and fix verified via #3590.

**Pull request closed without merging**
