### PR TITLE
Fix log level in MonitoredItem_delete

### PR DESCRIPTION
**Pull request by StalderT**

### CODE REVIEW

**Comment by StalderT** [comment]
@jpfr can we remove the log like in 0.4 ?

**Comment by jpfr** [comment]
Can we make it symmetric?
If we log the creation, then we should also log the deletion at the same level.

**Comment by StalderT** [comment]
> Can we make it symmetric?
> If we log the creation, then we should also log the deletion at the same level.

Yes. The creation logs nothing. So, I remove the log. I have change the PR title.

**Comment by jpfr** [comment]
Logs are a good thing. What is the problem with this one?
Why not rather add one for creating monitoreditems?

The nodes that are subscribed would be good to know in an audit...

What are the criteria for adding or removing log messages?

**Comment by StalderT** [comment]
> Logs are a good thing. What is the problem with this one?

No problem for me if the log is not a warning. I revert the commit to the original state (Fix log level in MonitoredItem_delete). When I remove 100'000 items, my system slows down because it displays 100'000 warning.

> Why not rather add one for creating monitoreditems?

No problem for me. If someone would make this?

**Comment by jpfr** [comment]
I added two commits to get a "nice" log history for subscriptions and monitoreditems.

**Comment by StalderT** [comment]
@jpfr thanks!

**Pull request merged**
