### PR TITLE
Update open62541-config.cmake.in

### PR DESCRIPTION
**Pull request by XB32Z**
Missing the open62541_TOOLS_DIR variable

### CODE REVIEW

**Comment by jpfr** [comment]
Hey @XB32Z ,

can you sign the CLA attached to the pull request?

Then we can merge.

**Comment by XB32Z** [comment]
Hi, 
I am still checking some of the conditions, I'll come back to you later :-)

**Comment by Pro** [comment]
@XB32Z any update on the CLA?
FYI our CLA is similar to the CLA from the Eclipse Project, with some very minor modifications:
https://eclipse.org/legal/CLA.php

**Comment by XB32Z** [comment]
Done

**Pull request merged**
