### PR TITLE
[Reopened without merge conflicts] feat(pubsub) allow subscribing to NetworkMessages with multiple DataSetMessages

### PR DESCRIPTION
**Pull request by jmachauer-codewerk**
Iterating over all DataSetMessages, searching for all DataSetReaders which correspond to each DSM via DataSetWriterId and applying the processing of the DSM to all DSRs.

### CODE REVIEW

**Comment by jpfr** [comment]
Nice!
Can you extend one of the existing unit tests to this case?
So we have it future proof and refactoring-safe.

**Comment by jmachauer-codewerk** [comment]
I took an exisiting unit test and made two new ones. ` SinglePublishSubscribeMultipleDataSetReaders` tests the case, that two DataSetReaders are subscribed to the same DataSetWriterId. `PublishSubscribeMultipleDataSetMessages` has two DataSetWriters and two DataSetReaders with a one to one mapping. For me the unit tests didn't work reliably, sometimes (quite often) it seems to skip the subscriber callback which results in a seg fault when it tries to compare the published with the subscribed nodes, since the subscribed node had no chance of being written to.

**Comment by jpfr** [comment]
@jmachauer-codewerk thanks for the analysis.
Is the segfault a consequence of this PR or is there an underlying issue?
Anyhow, if you have a segfault backtrace ready, that would be interesting to understand the issue.

**Comment by jmachauer-codewerk** [comment]
-exec backtrace
#0  0x000055555556b37f in SinglePublishSubscribeInt64 (_i=0) at /home/jmachauer/repos/open62541-fork/tests/pubsub/check_pubsub_subscribe.c:961
#1  0x0000555555a2ad9b in tcase_run_tfun_nofork.isra ()
#2  0x0000555555a2b15c in srunner_run ()
#3  0x000055555557268d in main () at /home/jmachauer/repos/open62541-fork/tests/pubsub/check_pubsub_subscribe.c:1803

-exec backtrace -full
#0  0x000055555556b37f in SinglePublishSubscribeInt64 (_i=0) at /home/jmachauer/repos/open62541-fork/tests/pubsub/check_pubsub_subscribe.c:961
        _ck_x = 64
        _ck_y = -8928469837276744192
        retVal = 0
        dataSetFieldConfig = {dataSetFieldType = UA_PUBSUB_DATASETFIELD_VARIABLE, field = {variable = {configurationVersion = {majorVersion = 0, minorVersion = 0}, fieldNameAlias = {length = 15, data = 0x555555a2d822 "Published Int64"}, promotedField = false, publishParameters = {publishedVariable = {namespaceIndex = 1, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 1000, string = {length = 1000, data = 0x555555a2d822 "Published Int64"}, guid = {data1 = 1000, data2 = 0, data3 = 0, data4 = "\"آUUU\000"}, byteString = {length = 1000, data = 0x555555a2d822 "Published Int64"}}}, attributeId = 13, samplingIntervalHint = 0, deadbandType = 0, deadbandValue = 0, indexRange = {length = 0, data = 0x0}, substituteValue = {type = 0x0, storageType = UA_VARIANT_DATA, arrayLength = 0, data = 0x0, arrayDimensionsSize = 0, arrayDimensions = 0x0}, metaDataPropertiesSize = 0, metaDataProperties = 0x0}, rtValueSource = {rtFieldSourceEnabled = false, rtInformationModelNode = false, staticValueSource = 0x0}}}}
        newnodeId = {namespaceIndex = 1, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 1003, string = {length = 1003, data = 0x555555a2d832 "Subscribed Int64"}, guid = {data1 = 1003, data2 = 0, data3 = 0, data4 = "2آUUU\000"}, byteString = {length = 1003, data = 0x555555a2d832 "Subscribed Int64"}}}
        subscribedNodeData = 0x555555cbfb50
        attr = {specifiedAttributes = 0, displayName = {locale = {length = 5, data = 0x555555a2d725 "en-US"}, text = {length = 15, data = 0x555555a2d822 "Published Int64"}}, description = {locale = {length = 5, data = 0x555555a2d725 "en-US"}, text = {length = 15, data = 0x555555a2d822 "Published Int64"}}, writeMask = 0, userWriteMask = 0, value = {type = 0x555555b13608 <UA_TYPES+392>, storageType = UA_VARIANT_DATA, arrayLength = 0, data = 0x7fffffffd6f8, arrayDimensionsSize = 0, arrayDimensions = 0x0}, dataType = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 8, string = {length = 8, data = 0x0}, guid = {data1 = 8, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 8, data = 0x0}}}, valueRank = -2, arrayDimensionsSize = 0, arrayDimensions = 0x0, accessLevel = 1 '\001', userAccessLevel = 0 '\000', minimumSamplingInterval = 0, historizing = false}
        dataSetFieldIdent = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 53924, string = {length = 53924, data = 0x0}, guid = {data1 = 53924, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 53924, data = 0x0}}}
        readerGroupConfig = {name = {length = 16, data = 0x555555a2d0ed "ReaderGroup Test"}, securityParameters = {securityMode = 0, securityGroupId = {length = 0, data = 0x0}, keyServersSize = 0, keyServers = 0x0}, rtLevel = UA_PUBSUB_RT_NONE}
        targetVars = {targetVariablesSize = 0, targetVariables = 0x0}
        dataSetWriter = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 53942, string = {length = 53942, data = 0x0}, guid = {data1 = 53942, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 53942, data = 0x0}}}
        readerIdentifier = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 53954, string = {length = 53954, data = 0x0}, guid = {data1 = 53954, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 53954, data = 0x0}}}
        pMetaData = 0x7fffffffe078
        vAttr = {specifiedAttributes = 0, displayName = {locale = {length = 5, data = 0x555555a2d725 "en-US"}, text = {length = 16, data = 0x555555a2d832 "Subscribed Int64"}}, description = {locale = {length = 5, data = 0x555555a2d725 "en-US"}, text = {length = 16, data = 0x555555a2d832 "Subscribed Int64"}}, writeMask = 0, userWriteMask = 0, value = {type = 0x0, storageType = UA_VARIANT_DATA, arrayLength = 0, data = 0x0, arrayDimensionsSize = 0, arrayDimensions = 0x0}, dataType = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 8, string = {length = 8, data = 0x0}, guid = {data1 = 8, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 8, data = 0x0}}}, valueRank = -2, arrayDimensionsSize = 0, arrayDimensions = 0x0, accessLevel = 1 '\001', userAccessLevel = 0 '\000', minimumSamplingInterval = 0, historizing = false}
        writerGroup = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 53925, string = {length = 53925, data = 0x0}, guid = {data1 = 53925, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 53925, data = 0x0}}}
        readerConfig = {name = {length = 18, data = 0x555555a2d712 "DataSetReader Test"}, publisherId = {type = 0x555555b13560 <UA_TYPES+224>, storageType = UA_VARIANT_DATA, arrayLength = 0, data = 0x7fffffffd6f2, arrayDimensionsSize = 0, arrayDimensions = 0x0}, writerGroupId = 100, dataSetWriterId = 62541, dataSetMetaData = {namespacesSize = 0, namespaces = 0x0, structureDataTypesSize = 0, structureDataTypes = 0x0, enumDataTypesSize = 0, enumDataTypes = 0x0, simpleDataTypesSize = 0, simpleDataTypes = 0x0, name = {length = 12, data = 0x555555a2d680 "DataSet Test"}, description = {locale = {length = 0, data = 0x0}, text = {length = 0, data = 0x0}}, fieldsSize = 1, fields = 0x55555607bca0, dataSetClassId = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, configurationVersion = {majorVersion = 0, minorVersion = 0}}, dataSetFieldContentMask = 0, messageReceiveTimeout = 0, securityParameters = {securityMode = 0, securityGroupId = {length = 0, data = 0x0}, keyServersSize = 0, keyServers = 0x0}, messageSettings = {encoding = UA_EXTENSIONOBJECT_ENCODED_NOBODY, content = {encoded = {typeId = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 0, string = {length = 0, data = 0x0}, guid = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 0, data = 0x0}}}, body = {length = 0, data = 0x0}}, decoded = {type = 0x0, data = 0x0}}}, transportSettings = {encoding = UA_EXTENSIONOBJECT_ENCODED_NOBODY, content = {encoded = {typeId = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 0, string = {length = 0, data = 0x0}, guid = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 0, data = 0x0}}}, body = {length = 0, data = 0x0}}, decoded = {type = 0x0, data = 0x0}}}, subscribedDataSetTarget = {targetVariablesSize = 0, targetVariables = 0x0}}
        folderId = {namespaceIndex = 1, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 1002, string = {length = 93823560582122, data = 0x5 <error: Cannot access memory at address 0x5>}, guid = {data1 = 1002, data2 = 21845, data3 = 0, data4 = "\005\000\000\000\000\000\000"}, byteString = {length = 93823560582122, data = 0x5 <error: Cannot access memory at address 0x5>}}}
        publishedNodeData = 0x555555f68200
        pdsConfig = {name = {length = 21, data = 0x555555a2d6c7 "PublishedDataSet Test"}, publishedDataSetType = UA_PUBSUB_DATASET_PUBLISHEDITEMS, config = {itemsTemplate = {metaData = {namespacesSize = 0, namespaces = 0x0, structureDataTypesSize = 0, structureDataTypes = 0x0, enumDataTypesSize = 0, enumDataTypes = 0x0, simpleDataTypesSize = 0, simpleDataTypes = 0x0, name = {length = 0, data = 0x0}, description = {locale = {length = 0, data = 0x0}, text = {length = 0, data = 0x0}}, fieldsSize = 0, fields = 0x0, dataSetClassId = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, configurationVersion = {majorVersion = 0, minorVersion = 0}}, variablesToAddSize = 0, variablesToAdd = 0x0}, event = {eventNotfier = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 0, string = {length = 0, data = 0x0}, guid = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 0, data = 0x0}}}, filter = {elementsSize = 0, elements = 0x0}}, eventTemplate = {metaData = {namespacesSize = 0, namespaces = 0x0, structureDataTypesSize = 0, structureDataTypes = 0x0, enumDataTypesSize = 0, enumDataTypes = 0x0, simpleDataTypesSize = 0, simpleDataTypes = 0x0, name = {length = 0, data = 0x0}, description = {locale = {length = 0, data = 0x0}, text = {length = 0, data = 0x0}}, fieldsSize = 0, fields = 0x0, dataSetClassId = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, configurationVersion = {majorVersion = 0, minorVersion = 0}}, eventNotfier = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 0, string = {length = 0, data = 0x0}, guid = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 0, data = 0x0}}}, selectedFieldsSize = 0, selectedFields = 0x0, filter = {elementsSize = 0, elements = 0x0}}}}
        dataSetWriterConfig = {name = {length = 18, data = 0x555555a2d6ff "DataSetWriter Test"}, dataSetWriterId = 62541, dataSetFieldContentMask = 0, keyFrameCount = 10, messageSettings = {encoding = UA_EXTENSIONOBJECT_ENCODED_NOBODY, content = {encoded = {typeId = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 0, string = {length = 0, data = 0x0}, guid = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 0, data = 0x0}}}, body = {length = 0, data = 0x0}}, decoded = {type = 0x0, data = 0x0}}}, transportSettings = {encoding = UA_EXTENSIONOBJECT_ENCODED_NOBODY, content = {encoded = {typeId = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 0, string = {length = 0, data = 0x0}, guid = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 0, data = 0x0}}}, body = {length = 0, data = 0x0}}, decoded = {type = 0x0, data = 0x0}}}, dataSetName = {length = 0, data = 0x0}, dataSetWriterPropertiesSize = 0, dataSetWriterProperties = 0x0}
        publisherIdentifier = 2234
        publisherNode = {namespaceIndex = 1, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 1000, string = {length = 1000, data = 0x555555a2d822 "Published Int64"}, guid = {data1 = 1000, data2 = 0, data3 = 0, data4 = "\"آUUU\000"}, byteString = {length = 1000, data = 0x555555a2d822 "Published Int64"}}}
        publisherData = 64
        writerGroupConfig = {name = {length = 16, data = 0x555555a2d6ee "WriterGroup Test"}, enabled = false, writerGroupId = 100, publishingInterval = 5, keepAliveTime = 0, priority = 0 '\000', securityMode = UA_MESSAGESECURITYMODE_INVALID, transportSettings = {encoding = UA_EXTENSIONOBJECT_ENCODED_NOBODY, content = {encoded = {typeId = {namespaceIndex = 0, identifierType = UA_NODEIDTYPE_NUMERIC, identifier = {numeric = 0, string = {length = 0, data = 0x0}, guid = {data1 = 0, data2 = 0, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 0, data = 0x0}}}, body = {length = 0, data = 0x0}}, decoded = {type = 0x0, data = 0x0}}}, messageSettings = {encoding = UA_EXTENSIONOBJECT_DECODED, content = {encoded = {typeId = {namespaceIndex = 33264, identifierType = 21845, identifier = {numeric = 1442186912, string = {length = 93825002768032, data = 0x0}, guid = {data1 = 1442186912, data2 = 21845, data3 = 0, data4 = "\000\000\000\000\000\000\000"}, byteString = {length = 93825002768032, data = 0x0}}}, body = {length = 0, data = 0x0}}, decoded = {type = 0x555555b181f0 <UA_TYPES+19824>, data = 0x555555f606a0}}}, groupPropertiesSize = 0, groupProperties = 0x0, encodingMimeType = UA_PUBSUB_ENCODING_UADP, maxEncapsulatedDataSetMessageCount = 0, rtLevel = UA_PUBSUB_RT_NONE}
        writerGroupMessage = 0x555555f606a0
        folderName = {length = 12, data = 0x555555a2d680 "DataSet Test"}
        oAttr = {specifiedAttributes = 0, displayName = {locale = {length = 5, data = 0x555555a2d725 "en-US"}, text = {length = 12, data = 0x555555a2d680 "DataSet Test"}}, description = {locale = {length = 0, data = 0x0}, text = {length = 0, data = 0x0}}, writeMask = 0, userWriteMask = 0, eventNotifier = 0 '\000'}
        folderBrowseName = {namespaceIndex = 1, name = {length = 12, data = 0x555555a2d680 "DataSet Test"}}
#1  0x0000555555a2ad9b in tcase_run_tfun_nofork.isra ()
No symbol table info available.
#2  0x0000555555a2b15c in srunner_run ()
No symbol table info available.
#3  0x000055555557268d in main () at /home/jmachauer/repos/open62541-fork/tests/pubsub/check_pubsub_subscribe.c:1803
        tc_add_pubsub_readergroup = 0x555555b202a0
        tc_pubsub_publish_subscribe = 0x555555b20590
        suite = 0x555555b20a20
        suiteRunner = 0x555555b20d60
        number_failed = 21845

**Comment by jmachauer-codewerk** [comment]
The issue is independent of my PR. This can happens in the following tests for me:

```
SinglePublishSubscribeDateTime
SinglePublishSubscribeInt32
SinglePublishSubscribeInt64
SinglePublishSubscribeBool
SinglePublishSubscribewithValidIdentifiers
```

I deleted all but one test to isolate the issue, set a breakpoint in `UA_Server_processNetworkMessage` and found out, when it fails it never calls that function, went up the call chain and found out `UA_ReaderGroup_subscribeCallback` gets called either once or twice. The first time when it is added in `UA_ReaderGroup_addSubscribeCallback` but here the buffer has still length zero and it doesn't result in a call to  `UA_Server_processNetworkMessage`. The second time it works properly but thats the cases when it doesn't seg fault.

**Comment by jmachauer-codewerk** [comment]
The last fix is something i found with valgrind. It doesn't fix the issue with the tests crashing.

**Comment by jmachauer-codewerk** [comment]
I've isolated the issue here: 
#3835

**Comment by jmachauer-codewerk** [comment]
This PR should be ready for review now.

**Comment by jmachauer-codewerk** [comment]
reopened #3887

**Pull request closed without merging**
