### PR TITLE
[WIP] Switch PubSub to EventLoop model

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by jpfr** [comment]
> With the eventloop architecture, do we still have the possibility of switching mqtt library from MQTT-C to other libraries?

Yes we do. The MQTT implementation just has to implement the "ConnectionManager" interface from the `eventloop.h`.

**Comment by keba-estr** [comment]
@jpfr: Is this merge request still relevant or has it already been resolved with other merge requests?

**Comment by jpfr** [comment]
You are right. This is already resolved.

**Comment by jpfr** [comment]
@applea9, yes you can still use a different mqtt library.

Just add a second implementation of this
https://github.com/open62541/open62541/blob/master/arch/eventloop_mqtt.c
and add your custom "ConnectionManager" to the server configuration.

**Pull request closed without merging**
