### PR TITLE
Fix OverflowEvent counting

### PR DESCRIPTION
**Pull request by aDogCalledSpot**
Fixes https://github.com/open62541/open62541/issues/2072.

The problem wasn't an overflow, but an underflow. This was causing the notification queue size to be reduced below 0. Usages of eventOverflows should be correctly found now.

Also, there are generally less overflows being generated since the generation was moved outside of the while loop in UA_MonitoredItem_ensureQueueSpace. The wording in the specification isn't entirely clear here. In Part 4 5.12.1.5 it says that when "events are discarded" (plural), an overflow is generated but it only discards the first event "without discarding any other events". I  believe having only overflowEvent indicate the removal of numerous events sounds more reasonable than generating one for each them - opinions?

### CODE REVIEW

**Comment by jpfr** [comment]
Great! Looks good.

- I think we can reduce the indendation of the event-code in this change.
- Can you add a unit test for the queue overflow behaviour?

A proper review will then follow.

**Comment by aDogCalledSpot** [comment]
Unfortunately, the bug wasn't deterministic in any way and would only occur randomly under heavy load. I've added a small "stress test" which will generally cause a segfault after 35-40 loops if run on the current master branch but I can't entirely rule out that false positive outcomes may occur.

**Comment by jpfr** [comment]
> Unfortunately, the bug wasn't deterministic in any way and would only occur randomly under heavy load. 

In our unit test framework, we can reproduce everything deterministically.
Because we can manually "fake" the clock.

I will have a look at this. "Mostly works" doesn't cut it at this stage of the project.
The changes are looking good though!

**Comment by jpfr** [comment]
@aDogCalledSpot Your fix is correct. 👍 

I made a few changes to have the functionality more "in one place".
But the functional core of your fix remains.

Can you review the last commit in https://github.com/jpfr/open62541/tree/hotfix/event_queue_crash ?

**Pull request merged**
