### PR TITLE
WIP: fix(freertosLWIP): compilation fixes

### PR DESCRIPTION
**Pull request by vulptex**
Compiling open62541 under FreeRTOS + LWIP leads to multiple compilation error.

- ua_clock.c: added #include <FreeRTOS.h> (task.h:33 asserts otherwise)
- ua_architecture.h: added #include <strings.h> (strncasecmp declaration)
- us_lwip.h: added missing poll defines (network.tcp:66)

### CODE REVIEW

**Comment by vulptex** [comment]
This was against last release tag: 1.24.

Latest master is broken anyway because of _*posix_* source under arch.

**Comment by jpfr** [comment]
I changed the base of this to the 1.2 branch.
But then the PR suddenly has 250 commits.
Where do you need this to land?
And remove the WIP tag when we shall review.

**Comment by vulptex** [comment]
I suggest to close this (something went miserably wrong anyway by changing the base). 
This would be the trivial patch (https://github.com/vulptex/open62541/commit/e09a17660cd04729f80147c22a3f36630ebcbde4). 

For now, FreeRTOS is not compileable at all (latest master/main), at least for me.

**Comment by vulptex** [comment]
> I suggest to close this (something went miserably wrong anyway by changing the base). This would be the trivial patch ([vulptex@e09a176](https://github.com/vulptex/open62541/commit/e09a17660cd04729f80147c22a3f36630ebcbde4)).
> 
> For now, FreeRTOS is not compileable at all (latest master/main), at least for me.

close

**Pull request closed without merging**
