### PR TITLE
Fix stdlib includes

### PR DESCRIPTION
**Pull request by keba-estr**
Include stdlib.h where open62541 no longer does it

### CODE REVIEW

**Comment by jpfr** [comment]
We include it here: https://github.com/open62541/open62541/blob/84ebf2509a0465a0f20025ff03ece117b67fd885/include/open62541/config.h.in#L278

**Comment by keba-estr** [comment]
> We include it here:
> 
> https://github.com/open62541/open62541/blob/84ebf2509a0465a0f20025ff03ece117b67fd885/include/open62541/config.h.in#L278

@jpfr If UA_ENABLE_MALLOC_SINGLETON is set, stdlib.h is not included in the config.h file, but the test files still use definitions from stdlib.h.
Should we include stdlib.h in config.h independent of UA_ENABLE_MALLOC_SINGLETON?

**Comment by jpfr** [comment]
Then I prefer moving those uses of a "naked calloc" to UA_calloc instead.
It is even good that stdlib.h is not included when the malloc singleton is used.
So we get a compiler error if a "naked calloc" is used by mistake.

**Comment by keba-estr** [comment]
I removed the commit for the ua_pubsub_manager.c due to the commit "refactor(pubsub): Use UA_calloc everywhere in ua_pubsub_manager.c".
The test files need the include because of the usage of EXIT_SUCCESS.

**Comment by jpfr** [comment]
Nice, merged.

**Pull request merged**
