### PR TITLE
Fix ConditionId Search (Alarms and Conditions)

### PR DESCRIPTION
**Pull request by sqadasi**
both BranchId and the passed ConditionId should be equal if we want to set the Event Field "ConditionId" with the main ConditionId.
Using "!UA_NodeId_equal" at this place allows the program to go each time inside the if-clause because BranchId is always equal Null NodeId. As a result, each Event ends up having a ConditionId Field within it.
This should fix the problem in https://github.com/open62541/open62541/pull/3415#issuecomment-582816205 and is related to https://github.com/open62541/open62541/issues/3451#issuecomment-591349071

### CODE REVIEW

**Comment by jpfr** [comment]
Thanks for the fix.

The code makes a lot of implicit assumptions.
Can you add detailed comments to the use of the structure members for UA_Condition and UA_ConditionBranch?

I was certainly not aware that BranchId always equals Null NodeId and when this is the case.

https://github.com/open62541/open62541/blob/632d490d6dfbec8607ab83e8e12b4ffd677d0e35/src/server/ua_subscription.h#L78

**Comment by jpfr** [comment]
Can be merged with the additional comments.
👍

**Comment by sqadasi** [comment]
@jpfr thank you for the review:) I added some comments as requested.

**Comment by sqadasi** [comment]
@jpfr I've found a related error, which affects events when A&C is disabled. Please don't merge yet.

**Comment by sqadasi** [comment]
should work now:)

**Comment by jpfr** [comment]
Rebased.

**Comment by jpfr** [comment]
Merged. Thanks!

**Pull request merged**
