### PR TITLE
Update ua_services_subscription.c

### PR DESCRIPTION
**Pull request by StalderT**
fix https://github.com/open62541/open62541/issues/647

### CODE REVIEW

**Comment by Stasik0** [comment]
I am not sure what to do here, since we do not discriminate between the status of the actual datavalue and the internal service Service_Read_single, is it okay for everybody without any check @open62541/open62541-core? A trivial idea would be to check for any UA_STATUSCODE_GOOD* and let the values pass?

**Comment by StalderT** [comment]
I make some more tests and this PR is not a good idea. I think add a UA_STATUSCODE_GOOD*  check is better. I close this PR.

**Comment by StalderT** [comment]
something like that is better : 

```
    if(v.hasStatus != UA_STATUSCODE_GOOD) {
        result->statusCode = v.status;
        if (result->statusCode & 0xFF000000) {
            UA_DataValue_deleteMembers(&v);
            return;
        }   
    }   
    UA_DataValue_deleteMembers(&v);

```

**Comment by Stasik0** [comment]
@StalderT will you add a new pr?

**Pull request closed without merging**
