### PR TITLE
WIP: fixed network buffer (server only so far)

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by Stasik0** [comment]
More performance for single-thread?

**Comment by jpfr** [comment]
The second-to-last PR of a feature that was long in the making.

After this, we can interleave the decoding and processing of services.
Example:  In a ReadRequest, decode the first ReadValueId, process it and encode the (partial) response. Then decode the next ReadValueId.
This gives us end-to-end processing of the read-service without a single malloc.
This makes use the fastest server in the west. And it could even simplify some code.

**Comment by Pro** [comment]
@jpfr should this be included in the 0.3 release?

**Comment by jpfr** [comment]
This is currentlly only half-baked.
Support for the client and multithreading is currently lacking.
It would be nice to have. But I cannot justify the complexity for my projects atm.

**Comment by Pro** [comment]
@jpfr please note that I rebased your commit on current master (including force push)

**Comment by StalderT** [comment]
any news about this PR?

Probably, change : 

```
#ifndef UA_ENABLE_MULTITHREADING
# define FIXED_NETWORK_BUFFER true
UA_ByteString sendBuffer = {0, NULL};
UA_ByteString recvBuffer = {0, NULL};
#else
# define FIXED_NETWORK_BUFFER false
#endif
```

to 

```
#ifndef UA_ENABLE_MULTITHREADING
# define FIXED_NETWORK_BUFFER
UA_ByteString sendBuffer = {0, NULL};
UA_ByteString recvBuffer = {0, NULL};
#else
# undef FIXED_NETWORK_BUFFER
#endif
```
can resolve the errors

**Comment by jpfr** [comment]
outdated by the upcoming network layer

**Pull request closed without merging**
