### PR TITLE
Copy method node instead of referencing it

### PR DESCRIPTION
**Pull request by cabralfortiss**
This is a test solution for #1730. I tested locally and it worked. This pull request will help trigger a CI we have.

### CODE REVIEW

**Comment by jpfr** [comment]
This solves one special case where methods are children to several parents.

The general case is that objects, variables and methods can all have several parents.
How could we solve the general case that nodes are only auto-deleted when their last parent is deleted?

**Comment by Pro** [comment]
@jpfr could we use the following approach to automatically delete nodes when the last parent is deleted:

When deleting node `n1`, we check all its children ( e.g. `c1` and `c2`). A children is only a node which is referenced through a `HierarchicalReferences` i=33 or any subtype of that, which also includes `HasComponent`, `HasSubtype` and `Organizes`.

In `c1` we check if there is any other node except `n1` with `c1` as the reference target and hierarchical reference type (including subtypes). If yes, then do not delete `c1`. If there aren't any other nodes we can delete `c1` and continue recursively.

Does that solve the issue?

**Comment by jpfr** [comment]
We can do that for some nodes. But not for all.
Objects do not need a parent. And some objects do not have a parent.
There are even a few examples in the (full) ns0.

What are the cases when we need to trigger a check?

**Comment by sqadasi** [comment]
> 
> 
> We can do that for some nodes. But not for all.
> Objects do not need a parent. And some objects do not have a parent.
> There are even a few examples in the (full) ns0.
> 
> What are the cases when we need to trigger a check?

Objects without parents should be deleted without a problem in my opinion, because no other node have them as a child. So deleting them won't affect other nodes. However, parentless objects may have children with the hierarchical references "HasChild or its Subtypes (Aggregates or HasSubType)" to other objects, and deleting those children will remove them also from their other parents tree. For example, if we delete an object instance which has method nodes (not copied, only referenced), the method nodes will be removed from the ObjectType Node.

In the special case of methods, which are only referenced when creating object instances, we could exclude them when deleting their object instance parents. So the current implementation of referencing methods doesn't necessarily have to be changed to create copies of methods.

**Comment by Pro** [comment]
> We can do that for some nodes. But not for all.
> Objects do not need a parent. And some objects do not have a parent.
> There are even a few examples in the (full) ns0.

Can we add an additional internal boolean, which indicates if the node should be deleted when it has no children?
By default this is set to true, and only for some special cases (e.g. the one from NS0) we set it to false.

And we add a User API which allows to set this boolean. Like this we delete the nodes by default, but give the user the possibility to disable auto deletion.

> So the current implementation of referencing methods doesn't necessarily have to be changed to create copies of methods.

We have to change that, otherwise it's not possible to change the callback for a specific instance of a type. See https://github.com/open62541/open62541/issues/1730#issuecomment-391395119 for further explanation

**Comment by jpfr** [comment]
> Objects without parents should be deleted without a problem in my opinion,

Nope. There are objects without parents. For example ModellingRule_Mandatory.

> Can we add an additional internal boolean, which indicates if the node should be deleted when it has no children?

Can we do it the other way around?
Delete the node when the only parent is deleted.
We already do it similarly. *But*: We currently don't check if there are other parents.
That's not good.

https://github.com/open62541/open62541/blob/master/src/server/ua_services_nodemanagement.c#L1160

> We have to change that, otherwise it's not possible to change the callback for a specific instance of a type. See #1730 (comment) for further explanation

I consider that bad practice. You also don't switch method implementations for instances of a Java class.
The sane way would be to test internally which object calls the method.
An if required, one can always manually replace the method node with a custom one.

**Comment by Pro** [comment]
See https://github.com/open62541/open62541/issues/1730#issuecomment-527492175

**Pull request closed without merging**
