### PR TITLE
Fix bugs preventing encryption from working correctly

### PR DESCRIPTION
**Pull request by Infinity95**
This PR fixes a few issues that are only present when using actual encryption.

### CODE REVIEW

**Comment by Infinity95** [comment]
Since this is a blocker for the first SecurityPolicy PR i'd like to merge this soon. I'm working on fixing the bugs that are blocking this PR (mainly #1269)

**Comment by jpfr** [comment]
I added the fix in a separate PR #1280 so we get green integration tests for this ASAP.
@Infinity95 Let's talk later today on what is necessary to get this in...

**Comment by jpfr** [comment]
The async client faults are gone for good!
Thanks for finding the issue with the thread-local variables. That was pure gold. 😄 
It was indeed fixed on 0.2 but not yet ported to master.

**Comment by Infinity95** [comment]
Although it's strange, that the problem didn't appear earlier.

**Pull request merged**
