### PR TITLE
Clean up implementation specific behavior and some other code smells

### PR DESCRIPTION
**Pull request by Infinity95**

### CODE REVIEW

**Comment by jpfr** [comment]
Woah. Did you use a linter tool to find all those?

**Comment by Infinity95** [comment]
My IDE found some of those. The rest are from clang-tidy, which is also integrated into the IDE. :+1: 
I can then step through all found issues by pressing f2. Very neat feature.

**Comment by Pro** [comment]
Fyi we now also have custom make targets to run clang-tidy and clang-format:
https://github.com/open62541/open62541/blob/master/tools/cmake/linting_target.cmake#L3

At some point we may be able to just enable this clang-tidy build in CI and check every commit.

**Comment by Infinity95** [comment]
This can be merged now, if you want.

**Pull request merged**
