### PR TITLE
[REVIEW] #1914 - remove binary encoding from namespace generation

### PR DESCRIPTION
**Pull request by matkonnerth**
This pr shold remove the necessity of calling ua_encodebinary during namespace generation with the nodeset compiler.

I have added a testnodeset in examples/nodeset. I will move this to tests folder and write some tests.

### CODE REVIEW

**Comment by jpfr** [comment]
Wow! Looks good. Just two questions.

Can you explain why we should have EnumValueType in the minimal types?

We can now add custom datatypes to the server-config at runtime.
I did not see this feature used. Did I miss something?
Otherwise, if the datatype is not "registered", how is decoding possible, e.g. for a write-request?

**Comment by matkonnerth** [comment]
Hi!
1) EnumValueType: there ist a node called EnumValues:
take a look on ua_namespace0.c, here before my pr:
struct {
  UA_Int64 Value;
  UA_LocalizedText DisplayName;
  UA_LocalizedText Description;
} variablenode_ns_0_i_12169_EnumValueType_0_0_struct;

after pr: I use the generated UA_EnumValueType for setting up the value

2) that's interesting, thanks for the hint. I've to take a look on it.

**Comment by Pro** [comment]
Note that the corresponding necessary steps to remove encodeBinary are described in #1914

**Comment by Pro** [comment]
Hey @matkonnerth!
Thank you for your nice PR! Great work! I really like the simplification this PR brings.

I just had a look at it and the changes look really good! I also added an additional commit which removes some unnecessary code and does some further cleanup. Can you have a look at it?

Just as a summary:
With this PR we do not need the encodeBinary in the public API and the generated code since it is using the generated datatypes for initializing extension objects.

@matkonnerth is this PR ready to be merged? If yes, please squash your commits.
As far as I can see there are still some minor issues with parsing `<array1><Double>1.1</Double></array1>`. I would put that fix in a new PR since it is a new addition/feature and not a change of the current code.

**Comment by matkonnerth** [comment]
Hi @Pro!

I have a few more unit tests, I will add them, I think then you can merge this pr in.

One question:
Should I let the server_testnodeset in the examples or remove it from there?

**Comment by Pro** [comment]
Unit tests are always good!

I'd put the testnodeset.xml into the tools/test/nodeset_compiler folder since it's mainly there for unit tests. Maybe you can add a note in the example/nodeset/server_nodeset.xml and say something like `A more complete example can be found in tools/test/nodeset_compiler`. At a later stage we may extend the nodeset example further.

**Comment by matkonnerth** [comment]
I think if CI is green, you can merge it in.

**Comment by Pro** [comment]
Thank you @matkonnerth!!

Another issue closed :+1: 

We would be really happy if you could also contribute a fix for the `<array1><Double>1.1</Double></array1>` initialization and especially #1420

**Pull request merged**
