### PR TITLE
fix(pubsub): Fix MQTT publish

### PR DESCRIPTION
**Pull request by opcua-tsn-team-kalycito**
- Remove WriterGroup regist function for MQTT publish fix

### CODE REVIEW

**Comment by jpfr** [comment]
Check if this impacts #4215.

**Comment by jackybek** [comment]
I check my current copy of ua_pubsub_writer.c and confirmed that the highlighted segment in RED above is already removed.
As such, this change does not resolve issue #4215

**Comment by andreasebner** [comment]
I think this PR is finished? Can you please rebase it on the latest master. This will also retrigger the failed CI.

**Comment by opcua-tsn-team-kalycito** [comment]
Hi @andreasebner, yes this PR is finished and has been rebased on the latest master.

**Pull request merged**
