### PR TITLE
Be paranoid and not return garbage on any struct fields

### PR DESCRIPTION
**Pull request by glima**
While debugging an issue I came accross that (does not fix the issue but
might help not to screw on other scenarious).

### CODE REVIEW

**Comment by Stasik0** [comment]
The builds are failing. You may not use a single {0} if struct starts with a non-scalar.

**Comment by glima** [comment]
That is weird, no warnings here, even with -Wall. OK, doing a memset version so that all compilers are happy.

**Comment by Stasik0** [comment]
Proper initialization with 0 should be quicker ;) No idea why buikds/tests fail though. @jpfr, any idea?

**Comment by jpfr** [comment]
Compound literals are generally not supported in C++.
They are compiler-specific extensions only, which we disable by using quite strict build flags.

I'm also not sure this needs fixing. Accessing uninitialized values are the symptom, not the cause.
Zero-initializing is additional work and our tools, like valgrind and clang-analyzer, can no longer point out the symptoms to us.

**Comment by glima** [comment]
OK, fair. I guess what annoyed me when printing values inside GDB was the output for union fields, but now reading carefully I see we might be safe with what we had before, sorry for the noise. As the for the valgrind argument, I guess it would work just fine with or without the zeroing out initially.

**Pull request closed without merging**
