### PR TITLE
Client performance issue on large responses

### PR DESCRIPTION
**Pull request by anzeskerjanc**
## Problem:
Large responses on server are divided into 64k chunks.
Client for every received chunk increases (UA_realloc) complete message size for one chunk size(64k). On large responses this means a lot of memory allocating for increasing buffer size just for 64k.

## Solution:
Increase memory size for more than just newly arrived chunk.

### CODE REVIEW

**Comment by jpfr** [comment]
Hello @anzeskerjanc,

right. There's a lot of coyping going on for the realloc.
How about we keep the chunks in a linked list until the last one arrives?

Regards, @jpfr

**Comment by anzeskerjanc** [comment]
I think that linked list will also solve the problem.  
First copying while adding chunk to linked list and second after all chunks arrives. Without reallocating.

I can implement and try this option too.

**Comment by anzeskerjanc** [comment]
Option with linked list works slightly better than my previous solution. So this also solves my client problems...

Only I don't know what to do with these CI errors:
./tools/travis/travis_linux_script.sh: 9: ./tools/travis/travis_linux_script.sh: build-wrapper-linux-x86-64: not found
./tools/travis/travis_linux_script.sh: 14: ./tools/travis/travis_linux_script.sh: sonar-scanner: not found

**Comment by StalderT** [comment]
> Only I don't know what to do with these CI errors:
./tools/travis/travis_linux_script.sh: 9: ./tools/travis/travis_linux_script.sh: build-wrapper-linux-x86-64: not found
./tools/travis/travis_linux_script.sh: 14: ./tools/travis/travis_linux_script.sh: sonar-scanner: not found

Should be fixed in https://github.com/open62541/open62541/pull/1691/commits/c7655458b4d96a843f5eb194044e200960a14ec4 Wait for https://github.com/open62541/open62541/pull/1691 to be merged

**Comment by Pro** [comment]
The sonarcloud issue should not influence this PR anymore, since I changed the base to 0.3

@anzeskerjanc I would recommend that you create a separate branch for every PR, that makes it easier for you to add updates. Since changing the base now also changed your master branch you may want to reset your master and 0.3 branches to upstream after your PRs are merged. Thanks again for your contribution!

**Comment by anzeskerjanc** [comment]
ReleaseRecvBuffer is always called later from higher level (UA_Server_processBinaryMessage). So we must copy data for later processing.

There’s room for improvement. Now we copy data while assembling complete chunk from packets (processBinaryMessage) and while assembilng whole message from chunks(processCompleteChunk). I have improved only second copying, but perfect solution would be without copying.

**Comment by anzeskerjanc** [comment]
Is this issue with check_discovery test related with my pull request?

**Comment by Pro** [comment]
I just restarted the appveyor build, let's see if it runs through on the second try

**Comment by anzeskerjanc** [comment]
No luck with second try. Now error occurs during installation of sphinx.

**Comment by anzeskerjanc** [comment]
Is there anything I can do about this issue?

**Comment by Pro** [comment]
Oh sorry, completely forgot about this.
Can you rebase your commits onto current master. I think that the appveyor issue is already fixed there.

**Comment by anzeskerjanc** [comment]
Moved in https://github.com/open62541/open62541/pull/1797

**Pull request closed without merging**
