### PR TITLE
Add server get config public function

### PR DESCRIPTION
**Pull request by mlang-de**
As discussed in PullRequest #1846
Single PR for public function UA_Server_getConfig.

### CODE REVIEW

**Comment by mlang-de** [comment]
Is the function prototype ok?
```C
UA_ServerConfig* UA_Server_getConfig(UA_Server *server) 
```
Or should there a return value like this:
```C
UA_StatusCode UA_Server_getConfig(UA_Server *Server, UA_ServerConfig** config) 
```

**Comment by jpfr** [comment]
Perfect! We will merge once the CI setup has shaken out its current problems.

**Comment by Pro** [comment]
CI (at least travis) should be fixed with #1919

**Comment by jpfr** [comment]
Great! Merged.

**Pull request merged**
