### PR TITLE
Added connection logs

### PR DESCRIPTION
**Pull request by davy7125**
It helped me for debugging the connection process

### CODE REVIEW

**Comment by jpfr** [comment]
The changes look very nice. 👍 
We have a few arch-specific warnings that I have to ask you to shepherd through CI.
`format specifies type 'int' but the argument has type 'size_t'`

**Comment by davy7125** [comment]
It's now ok, sorry for the warnings

**Comment by jpfr** [comment]
`/home/travis/build/open62541/open62541/src/client/ua_client_connect.c:625:17: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘size_t’ [-Werror=format=]`

**Comment by jpfr** [comment]
Netter. Thanks!

**Comment by jpfr** [comment]
Merged. Thanks!

**Pull request merged**
