### PR TITLE
[Review] Added possibility to use SecurityPolicy None for discovery only

### PR DESCRIPTION
**Pull request by jonasgreen88**
If no endpoint with SecurityPolicy None is available, it shall be
possible to open a secure channel with SecurityPolicy None to perform
the discovery services GetEndpoints, FindServers and
FindServersOnNetwork. See issue #1936 for details.

### CODE REVIEW

**Comment by jpfr** [comment]
What is the advantage over keeping the Endoint for #None and disallowing the session in the AccessControl plugin?
https://github.com/open62541/open62541/blob/master/include/ua_plugin_access_control.h#L40

**Comment by jonasgreen88** [comment]
> What is the advantage over keeping the Endoint for #None and disallowing the session in the AccessControl plugin?
> [/include/ua_plugin_access_control.h@`master`#L40](https://github.com/open62541/open62541/blob/master/include/ua_plugin_access_control.h#L40)

The main reason for us why we would like to add this hidden DiscoveryOnly endpoint is that the server shouldn't present endpoints that the client will be unable to create sessions on and to only allow a minimum of services without message security (GetEndpoints, FindServers and FindServerOnNetwork).

**Comment by sqadasi** [comment]
It would be nice to have this feature. However, the current implementation forces NonSecure endpoint to be always only for discovery, which could be a problem for different users, who want to keep NonSecure endpoint also for creating sessions.
And as @jpfr said, there is no advantage in keeping/showing the NonSecure endpoint if we are not allowed to create session on it.
So, I would suggest creating the discoveryOnly flag inside the plugin (SecurityPolicy struct), so the user would be able to set it in their application. Inside the function `processMSG` we could access the discoveryOnly flag using the passed SecureChannel parameter to block creating the session, but not discover (just as @jonasgreen88 implemented). In addition, if the discoveryOnly flag is set by user, we should block giving that endpoint on `Service_GetEndpoints` responce, so the UA CLient won't know about it at all.

**Comment by jonasgreen88** [comment]
> It would be nice to have this feature. However, the current implementation forces NonSecure endpoint to be always only for discovery, which could be a problem for different users, who want to keep NonSecure endpoint also for creating sessions.

No it doesn't. If you want an endpoint with SecurityPolicy None you just have to configure the server with such an endpoint. If you only configure your server to support SecurityPolicyNone (but no endpoint with this policy) the clients can only setup a secure channel with SecurityPolicy None for discovery.

> And as @jpfr said, there is no advantage in keeping/showing the NonSecure endpoint if we are not allowed to create session on it.

This PR does not show an endpoint with SecurityPolicy None that does not allow to create sessions on it.

> So, I would suggest creating the discoveryOnly flag inside the plugin (SecurityPolicy struct), so the user would be able to set it in their application. Inside the function `processMSG` we could access the discoveryOnly flag using the passed SecureChannel parameter to block creating the session, but not discover (just as @jonasgreen88 implemented). In addition, if the discoveryOnly flag is set by user, we should block giving that endpoint on `Service_GetEndpoints` responce, so the UA CLient won't know about it at all.

This is exactly now we use it and its the intention it should work this way. If there is an endpoint created with SecurityPolicy None it is possible to create sessions on it. If there is no endpoint with this policy, but the server supports SecurityPolicy None the server only allows a secure channel with SecurityPolicy None to perform discovery.

**Comment by jpfr** [comment]
@jonasgreen88 to rebase and move the boolean flag to the server config.

**Comment by jpfr** [comment]
Merged to the 1.1 branch. Master is next.

**Pull request merged**
