### PR TITLE
Remove invalid free in ua_subscription_events

### PR DESCRIPTION
**Pull request by aDogCalledSpot**
An invalid free was causing the server to crash when either creating multiple monitored items on a single node or shutting down the client before closing the subscription.

### CODE REVIEW

**Comment by jpfr** [comment]
Won’t this lead to leaks?
Note that UA_Server_delayedFree was added exactly for this use case.

Also, we should cover the scenario you explained with a unit test. Otherwise this will regress over time.

**Comment by aDogCalledSpot** [comment]
The monitored item already is being freed with a delayedFree at the end of `UA_MonitoredItem_delete`, so memory leakts aren't happening. I'll make sure to add a unit test.

**Comment by jpfr** [comment]
Hmm. CLA-Assistant seems to hang on this issue.
@FlorianPalm, did you register CLA-Assistant for us?

It should be possible that you re-check the open PR on their site to unblock this one.

**Comment by Pro** [comment]
I regsitered CLAassistant and just did a recheck.
Anyways can you please check that you also have access to cla @jpfr.
If I remember correctly, every member of the orga should be able to control it

**Comment by jpfr** [comment]
Ah ok.
No I don't have access from my account.

**Pull request merged**
