### PR TITLE
[Review] feat(ci): Matrix build linux

### PR DESCRIPTION
**Pull request by GoetzGoerisch**

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
@jpfr not all green, but I'm not able to fix.
SKS builds are just stalling and then timinig out. Which is also the case for current master.

**Comment by jpfr** [comment]
Yes, we’ll look at the sks.
But there are also pure Valgrind builds failing.

**Comment by GoetzGoerisch** [comment]
Debug Build & Unit Tests (gcc, 32bit):
```
      Start  7: check_types_builtin_xml

7: Test command: /home/runner/work/open62541/open62541/build/bin/tests/check_types_builtin_xml
7: Working Directory: /home/runner/work/open62541/open62541/build/tests
7: Test timeout computed to be: 10000000
7: Running suite(s): Built-in Data Types 62541-5 Xml
7: 98%: Checks: 126, Failures: 2, Errors: 0
7: /home/runner/work/open62541/open62541/tests/check_types_builtin_xml.c:1676:F:xml_decode:UA_Float_xml_nan_decode:0: Assertion '((u8*)&out)[3] == 0x7f' failed: ((u8*)&out)[3] == 255, 0x7f == 127
7: /home/runner/work/open62541/open62541/tests/check_types_builtin_xml.c:1817:F:xml_decode:UA_Double_nan_xml_decode:0: Assertion '((u8*)&out)[7] == 0x7f' failed: ((u8*)&out)[7] == 255, 0x7f == 127
 7/85 Test  #7: check_types_builtin_xml .....................***Failed    0.01 sec
```

Debug Build & Unit Tests (clang):
All test fail with 
```
<empty stack>
```

TPM Tool Build: Cannot be build with OpenSSL 3.x

Valgrind Build fails with a Python Error (Python 3.10 vs 3.8)
```
96: ### PYTHON ERROR: File descriptors header not found: /home/runner/work/open62541/open62541/build/bin/tests/check_nodeset_loader_input.log
96: ==8788== FILE DESCRIPTORS: 4 open (3 std) at exit.
96: ==8788== Open file descriptor 3: /home/runner/work/open62541/open62541/build/bin/tests/check_nodeset_loader_input.log
96: ==8788==    <inherited from parent>
96: ==8788== 
96: ==8788== 
```

**Comment by NoelGraf** [comment]
I was able to identify the sources of the bugs and have already created some fixes for them.
However, the Matrix build still does not work and other errors have appeared.

Clang-Build Error: wrong clang version for ubuntu-22.04.
Valgrind-Build Error:  Error in the regex (valgrind_check_error.py)
gcc(32bit) Error: Adjustment in check_types_builtin_xml.c

For details: [Testing-Branch](https://github.com/NoelGraf/open62541/tree/feat_matrix_build)

**Comment by jpfr** [comment]
The rebase removed a bunch of errors.
No we have things like this:

`
101: ### PYTHON ERROR: File descriptors header not found: /home/runner/work/open62541/open62541/build/bin/tests/check_nodeset_loader_input.log
101: ==9036== FILE DESCRIPTORS: 4 open (3 std) at exit.
101: ==9036== Open file descriptor 3: /home/runner/work/open62541/open62541/build/bin/tests/check_nodeset_loader_input.log
101: ==9036==    <inherited from parent>
101: ==9036== 
101: ==9036== 
101: 
101/101 Test #101: check_nodeset_loader_input ..................***Failed    6.46 sec
`

Seems to be from the interrelation between valgrind and the python runner...

**Comment by NoelGraf** [comment]
The Python error comes from the valgrind_check_error.py script, where a regex is not quite correct. See the change I made in my testing branch.

**Comment by jpfr** [comment]
Thanks @NoelGraf , I extracted your fix into a new commit (with you as author) and pushed to this branch.
Pushing from my side is possible when the PR is open.

**Comment by jpfr** [comment]
Okay. Now this has uncovered something funny.
On some 32bit configurations the (unfinished) XML encoding fails.

```
      Start  7: check_types_builtin_xml

7: Test command: /home/runner/work/open62541/open62541/build/bin/tests/check_types_builtin_xml
7: Working Directory: /home/runner/work/open62541/open62541/build/tests
7: Test timeout computed to be: 10000000
7: Running suite(s): Built-in Data Types 62541-5 Xml
7: 98%: Checks: 126, Failures: 2, Errors: 0
7: /home/runner/work/open62541/open62541/tests/check_types_builtin_xml.c:1676:F:xml_decode:UA_Float_xml_nan_decode:0: Assertion '((u8*)&out)[3] == 0x7f' failed: ((u8*)&out)[3] == 255, 0x7f == 127
7: /home/runner/work/open62541/open62541/tests/check_types_builtin_xml.c:1817:F:xml_decode:UA_Double_nan_xml_decode:0: Assertion '((u8*)&out)[7] == 0x7f' failed: ((u8*)&out)[7] == 255, 0x7f == 127
 7/92 Test  #7: check_types_builtin_xml .....................***Failed    0.01 sec
```

**Comment by GoetzGoerisch** [comment]
> Okay. Now this has uncovered something funny. On some 32bit configurations the (unfinished) XML encoding fails.
> 
> ```
>       Start  7: check_types_builtin_xml
> 
> 7: Test command: /home/runner/work/open62541/open62541/build/bin/tests/check_types_builtin_xml
> 7: Working Directory: /home/runner/work/open62541/open62541/build/tests
> 7: Test timeout computed to be: 10000000
> 7: Running suite(s): Built-in Data Types 62541-5 Xml
> 7: 98%: Checks: 126, Failures: 2, Errors: 0
> 7: /home/runner/work/open62541/open62541/tests/check_types_builtin_xml.c:1676:F:xml_decode:UA_Float_xml_nan_decode:0: Assertion '((u8*)&out)[3] == 0x7f' failed: ((u8*)&out)[3] == 255, 0x7f == 127
> 7: /home/runner/work/open62541/open62541/tests/check_types_builtin_xml.c:1817:F:xml_decode:UA_Double_nan_xml_decode:0: Assertion '((u8*)&out)[7] == 0x7f' failed: ((u8*)&out)[7] == 255, 0x7f == 127
>  7/92 Test  #7: check_types_builtin_xml .....................***Failed    0.01 sec
> ```

Yes, thats the error I discovered in the first iteration.

**Comment by NoelGraf** [comment]
Yes, correct. I also made a change to check_types_builtin_xml on my testing branch for this bug.
There seems to be a difference in how NaN behaves with a newer GCC version on 32-bit versions.

**Comment by jpfr** [comment]
@NoelGraf cool.
Your branch puts everything into single commit. We should keep separate things in separate commits.

Please use ‘git format-patch’ and post your change to xml here. Then @GoetzGoerisch or I can apply. That avoids PR against branches across forks…

**Comment by jpfr** [comment]
No we get this error:
```
22: ==7724== 288 bytes in 1 blocks are possibly lost in loss record 7 of 11
22: ==7724==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
22: ==7724==    by 0x40147D9: calloc (rtld-malloc.h:44)
22: ==7724==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
22: ==7724==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
22: ==7724==    by 0x4C6F7B4: allocate_stack (allocatestack.c:430)
22: ==7724==    by 0x4C6F7B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
22: ==7724==    by 0x120AF6: setup (check_accesscontrol.c:45)
22: ==7724==    by 0x2F1FDD: srunner_run_setup (in /home/runner/work/open62541/open62541/build/bin/tests/check_accesscontrol)
22: ==7724==    by 0x2F213B: tcase_run_tfun_nofork (in /home/runner/work/open62541/open62541/build/bin/tests/check_accesscontrol)
22: ==7724==    by 0x2F2869: srunner_run_tagged (in /home/runner/work/open62541/open62541/build/bin/tests/check_accesscontrol)
22: ==7724==    by 0x120FDC: main (check_accesscontrol.c:109)
22: ==7724== 
22: 
 22/101 Test  #22: check_accesscontrol .........................***Failed   10.25 sec
```

This does happen only on a few architecture.
Probably this is something weird within the glibc standard library.
If yes we can suppress via `/tools/valgrind_suppressions.supp`.

**Comment by GoetzGoerisch** [comment]
@NoelGraf could you please look into this as Julius suggested?

**Comment by GoetzGoerisch** [comment]
@NoelGraf three jobs are still failing. Maybe you have time to take a look.
All are Valgrind related.

**Linux Build & Test / ubuntu-22.04-PubSub SKS Build & Unit Tests (gcc):**
The following tests FAILED:
	 70 - check_pubsub_sks_push (Failed)
	 71 - check_pubsub_sks_pull (Failed)
	 73 - check_pubsub_sks_client (Failed)
	 
**Linux Build & Test / ubuntu-22.04-Valgrind Build & Unit Tests with MbedTLS (gcc)**
41 tests failed

**Linux Build & Test / ubuntu-22.04-Valgrind Build & Unit Tests with OpenSSL (gcc)**
41 tests failed

**Comment by NoelGraf** [comment]
@GoetzGoerisch If I see it correctly, the valgrind flag has not yet been removed. I suspect that this is the problem as I described in my last comment.

**Comment by jpfr** [comment]
Finally merged 👍

**Pull request merged**
