### PR TITLE
[WIP] Remove OR'ing statuscodes

### PR DESCRIPTION
**Pull request by Infinity95**
By OR'ing statuscodes we lose information in some cases and in those cases where they don't overlap it complicates getting the actual statuscodes.
Also in some cases we only check at the end of a function if we encountered an error. If the error happens at the beginning of the function the rest is still executed which might lead to other problems.

### CODE REVIEW

**Comment by jpfr** [comment]
This looks good!
But CI will probably fail in some places.

Some compilers, e.g. old VisualStudio, do not want to `goto` over variable declarations.
You might have to move some variable declarations to the front.

Or avoid goto entirely by moving code into a new function that is wrapped by the cleanup /error part.

**Comment by jpfr** [comment]
Oh. He ate it. Cool...

**Comment by Infinity95** [comment]
I'm still working on some other files, so i'll just create a new PR for those as soon as they are done.

**Comment by jpfr** [comment]
You can prefix the PR title with [WIP] if it is not done.

**Comment by Infinity95** [comment]
As was the case with this one 😅

**Pull request merged**
