### PR TITLE
fix(plugin): remove overhead for thumbprint creation (MbedTLS)

### PR DESCRIPTION
**Pull request by mcpat**
This PR removes two allocations while creating the certificate thumbprint and instead does the binary to hexstring conversion in place.

### CODE REVIEW

**Comment by jpfr** [comment]
Yes. It is better to stack-allocate where you have a fixed size.
But please keep the magic to a minimum.
Use deps/itoa.h to print hex with base 16.

**Comment by mcpat** [comment]
Using deps/itoa.h either requires to handle alignment properly (new magic of different kind) or to call the conversion function byte-wise (expensive). I do not like either choice so feel free to just close this PR.

**Comment by jpfr** [comment]
The speed improvement is still a very good improvement.
What we could do:

- Use `char buf[UA_SHA1_LENGTH];` to stack-allocate the fixed size buffer.
Instead of the malloc/free pair.

- Provide a reference for the hex conversion you did.
This is tricky code. And a good reference would help to increase our confidence.
Otherwise we need to do a pretty deep review to ensure there are no bugs.

**Comment by mcpat** [comment]
Would it make sense to extend deps/itoa.h to also support a function to convert an arbitrary buffer of bytes into its ASCII representation? I could then re-use existing code without the need of calling the conversion function multiple times.

**Comment by jpfr** [comment]
Nice, thanks.

**Pull request merged**
