### PR TITLE
Put binaries in bin folder instead of build

### PR DESCRIPTION
**Pull request by Infinity95**
This change puts the binary files that are generated when building into a bin folder. I find it easier to acces compiled files instead of searching for them in the build directory.

### CODE REVIEW

**Comment by jpfr** [comment]
Hello Mark,
looks good. Can you also adjust the scripts in /tools/travis?
They expect the binaries at a certain location.

**Comment by Infinity95** [comment]
Didnt know that. I will look into it.

**Comment by jpfr** [comment]
Nearly there. Some unit tests are still hardcoded.
I will squash/merge as soon as travis goes green.

**Comment by Infinity95** [comment]
I believe everything should work now.

**Comment by jpfr** [comment]
Thanks. Merged.

**Pull request merged**
