### PR TITLE
fix if/while/for/switch typo

### PR DESCRIPTION
**Pull request by StalderT**

### CODE REVIEW

**Comment by Pro** [comment]
@jpfr is this the style we want? Maybe we should try to include a code style checking in CI using lint?

**Comment by jpfr** [comment]
@Pro It should be the coding style we collectively decide on.
As of right now it is the consensus that most of the code-base follows.

I'm not entirely happy with the indendation of method arguments in the next line.
Do you have experience with clang-format?

@StalderT 👍 for the changes. The attention to detail is great!

Building PDF on appveyor fails atm.
This is disabled in another PR that will land soonish.

**Comment by StalderT** [comment]
https://google.github.io/styleguide/cppguide.html#Function_Declarations_and_Definitions
https://google.github.io/styleguide/cppguide.html#Function_Calls

**Comment by Pro** [comment]
@StalderT @jpfr note that the google cppguide requires a space before ( in if(

**Comment by StalderT** [comment]
> note that the google cppguide requires a space before ( in if(

yes I saw! :-(

```
root@debian:/data/open62541# cat CPPLINT.cfg 
set noparent
filter=-readability/casting
filter=-build/include_subdir

root@debian:/data/open62541# python cpplint.py src/client/ua_client.c
src/client/ua_client.c:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
src/client/ua_client.c:21:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:25:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:32:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:44:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:48:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:50:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:81:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:104:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:107:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:113:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:120:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:121:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:123:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:124:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:133:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:138:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:141:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:150:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:151:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:174:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:183:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:197:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:198:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:203:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:204:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:213:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:215:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:221:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:233:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:235:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:237:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:243:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:255:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:265:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:267:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:272:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:280:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:285:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:287:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:289:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:289:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:290:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:295:  Missing space before ( in while(  [whitespace/parens] [5]
src/client/ua_client.c:308:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:309:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:310:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:321:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:322:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:323:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:327:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:341:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:345:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:361:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:362:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:369:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:370:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:377:  Missing space before ( in if(  [whitespace/parens] [5]
src/client/ua_client.c:386:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:390:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:391:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/client/ua_client.c:392:  Missing space before ( in if(  [whitespace/parens] [5]
Done processing src/client/ua_client.c
Total errors found: 62
```

**Comment by Pro** [comment]
See #1538 regarding code style discussion

**Pull request merged**
